### ISSUE TITLE
Improve normalized_labeling speed

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#103]
### Problem

When iterating over PeakData rows (*e.g.* #77, #22), computing the cached_properties is very slow, making the page take nearly 15 seconds to load.

### Steps to reproduce

1. Get a list of all PeakGroups, iterate over

### Current behavior

Page takes ~15 seconds to fully render

### Expected behavior

The page should load much faster (ideally in less than a second, but any improvement is welcome)

### Suggested Change

* Write a test to time the calculation of  normalized_labeling to aid in profiling
* Move calculation of serum tracer value to a cached_property of the animal and use that when calculating normalized labeling

### Comment

A longer term solution could be to calculate this and store it in the database when data is updated.

-----

### Assumptions

- 

### Requirements

- Calculation of many PeakGroup.normalized_labeling values for a given study should be faster
- Ideally, the value should be obtainable in the same way (property of PeakGroup)

### Limitations

- 

### Affected/Changed Components

- PeakGroup and Animal classes

#### Code Change Description *(Pseudocode optional)*

Move calculation of serum tracer value to a cached_property of the animal and use that when calculating normalized labeling

#### Tests

Test to time the calculation of  normalized_labeling

**Comment by hepcat72** [comment]
I believe this was fixed.
