### ISSUE TITLE
Improve enrichment_fraction speed

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#104]
### Problem

When iterating over PeakData rows (*e.g.* #77, #22), computing the cached_properties is very slow, making the page take nearly 15 seconds to load.

### Steps to reproduce

1. Get a list of all PeakGroups for a study, iterate over them, printing the [`enrichment_fraction`](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/82b17fb59d220a7565b468f9b128e328a49b744a/DataRepo/models.py#L386)

### Current behavior

Page takes ~15 seconds to fully render

### Expected behavior

The page should load much faster (ideally in less than a second, but any improvement is welcome)

### Suggested Change

* Write a test to time the calculation of  [`enrichment_fraction`](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/82b17fb59d220a7565b468f9b128e328a49b744a/DataRepo/models.py#L386) to aid in profiling
* Use F string to calculate the sum in a single query
* Use the PeakGroup.atom_count function to avoid querying for a compound

### Comment

A longer term solution could be to calculate this and store it in the database when data is updated.

-----

### Assumptions

- 

### Requirements

- Calculation of many PeakGroup.enrichment_fraction values for a given study should be faster
- Ideally, the value should be obtainable in the same way (property of PeakGroup)

### Limitations

- 

### Affected/Changed Components

- PeakGroup class

#### Code Change Description *(Pseudocode optional)*

* Use F string to calculate the sum in a single query
* Use the PeakGroup.atom_count function to avoid querying for a compound

#### Tests

Test to time the calculation of  [`enrichment_fraction`](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/82b17fb59d220a7565b468f9b128e328a49b744a/DataRepo/models.py#L386) to aid in profiling

**Comment by hepcat72** [comment]
I believe this was fixed.
