### ISSUE TITLE
Compounds sheet was unaltered, but resulted in ConflictingValueErrors

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#1061]
### Problem

After creating a template and filling in details, validation raised `ConflictingValueErrors` regarding compounds that were unaltered in the template.

### Steps to reproduce

See #1034 

1. To 
2. Be
3. Described

### Current behavior

```
Conflicting values encountered during loading:
During the processing of sheet [Compounds] in /tmp/study.xlsx...
Creation of the following Compound record(s) encountered conflicts:
File record: {'name': 'aconitate', 'formula': 'C6H6O6', 'hmdb_id': 'HMDB0000072'} (on row(s): 3)
Database record: {'name': 'aconitate', 'formula': 'C6H10O3', 'hmdb_id': 'HMDB0000072'}
[formula] values differ:
- database: [C6H10O3]
- file: [C6H6O6]
```

### Expected behavior

Since the compounds in the template were automatically populated, there should be no errors resulting from them. They are not part of the submission, but used only for reference.

### Suggested Change

None provided

### Comment

None

-----

### Assumptions

1. List of assumptions made WRT the code
2. E.g. We will assume input is correct (explaining why there is no validation)

### Limitations

1. A list of things this work will specifically not do
2. E.g. This feature will only handle the most frequent use case X

### Affected Components

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

#### GUI Change description

None provided

#### Code Change Description

None provided

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by hepcat72** [comment]
This is not a code bug.  I believe this is a bug in the Rabinowitz data.  See this text in a comment in the issues you linked:

> Ah! Yes. This appears real. I suspect what happened here was a get-or-create from the compound name and formula from one of the peak annotation files, which prompted an autofill to the compounds sheet. And, looking at the dev compound records, my bet is that the wrong formula or compound name was assigned for: Trans-aconitic acid; trans-aconitic acid.

So the Compounds template is not **only** populated from the database.  It first populates the compound name and formula extracted directly from the peak annotations file, and that file I strongly suspect (though I did not confirm), assigns the wrong name or formula to the peak (confusing the compound aconite and trans-aconitic acid).  So this issue should probably be moved to the rabinowitz repo and marked here as invalid.

**Comment by lparsons** [comment]
Excatly right @hepcat72. The peak annotation file lists a compound called "aconitate" with a formula of "C6H6O6". That is clearly incorrect, as there are records in the compound database for that name separate from that formula:

```
aconitate	C6H10O3	HMDB0000072	aconitic acid
```
https://github.com/PrincetonUniversity/tracebase-rabinowitz-data/blob/5a251b11b1a3ba3db818c446dcb734d298318bd5/compounds/compounds.tsv#L137

```
dehydroascorbic acid	C6H6O6	HMDB0001264	
```
https://github.com/PrincetonUniversity/tracebase-rabinowitz-data/blob/5a251b11b1a3ba3db818c446dcb734d298318bd5/compounds/compounds.tsv#L237


In a case like this, where we cannot properly do a lookup of compound by the name and formula presented in the peak annotation file, I would have expected this to be flagged as a "new" compound (or as an error) during template creation. Note for future testing (#1034 ) we should test cases with new compounds, tissues, methods, etc.

Now, how this continues to get loaded without error in TraceBase is a bit concerning, but at least we know it won't happen in the future since this loading code seems to better enforce consistency.

**Comment by hepcat72** [comment]
The old code only looked up the compound using only the compound name (which is why it loaded in the past without error).  The new code does a get or create using both the name and formula (since those are both available).  This results in what you observed: a `ConflictingValueError` during the validation step.

> I would have expected this to be flagged as a "new" compound (or as an error) during template creation.

The way it was designed was to flesh the template with existing data and dumbly filled in peak annotations-file-extracted data (that doesn't match existing data), which is what it did.  It doesn't do a lookup on the dumbly filled in data.  It just fills it in.  I could add checks, but I viewed it as more of a validation issue (i.e., for later in the validation step), which is what happened.
