### ISSUE TITLE
Create a consolidated list of TraceBase terms and definitions

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#107]
Create a consolidated list of terms used in TraceBase along with the definition of those terms as well as a list of synonyms.

The list should be a markdown file in the repository.

Some sources for the list of terms include:
* [Variable Definitions](https://docs.google.com/spreadsheets/d/1UI2Fs1hW6RiDcM7JhJYfG6yhecSQ8u7A9vaxSrJGeW0/edit?usp=sharing)
* [TraceBase Data Model](https://github.com/Princeton-LSI-ResearchComputing/tracebase/issues/16) and [models.py](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/DataRepo/models.py)
* [tissueDataProcessed033120_withSoleus](https://docs.google.com/spreadsheets/d/1waEyLnC3VcNz43VVT1t7Sp0td8XcVf8rrzDdCuDUVcA/edit?usp=sharing)
* [serumlabeling](https://docs.google.com/spreadsheets/d/1MH7J3bsLERc5FY0NDhYsSI7pK3P-Q1iXwA4Hb8S6Ylk/edit?usp=sharing)
* [Copy of serumlabeling with suggested new column names](https://docs.google.com/spreadsheets/d/1slSFUVF-OFQbe9vEWH491bFm1Su3X_BSjYvIadiem38/edit?usp=sharing)
* [TraceBase SampleTable Template](https://docs.google.com/spreadsheets/d/1To3495KxJkAtnAD9KVdzc162zKbNiYuPEVyPseQPjMQ/edit?usp=sharing)
* [Proposed Output Tables](https://docs.google.com/spreadsheets/d/1b74-f473-K4EewmCaZTv5CfVFDVglI1xyaHlKBGUAqI/edit?usp=sharing)

**Comment by lparsons** [comment]
See the Google Doc for a list of [TraceBase Terms and Definitions](https://docs.google.com/spreadsheets/d/1iOHcBc2bY5vmdFfzam9-C3XkLsnoBt2WCZOG1qmzy4A/edit?usp=sharing).

**Comment by hepcat72** [comment]
> See the Google Doc for a list of [TraceBase Terms and Definitions](https://docs.google.com/spreadsheets/d/1iOHcBc2bY5vmdFfzam9-C3XkLsnoBt2WCZOG1qmzy4A/edit?usp=sharing).

What do you think about:
1. Adding a field name to the tight of the table name column (for extra clarity - if the field exists)
2. Updating the help text for fields in models.py with the descriptions in the google doc

**Comment by lparsons** [comment]
> 1. Adding a field name to the tight of the table name column (for extra clarity - if the field exists)

Done

> 2. Updating the help text for fields in models.py with the descriptions in the google doc

Most of these were taken from `models.py`, but it might be good to identify any that aren't correct. One thing that might be missing is the synonym. Also, for properties (not fields), there is no `help_text` (since that is used in the admin interface) so for now, we're keeping it in the function docstring.
