### ISSUE TITLE
Consistency in templates and views

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#109]
Noting a few issues raised in #102 that should be addressed in the next PR:

* [Remove commented import in views.py](https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/102#discussion_r644806700)
* [Fix spelling of Icahn in navbar](https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/102#discussion_r644961042)

Rejected:

* [Update comment to clarify class view variable defaults](https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/102#discussion_r645042074)
* [Be consistent with specification of class view defaults](https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/102#discussion_r645038206)

**Comment by fkang-pu** [comment]
For Compound and Study, I include `context_object_name` and `template_name` for list view, though Django's default name for object list and template location are used.  I think it's easier to read and review the code for a view and it's template file. Should I do the same for the other models or you have different opinion?

**Comment by lparsons** [comment]
@fkang-pu Your plan sounds good to me. I'm happy as long as we are consistent.

**Comment by hepcat72** [comment]
Yeah, I say set them explicitly for all of the generic views.  I agree it's easier to read/follow.
