### ISSUE TITLE
Task: Create development plan and issues to address phase 2 of submission flow

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#1151]
The current plan for phase 2 of the submission flow is in #1040 . Once we've gotten some feedback from researchers about the current (phase 1) submission process, we should update the plan in the discussion and then create a development plan here and create issues for each task.

**Comment by hepcat72** [comment]
I created issues for the existing phase 2 plan.  I'm going to mark this as done.  We can update it as-needed based on feedback.
