### ISSUE TITLE
Cannot add compound synonym if the compound isn't present

### ISSUE THREAD

**Issue by hepcat72** [Princeton-LSI-ResearchComputing/tracebase#1153]
@mneinast - So I think I can accurately guess what's going on here.  Here's what I expect happened.

- When you ran the start page to autofill, the compound synonym didn't exist.
- The compound existed, but it wasn't autofilled in the compounds sheet because the synonym search failed to find it
- So the autofill added a partial record based on the information it got from the peak annotation file (the synonym and the formula).  It created new rows for that data and could not fill in the HMDB ID nor the synonyms
- Then, when you went to validate, having added the HMDB ID, (which is required to be unique), you ended up with a conflicting value error.
- the solution is to add the synonyms from the Peak Annotations file to the existing compound records as synonyms instead of as separate compound records.
- The problem is that the autofill doesn't provide that compound record for you to edit.

I think that the solution here is to auto-populate all existing compounds and hope that the user will see that the autofilled row for what is essentially a compound synonym of another row and delete that row and add the synonym to the other record.

I'll create an issue for this.

_Originally posted by @hepcat72 in https://github.com/Princeton-LSI-ResearchComputing/tracebase/issues/1049#issuecomment-2289194431_

**Comment by mneinast** [comment]
If we include all compounds in tracebase, it could be helpful to clearly indicate which ones were detected in the data (ie a column showing the number of peak annotation files containing that compound in this submission, or perhaps just a T/F indicating it is present or not).  Also to clearly indicate the compounds which are found in the submitted data but not in the tracebase compounds list.
