### ISSUE TITLE
Exception about Tracer Row Group column missing value

### ISSUE THREAD

**Issue by hepcat72** [Princeton-LSI-ResearchComputing/tracebase#1166]
### Problem

Uncaught exception on submission page when Tracer (or Infusate) Row Group column has a missing value.

### Steps to reproduce

1. Submit [MASTER STUDY DOC FOR TRACEBASE_exp011b3_240816_breaks validation.xlsx](https://github.com/user-attachments/files/16662102/MASTER.STUDY.DOC.FOR.TRACEBASE_exp011b3_240816_breaks.validation.xlsx) on the validate page

### Current behavior

![image](https://github.com/user-attachments/assets/5d628fe9-6bd5-43d4-8687-2fd5515553bf)

### Expected behavior

Regular red error displayed in the status report.

### Suggested Change

Catch an error where the value is cast as an `int` and buffer an `InfileError`, then skip the rest of that row.

### Comment

validation broken by a missing value in the Tracer Row Group:  I am taken to an error page like this one 
(see the screenshot above)

_Originally posted by @mneinast in https://github.com/Princeton-LSI-ResearchComputing/tracebase/discussions/1040#discussioncomment-10384526_

-----

### Assumptions

1. List of assumptions made WRT the code
2. E.g. We will assume input is correct (explaining why there is no validation)

### Limitations

1. A list of things this work will specifically not do
2. E.g. This feature will only handle the most frequent use case X

### Affected Components

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

#### GUI Change description

None provided

#### Code Change Description

None provided

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by mneinast** [comment]
I couldn't quite copy/paste the error here, but here are two versions of the study doc (one that works and one that doesn't).

[MASTER STUDY DOC FOR TRACEBASE_exp011b3_240816.xlsx](https://github.com/user-attachments/files/16662101/MASTER.STUDY.DOC.FOR.TRACEBASE_exp011b3_240816.xlsx)


[MASTER STUDY DOC FOR TRACEBASE_exp011b3_240816_breaks validation.xlsx](https://github.com/user-attachments/files/16662102/MASTER.STUDY.DOC.FOR.TRACEBASE_exp011b3_240816_breaks.validation.xlsx)
 - the only change is in the Tracers sheet:  the Tracer Row Group field for water was deleted.
