### ISSUE TITLE
Time Collected is None when it should be Zero

### ISSUE THREAD

**Issue by mneinast** [Princeton-LSI-ResearchComputing/tracebase#1187]
### Problem

Some samples are collected at time "zero" relative to the start of the infusion.  These are almost always a serum sample collected just before the infusion starts.  In TraceBase, the Time Collected for any sample which should be `0` has been converted to `None`.

### Steps to reproduce

Go https://tracebase.princeton.edu/DataRepo/search_advanced/
 - Output Format = `PeakGroups`
 - Match `all`
 - Time Collected (since infusion) = `is` `0` `minutes`

No PeakGroups will be found.

Now, you can find these by changing Time Collected (since infusion) = `does not have a value (ie. is None)`.  You will see several thousand PeakGroups.  Running the "Stats" will show you that all of these samples are some form of "Serum" tissue.

### Expected behavior

Samples which were marked in the study doc as time collected = `0` should maintain that value in Tracebase.

There may be samples whose Time Collected is truly `None`, although i can't think of what they would be.  These should remain as `None`.

### Suggested Change

Perhaps the loading scripts convert `0` to `None` somewhere?

### Comment

-----

### Assumptions

1. List of assumptions made WRT the code
2. E.g. We will assume input is correct (explaining why there is no validation)

### Limitations

1. A list of things this work will specifically not do
2. E.g. This feature will only handle the most frequent use case X

### Affected Components

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

#### GUI Change description

None provided

#### Code Change Description

None provided

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by hepcat72** [comment]
This was fixed in the loader refactor.  (It was a loading issue and there needs to be a migration to deal with already loaded data).
