### ISSUE TITLE
Command line "loader" script for compound text files

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#13]
* [x] make compound data file
* [ ] Script to load compound records from a csv/tsv file
* [ ] List of the core compounds
* [ ] Tests

**Comment by jcmatese** [comment]
I can try to acquire the data file (prerequisite for first checkbox)

**Comment by jcmatese** [comment]
[Here is a file](https://docs.google.com/spreadsheets/d/1tS6C1HEPA-aUQKtYVoH7t4mM7HVyEQPJ8H_TAlpglkA/edit?usp=sharing), which would at least provide some test data.  May need to be pared down, but I would probably just load the HMDB columns with the first column as a "preferred/display name" or synonym.
