### ISSUE TITLE
Averaged PeakGroups advanced search

### ISSUE THREAD

**Issue by hepcat72** [Princeton-LSI-ResearchComputing/tracebase#131]
### Feature Inspiration

The averaged peakgroups tab of [customer-desired consolidated view formats](https://docs.google.com/spreadsheets/d/1b74-f473-K4EewmCaZTv5CfVFDVglI1xyaHlKBGUAqI/edit#gid=62403243)

This is an extension of issues:
- #116
- #128

### Feature Description

This will add an output format named averaged peakgroups to the advanced search hierarchical dynamic form code of #128.

### Alternatives Considered

none

### Comment

none

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by hepcat72** [comment]
Looking back on this and understanding the data more than I did on July 1, 2021, I think this is *done*.  OK to close?

@lparsons

**Comment by lparsons** [comment]
This type of analysis is being done in R for the time being: [FCirc plots](https://rpubs.com/lparsons/tracebase-fcirc-plots) and [PeakGroup plots](https://rpubs.com/lparsons/tracebase-peakgroup-plots), so I think it's OK to close this for now. If new built in functionality is warranted, we will create new, more specific issues.

**Comment by lparsons** [comment]
I'd vote to close it. The intention was a more generalized grouping and aggregation functionality, but that is too vague to be very useful at this stage, imo.
