### ISSUE TITLE
Accept separate tables to import Animals and Samples

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#136]
### Feature Inspiration

Currently, we import an single sample table that includes data about each sample and each animal (mouse). In fact, many of the columns are related to the animal, and thus end up being repeated many times for each sample from a given animal. It would be simpler for researchers to provide this data as separate tables.

### Feature Description

* Create a load_animals command that will load animal data from an animal table (see Animals sheet in [TraceBase Animal and Sample table templates](https://docs.google.com/spreadsheets/d/1To3495KxJkAtnAD9KVdzc162zKbNiYuPEVyPseQPjMQ/edit?usp=sharing)).
* Update the load_samples command to load sample data from an sample table (see Samples sheet in [TraceBase Animal and Sample table templates](https://docs.google.com/spreadsheets/d/1To3495KxJkAtnAD9KVdzc162zKbNiYuPEVyPseQPjMQ/edit?usp=sharing)). Animals must be loaded first.
* Split the example data sample table files into separate animal table and sample table files

### Alternatives Considered

* Updating the `load_samples` command to (optionally) take two tables and combined them into a single dataframe prior to loading might make things simpler to implement and allow us to continue to accept either format.

### Comment

Incorporating a script or feature that accepts the combined table is an option, but seems more trouble than it's worth since going forward we suspect all data to come as separated tables.

-----

## ISSUE OWNER SECTION

- Based on a brief Zoom chat with Lance, it was decided to try the **_alternative_** solution at first pass.  Will write a script (or edit `load_samples`) to handle 2 file inputs as named arguments, join them on `Animal ID` key and pass it along to existing code.

### Assumptions

- Code will assume files are formatted as defined in the [TraceBase Animal and Sample table templates](https://docs.google.com/spreadsheets/d/1To3495KxJkAtnAD9KVdzc162zKbNiYuPEVyPseQPjMQ/edit?usp=sharing)) 
- Code will assume input is correct (no additional validation)

### Requirements

none

### Limitations

- For this iteration, we will use the _existing_ `SampleTableLoader` class, rather than write new `SampleLoader` and _AnimalLoader_ classes 

### Affected/Changed Components

- `load_samples` command, or similar parallel

#### GUI Change description

API for loadsample will change or a new command will be made available.

#### Code Change Description *(Pseudocode optional)*

write or edit command that joins 2 files into a data-structure that SampleTableLoader can consume

#### Tests

Existing tests should suffice.

**Comment by jcmatese** [comment]
@lparsons did you actually want to blow away the old script, SampleTableLoader class, yaml, tests example file, etc. or do you just want to add a new script(s), class(es), and example files to load sample and animals independently?

**Comment by lparsons** [comment]
As we discussed, I can see multiple paths, each with pros and cons, but I hadn't thought through it enough to come to a conclusion. Happy to discuss ideas with you if you like.
