### ISSUE TITLE
Ability to show/hide search result columns

### ISSUE THREAD

**Issue by hepcat72** [Princeton-LSI-ResearchComputing/tracebase#158]
### Feature Inspiration

Feedback from Michael during the meeting on 7/28/2021, which was documented in [his notes](https://docs.google.com/document/d/1HCdqFgIDjGeaA8p1M8ElZhWuwxuczVvfwdydhuhLPUo/edit).

### Feature Description

Click a column header 'x' to hide it and add the column header to a list of hidden clickable buttons to re-add them.  In fact, some columns could be pre-hidden.

### Alternatives Considered

Ability to reorder columns.  Or include a static list of checkboxes for optional columns to "add" or "remove", where certain columns are not allowed to be removed.  These could appear in a pane on the right side, or that can pop out from the side.

### Comment

The number of columns makes the table quite wide.  Different users may be interested in certain columns.  Perhaps if the column was included in the search - should it have a hidden default or be unhidable?

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by lparsons** [comment]
I believe this is covered by #217, should we close this one?
