### ISSUE TITLE
Data submission ability (in lieu of direct import)

### ISSUE THREAD

**Issue by hepcat72** [Princeton-LSI-ResearchComputing/tracebase#161]
### Feature Inspiration

Feedback from Michael during the meeting on 7/28/2021, which was documented in [his notes](https://docs.google.com/document/d/1HCdqFgIDjGeaA8p1M8ElZhWuwxuczVvfwdydhuhLPUo/edit).

### Feature Description

Have a form to submit data for loading.  The page would/could:

- include a select list for format
- link to a format description
- first-pass validate data to fix simple issues
- save the submitted data file and notify curators to inspect & load
- have a text field to include a message to the curators
- provide contact info for the curator list for followup
- have the submitter enter their contact info
- send an email back to the submitter confirming receipt of the submission
- Provide a link to the submitter to a load status page, like a package tracker
- have the load script email or schedule an email notifying the user of successful load or failure status

### Alternatives Considered

Allow user to load data that is sandboxed in their own gated portion of the database for immediate use and have full incorporation for other users once curators approve it.

Allow direct-loading of machine-generated data (i.e. a more raw format).

### Comment

The concern with user-upload is the potential for the data to get messy/erroneous.  If there was a way to exhaustively validate, that could allow direct upload.  Tracking data prevenance would also help.

-----

### Assumptions

- Database administrators will curate data before loading

### Requirements

- [x] include a select list for format (implemented as 2 google form sections)
- [x] link to a format description (template provided for animal/sample and accucor format specified in section 2)
- [x] first-pass validate data to fix simple issues
- [x] save the submitted data file (saved in google drive)
- [x] notify curators to inspect & load
- [x] have a text field to include a message to the curators
- [x] provide contact info for the curator list for followup (PU email provided via login)
- [x] have the submitter enter their contact info
- [x] send an email back to the submitter confirming receipt of the submission
- **X** [cannot efficiently figure out how to add a status widget to the spreadsheet for tracking - or how to retrieve that status in tracebase, so I'm skipping this] Provide a link to the submitter to a load status page, like a package tracker
- **X** [Leaving this as a "nice-to-have" feature to implement later] have the load script email or schedule an email notifying the user of successful load or failure status
- [x] Documentation of the data submission & load process
- [x] Add a link in tracebase to the submission form

### Limitations

- Only minimal data validation will take place automatically, the remainder will be done via the import scripts or via manual inspection

### Affected/Changed Components

- Templates will include a link to the submission form

#### GUI Change description

* Link to the submission form.
* Google Form to submit new data for import

#### Code Change Description *(Pseudocode optional)*

1. Create or Edit this Google Form for animal/sample table and accucor file upload - https://docs.google.com/forms/d/1Y2SEQgLTd8QUjbXGCuo3989WQxMfsfh4AbJyeL3f6c8/edit?urlBuilderDomain=princeton.edu
2. Add this link to fill out the form to the Tracebase interface: https://forms.gle/Jyp94aiGmhBNLZh6A where appropriate
3. See if there's an automation that can be added to google docs that can run a validation on the files
4. See if there's a way to automatically email the submitter upon successful run of the load script(s) or a way for a curator to mark the submission in the [form](https://docs.google.com/spreadsheets/d/1IwixoN2ltNfyxiuYerPiYXz8jp9WKCSWHZ5-t49A6ZE/edit?resourcekey#gid=521196006) as successful or had errors
5. Possibly create a load status page and link it in Tracebase if loads are pending
6. Document the form submission process

**Comment by lparsons** [comment]
This should include instructions about data submission requirements and suggestions (as a Google Doc we link to) as well as a Google Form we link to.

Some notes regarding Animal and Sample naming. These should be fleshed out in the Google doc, then discussed and reviewed by the team.

Requirements:
* Animal and Sample names must be unique across a study (defined as a set of animals)

Suggestions:
* Animal names should be short strings that clearly identify an animal within the context of an experiment
* Sample names should be a combination of animal name, tissue, and date collected

**Comment by hepcat72** [comment]
Hey @lparsons, @fkang-pu, & @jcmatese - in order for you to get email notifications for data submissions from the form Lance created, you must go to the responses tab, click the vertical "..." and check "Get email notifications for new responses", as shown in the top gif on this page:

https://mailrecipe.com/mailrecipe/get-email-notifications-for-new-responses-in-google-forms.html

Whoever intends to load the submitted files should probably enable this.

**Comment by lparsons** [comment]
Thanks Rob, that information will need to be included in the documentation of the process for submission and processing.
