### ISSUE TITLE
Last serum sample returned might have `null` `time_collected`

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#188]
The `latest` method can return `null` values, since it's simply returning the last record based on database ordering of the field. We should explictly define how to handle `null` serum samples.

_Originally posted by @hepcat72 in https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/186#discussion_r705737968_

**Comment by hepcat72** [comment]
I think that `latest` shouyld actually be changed to an aggregate max function...  See my comment here:

https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/186#discussion_r706206130

**Comment by hepcat72** [comment]
Fixed by #507
