### ISSUE TITLE
Repo settings

### ISSUE THREAD

**Issue by hepcat72** [Princeton-LSI-ResearchComputing/tracebase#2]
I checked and I do not have access to the repo settings in order to tweak the ability to add more than 1 reviewer to PRs.

> Huh, apparently I can only request up to one reviewer.  If I select John, it deselects Lance.  We should fix that.  Let me see if I can do it...

_Originally posted by @hepcat72 in https://github.com/Princeton-LSI-ResearchComputing/tracebase/issues/1#issuecomment-781520914_

**Comment by lparsons** [comment]
Made it public, now allows up to 15 reviewers.
