### ISSUE TITLE
Peakgroups for two compounds are not getting associated with two compounds

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#208]
Took a look at this issue. For peak group like "citrate/isocitrate", I expected both citrate and isocitrate would return with many-to-many relationships. However, it seemed only the latter returned from database retrieval.  my test using Django shell:
```
In [1]: from DataRepo.models import *

In [2]: pg1 = PeakGroup.objects.get(id=18)

In [3]: pg1.name
Out[3]: 'citrate/isocitrate'

In [4]: pg1.formula
Out[4]: 'C6H8O7'

In [5]:  pg1.compounds.all()
Out[5]: <QuerySet [<Compound: isocitrate>]>

In [6]:  pg1.compounds.all().count()
Out[6]: 1

In [7]:  pg1.compounds.all()[0]
Out[7]: <Compound: isocitrate>

In [8]:  pg1.compounds.all()[0].id
Out[8]: 24

In [9]:  pg1.compounds.all()[0].name
Out[9]: 'isocitrate'
```

_Originally posted by @fkang-pu in https://github.com/Princeton-LSI-ResearchComputing/tracebase/issues/150#issuecomment-919197130_

**Comment by jcmatese** [comment]
https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/43a9552a7e211daa5ca2f6cc2726a66579f8ecc7/DataRepo/utils.py#L676-L698
