### ISSUE TITLE
Create PeakGroup and PeakData objects

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#21]
Create ObservedCompound and PeakData objects

Both tables objects will need functions to lookup/compute values including. These functions will be added as part of separate issue, but are noted below for context.

![image](https://user-images.githubusercontent.com/645128/114769901-cbed7b80-9d38-11eb-878b-796f920f2cbc.png)

```bash
PeakGroup
-
id PK int
name string                        # Compound or isomer group name
formula string INDEX               # Molecular formula
ms_run_id int FK >- MSRun.id
compound_id int FK >-< Compound.id # Many-to-many
# Additional computed values
# total_abundance
# enrichment_fraction
# enrichment_abundance
# normalized_labeling

PeakData
-
id PK int
peak_group_id int FK >- PeakGroup.id
labeled_element string
labeled_count int
# Composite Key -> observed_compound_id, labeled_atom, and labeled_count
raw_abundance float
corrected_abundance float  # also called total_ion_count
med_mz float
med_rt float
# Additional computed values
# serum_infusate_abundance
# fraction (also called normalized abundance)
```

**Comment by hepcat72** [comment]
Didn't Michael say some analog of `presumed` compound would be more accurate?  The observation is not really of the compound.

**Comment by jcmatese** [comment]
@lparsons I see that labeled_element and labeled_count are very similar to animal.tracer_labeled_atom and animal.tracer_labeled_count .  Should I make an abstract base class for "TracerLabeledThings" for for shared thing like `MAX_LABELED_COUNT` or `TRACER_LABELED_ELEMENT_CHOICES`?  Just wondering...

**Comment by lparsons** [comment]
> @lparsons I see that measurement.labeled_element and measurement.labeled_count are very similar to animal.tracer_labeled_atom and animal.tracer_labeled_count . Should I make an abstract base class for "TracerLabeledThings" for for shared data like `MAX_LABELED_COUNT` or `TRACER_LABELED_ELEMENT_CHOICES`? Just wondering...

It makes sense to avoid duplication for sure. I'm not certain of the best way to do that off the top of my head, but you're welcome to take a stab at it if you like. I'm also happy leaving this as a future enhancement. A couple of thoughts:

* The elements that would be labeled (_i.e._ `TRACER_LABELED_ELEMENT_CHOICES`) would certainly come from the same list, it might be good to create a class for that.
* The `MAX_LABELED_COUNT`, however, should be dynamically controlled for each compound, and be the number of those elements present in the formula. That should probably be a method in the `Compound` class.

**Comment by jcmatese** [comment]
will change `peakgroup.label` to `peakgroup.name`
