### ISSUE TITLE
Update load_compounds command to incorporate synonyms

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#225]
### Feature Inspiration

Various compounds may have synonyms we will encounter new synonyms for existing compound records.

### Feature Description

Have `load_compounds` accept an additional column that contains a synonym record which will be associated with compound records indicated by the name and HMDB id on that line

### Alternatives Considered

A separate command to load synonyms is an option, but it seems that would complicate the interface (another command) without providing much benefit (that I can think of right now).

### Comment

-----

### Assumptions

- 1 row per compound
- synonyms delimited by semi-colon (by default), or override synonym_delimiter by new argument
- new [example data file](https://docs.google.com/spreadsheets/d/1FoEF-ssxO8g-OjXB9PSIqkBH1QO1Jaw7mcvPP8PHzNU/edit?usp=sharing)
- NOTE: this new file changes the previous compound names of `C16:0` to `palmitic acid` , `C18:1` to `oleic acid`, `C18:2`, to `linoleic acid`.  These new names also differ from the `*ate` style of other compounds, if that is important.
-NOTE: the new file also has (probably) new compounds `dihydroxy-acetone-phosphate` , `fumarate`, `glucose-6-phosphate` , `glycerol-3-phosphate` , `stearic acid` (`C18:0`) and `taurine` 

### Requirements

- Compounds (as indicated by the name) that don't exist should be added
- Existing compounds should have synonyms added (unless the synonym is already associated with that compound)
- Synonyms in the file that already exist, but as associated with a different compound should throw an error

### Limitations

- 

### Affected/Changed Components

- `DataRepo/load_compounds.py`
- `DataRepo/utils.py`

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by jcmatese** [comment]
@lparsons @hepcat72 @fkang-pu  Looking at the new file (see notes above), it did appear that ~6 compounds are probably new to the database .  However there are 3 rows that match existing compounds (`C16:0` == `palmitic acid` , `C18:1` == `oleic acid`, `C18:2` == `linoleic acid`, ordered as  `previous_name` == `new_name`)  

As an implementation detail, would you prefer:
1. don't touch the existing compound record (name), but just add the list of all names as compound_synonyms
2. update the compound.name to presumably the newly preferred designation in the latest file, and also add the list of all names as compound_synonyms

**Comment by hepcat72** [comment]
I say first past the post is the winner, so: 1.  We can tackle changes if they're requested.

**Comment by lparsons** [comment]
My preference would be to throw an exception on rows that attempt to "change the primary name". Otherwise, option 1 is OK.

**Comment by jcmatese** [comment]
OK, maybe if we meet with Michael tomorrow, we can discuss.  Fan mentioned (in office discussions) kicking the file back to the lab for clarifications (presumably the same result with the "throw an exception" route).  However, to my mind, at some point if your are taking researcher's files as source material, you may eventually have to update the previous records with the "new preferred names" [i.e. Michael may reply with "yes, I meant it when I want wrote linoleic acid instead of C18:2 as the preferred name"; followed in 6 months by "how about linoleate, instead"]

**Comment by fkang-pu** [comment]
yes, for mapping synonym(s) to compound name, I prefer to generate a list during loading validation process and ask the lab for clarification.  I use the following example to share how I wish it would be handled:

assume a case with "glucose"
in TraceBase:
```
compound.name=glucose,  HMDB_ID=HMDB0000122
synnonyms=Glucose, GLUCOSE
```

then `peakgroup="D-Glucose" `in loading file which has no match with any compound name or synonym. The question is how to handle it during loading?

I would prefer:

1) raise exception during loading validation and suggest compound/synonym mapping and kick back to the user for verification:

`suggestion: D-Glucose => compound.name=glucose,  HMDB_ID=HMDB0000122`

2) how to record detected peakgroup in TraceBase for this case?
I would like to add a new column named pg_name_in_file (or call it user_preferred_name, pg_display_name, or a better name)
`after loading, the record in TraceBase: peakgroup.name="glucose", peakgroup.pg_name_in_file="D-Glucose". `

In this way, we would have consistent name for peakgroup.name without losing user selected synonym for a detected peak.

p.s. I hope we can work with the lab to compile and curate a long list of compounds with synonyms, so missing compounds/synonyms would not occur frequently during loading.  We should also remind the lab to choose which synonym as compound.name carefully and try not to change unless they have to.
