### ISSUE TITLE
Create an initial list of compounds with HMDB ids to simplify data loading

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#228]
### Feature Inspiration

Going through some effort to collect a list of compounds and associated HMDB IDs will make loading future AccuCor datasets simpler.

### Feature Description

Create a compound list that has been curated and verified by lab researchers. The list can be stored on the dev server for now and loaded as part of initial setup (see internal wiki for notes).

### Comment

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by jcmatese** [comment]
I assume this was actually resolved when @lparsons put together the [consolidated list](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/DataRepo/example_data/consolidated_tracebase_compound_list.tsv), which was added in PR #249 ?

**Comment by lparsons** [comment]
Fixed in #249
