### ISSUE TITLE
Document the load_study

### ISSUE THREAD

**Issue by hepcat72** [Princeton-LSI-ResearchComputing/tracebase#238]
### Feature Inspiration

Tried to load data to have results from an advanced fcirc search to view and had trouble interpreting what I needed to load.  I was loading individual sample, animal, compounds, and accucor files and wasn't getting any fcirc results and it wasn't clear to me why.  Running load_study and guessing that `study_params` corresponded to `loading.yaml` loaded data that included enough to see fcirc search results.

### Feature Description

I'm not sure what would make things more intuitive for someone less familiar with the interface, but I think that updating the CONTRIBUTING doc to show an example for every type of load would be helpful.  Probably a reorganization of the example data directory and/or changing the usage output for the param from `study_params` to something like `study_params.yaml` or `study_yaml_file` could help.  But I'm uncertain why the individual file loads did not result in fcirc calculations, particularly after having loaded serum samples, so there may be an improvement that could explain why loading (for example) every individual file in the `obob_example` real data directory didn't result in viewable fcirc data...

### Alternatives Considered

none

### Comment

The commands I ran that resulted in no viewable fcirc data were:

```
python manage.py load_compounds REALDATA/compounds/compounds.tsv 

python manage.py load_animals_and_samples --animal-and-sample-table-filename REALDATA/obob_example/animals_samples_treatments.xlsx --table-headers REALDATA/obob_example/headers.yaml 

python manage.py load_accucor_msruns --accucor-file REALDATA/obob_example/obob_maven_6eaas_inf.xlsx --protocol dummy --date 2021-11-03 --researcher "Robert Leach"
python manage.py load_accucor_msruns --accucor-file REALDATA/obob_example/obob_maven_6eaas_inf.xlsx --protocol dummy --date 2021-11-03 --researcher "Michael Neinast"
python manage.py load_accucor_msruns --accucor-file REALDATA/obob_example/obob_maven_6eaas_serum.xlsx --protocol dummy --date 2021-11-03 --researcher "Michael Neinast"
python manage.py load_accucor_msruns --accucor-file REALDATA/obob_example/obob_maven_c160_inf.xlsx  --protocol dummy --date 2021-11-03 --researcher "Michael Neinast"
python manage.py load_accucor_msruns --accucor-file REALDATA/obob_example/obob_maven_c160_serum.xlsx  --protocol dummy --date 2021-11-03 --researcher "Michael Neinast"

python manage.py load_samples REALDATA/obob_example/obob_sample_table.tsv --sample-table-headers REALDATA/obob_example/headers.yaml 
```

But running this, did flesh out what's needed for fcirc results:

```
python manage.py load_study REALDATA/serine-glycine-free-glucose-infusion/loading.yaml 
```

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by lparsons** [comment]
Reorganizing example data, breaking the files into discrete directories and providing a `load_study` YAML config file would be a good solution to this. Related to #172.

**Comment by hepcat72** [comment]
This issue is moot now, with the load refactor.
