### ISSUE TITLE
Potential for primary synonym deletion

### ISSUE THREAD

**Issue by jcmatese** [Princeton-LSI-ResearchComputing/tracebase#242]
"There is possibility of the "primary synonym" record being deleted right now and no validation or anything would catch that."

_Originally posted by @lparsons in https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/239#pullrequestreview-801665856_

It is still possible that someone could delete a synonym that is "protected" for the compound (matching name), but my initial attempts to ward this off by overriding CompoundSynonym

```
def delete(self):
    if self.compound.name == self.name:
        raise ValidationError(
            f"{self.name} is the protected synonym for {self.compound.name}."
        )

```
OR playing around with Django signals

```
from django.db.models.signals import pre_delete
from django.dispatch import receiver

@receiver(pre_delete, sender=CompoundSynonym)
def pre_delete_primary_synonym_active_compound(sender, instance, **kwargs):
    traceback.print_tb(sys.exc_info()[2])
    if instance.compound.name == instance.name:
        raise ValidationError(
            f"{instance.name} is the protected synonym for {instance.compound.name}."
        )
```

just prevent deletion of a Compound altogether.  Is that a good thing (perhaps)?

**Comment by hepcat72** [comment]
This is legacy code.
