### ISSUE TITLE
Refactor the `QuerySetToPandasDataFrames` class

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#246]
@lparsons I will keep your comments and go through them again when making modifications. Just answer your questions in general:
The questions you asked I also debated with myself several times. We should have further discussions about the following issues, though they are not top priorities for beta release. 

- It's fine to move data frames to a separate module, but it's not my preferred choice to move them into 
Models since some of them are shared among Models (e.g. all_anim_msrun_df contains combined data from Study, 
Animal, Tissue, Sample, and MSRun, called by several views). I also feel it's better to break models.py, views.py, utils.py into several files in sub-folders in the future.

- I like to have get_absolute_url() for every model. I raised this question a few months ago, but seems we decided not to do it, use {% url 'object_detail' pk %} instead. We can discuss it again.

- About field names in DataFrames:  to use values_list() (or values() function ) in a queryset to get related data from other models, the fields names are formed based on query path, some of which have long names with multiple double underscores. It's easy to rename columns with Pandas, I tried to make them short, easy to read, and consistent for columns in different DataFrames. Basically, I  attempted to do data manipulation with Pandas DataFrames, and then use them with minimum work when rendering data in templates.

- my to-do list:

1) remove debug code
2) add test for tissue list and detail. 
3) modify test code for other views (study, animal, sample)  
Hopefully I'll find time to do it Friday afternoon (or early next week).

_Originally posted by @fkang-pu in https://github.com/Princeton-LSI-ResearchComputing/tracebase/issues/241#issuecomment-964590981_

**Comment by lparsons** [comment]
A couple of other areas to note:
* https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/264#discussion_r754563547
* https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/264#discussion_r754566139

**Comment by hepcat72** [comment]
I think this is done.
