### ISSUE TITLE
Create `load_study` configuration for lactate timecourse data

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#251]
Run through the process of validation, submission, and loading of the data for the lactate timecourse study data.

* [x] Test the validation and submission process by following the instructions on TraceBase for submission of new study data, including validation and form submission.
* [x] Prepare the data for loading into TraceBase by attempting to load into a local development instance and fix problems. Any changes/fixes to the data files necessary to get the study loaded should be recorded in a `CHANGES.md` file. In some cases, this may require getting additional information from the researcher or even having the researcher update the files. The `CHANGES.md` file will eventually be communicated back to the submitting researcher and should be stored along with the studies files on the tracebase-dev server.
* [x] Create a YAML configuration file that can be used by [`load_study`](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/DataRepo/management/commands/load_study.py) Example: [`small_obob_study_params.yaml`](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/DataRepo/example_data/small_dataset/small_obob_study_params.yaml)
* [x] The configuration file and the required [lactate timecourse data files](https://drive.google.com/drive/folders/1v7QwchR1xXjdhgkgrvIGexhdG9LD8y6E?usp=sharing) should be placed on the tracebase-dev server according to the [admin docs for loading studies](https://nplcadmindocs.princeton.edu/index.php/TraceBase#Loading_Studies).
* [x] Load the study data into tracebase-dev

**Comment by jcmatese** [comment]
Just some validation notes, which might rise to be an "issue".  I was able to load the 2 accucor files using configured yaml.

- For the validate web template, it would be nice to validate more than 1 Accucor file (i.e. 1 sample/animal file to 1/many Accucor files),  In this case, I have 2 (exp024c_plasma_combined_bookmarked_corrected, exp024f_plasma_negative_corrected)
- exp024f_plasma_negative_corrected.xlsx FAILED validation , with the bulleted line "exp024f_inf" , which I _assume_ was a sample name in the data file, but missing from the sample/animal file. ]no explicit message; I am just guessing[  That was only 1 of the samples I flagged as skipped in the config.yaml, though.
- similarly, "exp024c_INF_317" also FAILED validating exp024c_plasma_combined_bookmarked_corrected.xlsx   (no explicit reason)

**Comment by jcmatese** [comment]
I did not really have to change too much.  I reformatted the provided sample table to the new xlsx template.  I renamed the `serum` tissue to the artery-specific version.  I did not make a CHANGES file, but could if deemed warranted, or if [Michael gets back on treatment descriptions](https://tracebase.slack.com/archives/C01M97YLQE5/p1637695312046400).

**Comment by jcmatese** [comment]
Loaded fine into my sandbox with the following 2 commands.
`python manage.py load_study datasets/michael_neinast_lactate_timecourse/study_params_positive_mode.yaml`
`python manage.py load_study datasets/michael_neinast_lactate_timecourse/study_params_negative_mode.yaml`

Data were staged to tracebase-dev:/var/www/tracebase/datasets/michael_neinast_lactate_timecourse/ , but not loaded there, yet.

**Comment by jcmatese** [comment]
Update: consolidated the 2 yaml file into 1, `loading.yaml` . so you should be able to execute pyth`on manage.py load_study datasets/michael_neinast_lactate_timecourse/loading.yaml`.  That file was copied to `tracebase-dev:/var/www/tracebase/datasets/michael_neinast_lactate_timecourse/`

**Comment by lparsons** [comment]
@jcmatese 👍🏻 The study loaded into tracebase-dev: http://tracebase-dev.princeton.edu/DataRepo/studies/4/. Please check to ensure things loaded correct, esp wrt the protocol.

**Comment by jcmatese** [comment]
Well, a [negative msrun](http://tracebase-dev.princeton.edu/DataRepo/msruns/310/) contains peak_groups from the [negative peak_group_set](http://tracebase-dev.princeton.edu/DataRepo/peakgroups/?msrun_id=310), so I believe it is ok?

**Comment by lparsons** [comment]
> Well, a [negative msrun](http://tracebase-dev.princeton.edu/DataRepo/msruns/310/) contains peak_groups from the [negative peak_group_set](http://tracebase-dev.princeton.edu/DataRepo/peakgroups/?msrun_id=310), so I believe it is ok?

What do we need to do to confirm the data loaded properly? Should we ash Michael to review it? Can we point him to specific things that were changed, etc. so he has some things to check for?

**Comment by jcmatese** [comment]
The only thing that was changed was replacing "serum" with "serum_plasma_artery", and the researcher-approved "skipped_samples".  Michael reviewing it would be fine.  I am unaware of a Tracebase export protocol that would be directly comparable to the imported data files (beyond spot-checks and row counts).  The 2 msrun protocols are there, the 2 sample protocols are there, the 2 peak_group_sets are there, 1 study, etc.  Beyond that, you get into the nitty-gritty that I hope the test suite might cover?
