### ISSUE TITLE
Possible syntax error in manage.py?

### ISSUE THREAD

**Issue by jcmatese** [Princeton-LSI-ResearchComputing/tracebase#26]
For me, I get this

```
/usr/bin/python manage.py migrate
  File "manage.py", line 17
    ) from exc
         ^
SyntaxError: invalid syntax

```
https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/bcdfe79682b704e322a095521c8025dd4f3751e6/manage.py#L7-L18

**Comment by jcmatese** [comment]
May be something wrong with my virtual environment?

**Comment by jcmatese** [comment]
I re-ran (?) 

```
usr/local/bin/python3 -m venv .venv
source .venv/bin/activate
```

And things are behaving again.  Uncertain whether I have to do that after every pull, or if there is something else going on...

**Comment by hepcat72** [comment]
My guess is the pythong version.  What do you get (when your environment is active) when you run `python --version` or `python3 --version`?

In fact, my environment has `python` linked to a 3 version.  Yours might be 2, which would mean you have to use `python3` explicitly.

**Comment by hepcat72** [comment]
You should not have to do this after pulling.
