### ISSUE TITLE
List of Studies does not show all studies

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#262]
### Problem

If a study is missing data in some linking tables, it is not returned as part of the list.

### Steps to reproduce

1. Load animal and sample records for a new study, but no accucor data.
2. View the List of Studies page

```
python manage.py load_animals_and_samples --animal-and-sample-table-filename animals_samples_treatments.xlsx
```
[animals_samples_treatments.xlsx](https://github.com/Princeton-LSI-ResearchComputing/tracebase/files/7567499/animals_samples_treatments.xlsx)

### Current behavior

The new study (fluxomics 2020) will not be displayed in the list of studies.

### Expected behavior

The fluxomics 2020 study should be display, but without any Genotypes or Tracers listed.

### Suggested Change

A guess at what might fix the issue.  *Pseudocode encouraged.*

### Comment

Any other relevant context or links to what you were working on when you
discovered the problem.

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will not fix
- E.g. Getting edge case X to work requires too much effort and will not be
  fixed in this effort.

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the fix.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by fkang-pu** [comment]
I reproduced the issue with a small test case, will modify my code for DataFrames to fix it in my next PR.
