### ISSUE TITLE
Show/hide of FCirc "Previous" rows does not work

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#266]
### Problem

Checking/unchecking the box to show/hide the "Previous" rows on the FCirc page has no effect.

### Steps to reproduce

1. View the FCric page for a study - *e.g.* [FCirc for Serine synthesis from glucose in control vs ser/gly-free diet](http://tracebase-dev.princeton.edu/DataRepo/search_basic/Study/id/exact/2/fcirc/)
2. Uncheck the "Previous" checkbox for "Serum Sample Row(s)" at the top

### Current behavior

No change in the rows displayed in the table.

Test with:
* Chrome - Linux
* Firefox - Linux

![image](https://user-images.githubusercontent.com/645128/143071318-ce29720d-6ae6-49c1-b3e9-8c4690f720a1.png)
![image](https://user-images.githubusercontent.com/645128/143071421-d861c3cb-edcc-4c78-b68a-5cecb2e1e995.png)

### Expected behavior

Rows for earlier timepoints (not the final serum samples) should be hidden when "Previous" is unchecked.

### Suggested Change

A guess at what might fix the issue.  *Pseudocode encouraged.*

### Comment

Any other relevant context or links to what you were working on when you
discovered the problem.

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will not fix
- E.g. Getting edge case X to work requires too much effort and will not be
  fixed in this effort.

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the fix.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by hepcat72** [comment]
Could you post the screenshots? It works for me. Do you get any errors in the console?

**Comment by hepcat72** [comment]
Or at least, it worked when I tested it during the PR. Haven't tested it today, obviously. (Vacation)

**Comment by hepcat72** [comment]
Ah. I see the issue.  Trivial fix.  Not sure how I managed to break that.  Probably a copy/paste-o when streamlining followed by not double-checking.
