### ISSUE TITLE
Additional columns in FCirc search results table

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#270]
### Feature Inspiration

When plotting FCirc values, researchers often want to group records by Animal metadata such as Feeding Status.

### Feature Description

Include additional Animal level metadata in the FCirc results table.

| Column | Initial display |
| --- | --- |
| Animal | Show |
| Studies | Show |
| Genotype | Show |
| Body Weight (g) | Hide |
| Age (weeks) | Hide |
| Sex | Hide |
| Diet | Hide |
| Feeding Status | Show |
| Treatment | Show |
| Tracer | Show |
| Labeled Element | Hide |
| Infusion Rate (ul/min/g) | Show |
| Infusion Concentration (mM) | Show |
| Time Collected (min) | Show | 

All columns should be included in downloaded tables.

### Alternatives Considered

A brief description of any alternative features that may accomplish the same
ultimate goal.

### Comment

-----

### Assumptions

- I'm inferring the feature description describes 2 features: add columns to the fcirc format and set initial visibility of th columns (same for every user).

### Requirements

- Add listed columns in the feature description table to the fcir html & tsv temapltes
- Set the initial column visibility of the fcirc template as shown in the feature description table

### Limitations

- No user-specified initial column visibility settings

### Affected/Changed Components

- fcirc.html
- fcirc.tsv
- compositeviews.py

#### GUI Change description

New columns in the fcirc data and some columns will start out as hidden.  All added columns will appear in the fld select list(s).

#### Code Change Description *(Pseudocode optional)*

- Add fields to the compositeviews.py fcirc format.
- Add columns for both fcirc templates.
- Use the bootstrap-table javascript doc to figure out how to set initial columnSwitch values

#### Tests

none

**Comment by hepcat72** [comment]
Just had a separate thought while working on this... Is the time collected of the serum sample relevant at all, because the time collected that's displayed, I believe, is that of whatever tissue sample on the row... If this doesn't make sense, then never mind.

**Comment by lparsons** [comment]
> Just had a separate thought while working on this... Is the time collected of the serum sample relevant at all, because the time collected that's displayed, I believe, is that of whatever tissue sample on the row... If this doesn't make sense, then never mind.

The rate of appearance (Ra) values are calculated for each serum sample. In order to interpret those values, the researcher should know the time collected as the value changes as the animal gets further out from the initial infusion. Eventually, the value should level off and approximate the true circulatory flux (FCirc). @jcmatese or @mneinast - please correct me if I'm wrong here.

**Comment by hepcat72** [comment]
While working on the show/hide defaults, I found a bootstrap-table issue with the toggle all control... I appears to toggle all but the first column (Animal), which the checkbox displays as still checked and grayed out... but the Animal column ends up hidden...

**Comment by hepcat72** [comment]
Looks like it's a bug WRT bootstrap-table.  I used their [editor interface](https://live.bootstrap-table.com/example/options/columns-toggle-all.html) and tested out a hunch. If you have any columns (other than the first column) with `data-switchable="false"`, every switchable will hide, but the first column's switch checkbox will remain checked and gray out.  Going to see if they have a repo to report the bug...

**Comment by hepcat72** [comment]
https://github.com/wenzhixin/bootstrap-table/issues/5991

**Comment by hepcat72** [comment]
> > Just had a separate thought while working on this... Is the time collected of the serum sample relevant at all, because the time collected that's displayed, I believe, is that of whatever tissue sample on the row... If this doesn't make sense, then never mind.
> 
> The rate of appearance (Ra) values are calculated for each serum sample. In order to interpret those values, the researcher should know the time collected as the value changes as the animal gets further out from the initial infusion. Eventually, the value should level off and approximate the true circulatory flux (FCirc). @jcmatese or @mneinast - please correct me if I'm wrong here.

You may disregard.  I couldn't remember the components of the calculation.  I knew that the serum sample time collected was important, but I vaguely/incorrectly had some notion of other samples being involved in one calculation.  I just refreshed my memory by looking at the code.
