### ISSUE TITLE
Links to PeakGroups / PeakData from Compound detail listing data where that compound was measured

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#277]
### Feature Inspiration

Researchers often want to see data on the measurement of a specific compound (see #276). 

### Feature Description

Links on the Compound detail page that return PeakGroup and PeakData records where the specified compound was measured. This will likely require #276 to properly implement, though various workarounds could be done if needed.

### Comment

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by hepcat72** [comment]
Since measured compound isn't currently a part of the peakdata format (and thus is not a searchable field for that format), this issue will also involve adding that to the peakdata format...

**Comment by hepcat72** [comment]
- [x] Add link to the Compound detail page to a PeakGroup advanced search where the specified compound was measured.
- [x] Add a link to the Compound detail page to a PeakData advanced search where the specified compound was measured.
- [x] Add Measured Compound to the PeakData advanced search format

**Comment by hepcat72** [comment]
- [ ] Add a button on the compound detail page to advanced search's peak data format, using the measured compound
- [ ] Add a button on the compound detail page to advanced search's peak groups format, using the measured compound
