### ISSUE TITLE
Pass linting with jscpd for home.html

### ISSUE THREAD

**Issue by fkang-pu** [Princeton-LSI-ResearchComputing/tracebase#279]
### Feature Inspiration

Need to improve the code for 8 cards added to home.html in order to pass linting with jscpd.

### Feature Description
Re-write the 8 blocks of code for cards for home.html.

### Comment

With code added to home.html to create 8 cards for browsing data in [PR 273](https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/273), this template file failed passing linting with jscpd. The workaround was to add home.html to .jscpd.json to skip the linting with jscpd.

-----

### Requirements

- New code should allow home.html to pass linting without changing any search/browse functions.

### Affected/Changed Components

- home.html

#### GUI Change description

No GUI change should be made for this issue. 

#### Tests

home.html should be removed from .jscpd.json and pass all tests and linting workflow.

**Comment by jcmatese** [comment]
I think you could probably just make a subtemplate 

`{% include "path/to/template/includes/card_div.html" %}  `

and loop though the cards
```
{% for card_meta in card_objs_metas %}
{% include "path/to/template/includes/card_div.html" %}
{% endfor %}
```

provided you had a list of dictionaries containing the header, url, and perhaps class/color.  I have no experience in this templating language, though.

**Comment by hepcat72** [comment]
[Yes, that's correct](https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/273#issuecomment-983979451)

**Comment by fkang-pu** [comment]
I thought about it, but the card title also include one or two variables (e.g. <div class="card-body"><h4>{{ compound }} Compounds( {{ tracer }} Tracers )</h4></div>) and card foot with a variable for url link (`href="{% url 'compound_list' %}"`).  I was not quick enough to come up with details code and test to add it to PR273.  So I added this issue to address it later.

**Comment by hepcat72** [comment]
All the variables can be created/passed to the included template. You can name them anything you want.

**Comment by fkang-pu** [comment]
I now have an idea on how to solve the issue. Need to re-write the part of code in views.py for rendering home page, and will submit a new PR later.
