### ISSUE TITLE
Remove commented code

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#285]
NB: Generally, it's best to remove commented code. We have git history if we need to get it back. https://kentcdodds.com/blog/please-dont-commit-commented-out-code

_Originally posted by @lparsons in https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/273#discussion_r763375149_

**Comment by hepcat72** [comment]
Appears to have been removed.
