### ISSUE TITLE
Reorganize PeakGroup advanced search result columns 

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#315]
### Feature Inspiration

The result tables should help the researcher focus on the most important and relevant details for the specific data they are viewing. Reducing the default columns displayed and grouping the columns will help to make the organization of the table more intuitive.

### Feature Description

By default, show the following columns, with darker lines separating the groups. The group names are for clarification in this issue, but don't need to be displayed on the actual page.

Row Identification - Details that identify what this row of data describes
* Sample
* Tissue
* Compound Name (not pg name)
* Labeled Element

Data - The data collected/calculated for this row
* Total Abundance
* Enrichment Fraction
* Enrichment Abundance
* Normalized Labeling

Metadata - most commonly used metadata for grouping, etc.
* Genotype
* Feeding Status
* Treatment
* Tracer
* Study

Additional columns should be included in the appropriate group, but not displayed by default.

### Alternatives Considered

None

### Comment

![image](https://user-images.githubusercontent.com/645128/147978615-96f1c2e6-2ff5-4252-8a6d-6c725cb01ad3.png)

-----

### Assumptions

none

### Requirements

Column details

```
Legend:

^ added column
* hidden column
- darker border

Column order:

*Animal
Sample
Tissue
*Peak Group
^Compound Name
*Measured Compound(s)
Labeled Element
*Peak Group Set Filename
-
Total Abundance
Enrichment Fraction
Enrichment Abundance
Normalized Labeling
-
*Formula
Genotype
*Sex
Feeding Status
*Diet
Treatment
*Body Weight (g)
*Age (weeks)
Tracer Compound
*Tracer Infusion Rate (ul/min/g)
*Tracer Infusion Concentration (mM)
Study
```

Add the added column to the download

### Limitations

none

### Affected/Changed Components

- `peakgroups.html`
- `peakgroups.tsv`

#### GUI Change description

Peak group column order, default hidden columns, and added compound name column.

#### Code Change Description *(Pseudocode optional)*

Simple template changes.  I will explore "border-collapse" for the dark border.

#### Tests

none - template code.

**Comment by hepcat72** [comment]
With hiding/showing columns, it's not clear to me yet how to do the darker lines between groups, but I'll think about it... Might be easier to alternate the background transparency of the column in the groups... though even then, what if the user hides an entire group...  We could use different colors, but then it would start to look ugly.  Anyway, I'll think about the borders.

**Comment by lparsons** [comment]
> With hiding/showing columns, it's not clear to me yet how to do the darker lines between groups, but I'll think about it... Might be easier to alternate the background transparency of the column in the groups... though even then, what if the user hides an entire group... We could use different colors, but then it would start to look ugly. Anyway, I'll think about the borders.

I think `border-collapse` on the table with `border` settings for each `colgroup` would work.

**Comment by hepcat72** [comment]
Is "Compound Name" supposed to be "Measured Compound(s)"?  Do you want me to change the column header?  And I will assume the downloaded file column order should match.

**Comment by hepcat72** [comment]
And I assume you still want to include the Peak Group column (including it [hidden by default] with the row identification group). I hadn't removed it with the original measure compound issue (as the issue had suggested) because otherwise, there's no link to the PG record.  Should all default-hidden associated columns be appended to those groups, or potentially interspersed?  E.g. I feel like it makes sense to make peak group and measured compounds adjacent...

**Comment by lparsons** [comment]
> Is "Compound Name" supposed to be "Measured Compound(s)"? Do you want me to change the column header? And I will assume the downloaded file column order should match.

Ideally, we would display the actual Compound.name field(s), (without the extra synonyms). The PeakGroup.name field can be hidden. I'm not sure what we are calling that now, but we can probably leave the heading as it is.

While it would be nice if the order of the downloaded file matched, I don't think it's particularly important right now. Keep in mind, all of this is subject to further changes.

**Comment by lparsons** [comment]
> And I assume you still want to include the Peak Group column (including it [hidden by default] with the row identification group). 

Yes.

> Should all default-hidden associated columns be appended to those groups, or potentially interspersed? E.g. I feel like it makes sense to make peak group and measured compounds adjacent...

Yes, "Additional columns should be included in the appropriate group, but not displayed by default."

**Comment by hepcat72** [comment]
> > Should all default-hidden associated columns be appended to those groups, or potentially interspersed? E.g. I feel like it makes sense to make peak group and measured compounds adjacent...
> 
> Yes, "Additional columns should be included in the appropriate group, but not displayed by default."

Sorry.  The question was unclear.  What I meant is, is this ordering implicitly expected:

Sample
Tissue
Measured Compound(s)
Labeled Element
[Peak Group] (hidden)

Or is this ordering OK:

Sample
Tissue
[Peak Group] (hidden)
Measured Compound(s)
Labeled Element

**Comment by lparsons** [comment]
Either is OK, whichever you think makes more sense.

**Comment by hepcat72** [comment]
> > Is "Compound Name" supposed to be "Measured Compound(s)"? Do you want me to change the column header? And I will assume the downloaded file column order should match.
> 
> Ideally, we would display the actual Compound.name field(s), (without the extra synonyms). The PeakGroup.name field can be hidden. I'm not sure what we are calling that now, but we can probably leave the heading as it is.
> 
> While it would be nice if the order of the downloaded file matched, I don't think it's particularly important right now. Keep in mind, all of this is subject to further changes.

OK. I will add a compound.name column and hide the synonyms column.  If a record can match a search (e.g. a synonym), I'd want the matching text to at least be able to be revealed in the table.

**Comment by hepcat72** [comment]
Alright. I finished the order and the default-hiding and dug into border-collapse.  If we want borders around the column groups, I believe we will need some custom javascript due to the column switching of bootstrap-table.  E.g. I can see borders if I set:

```
        <colgroup span="8" class="identdata"></colgroup>
        <colgroup span="4" class="datadata"></colgroup>
        <colgroup span="12" class="metadata"></colgroup>
```

...but they are static and only apply to the visible columns, so we see:

<img width="1615" alt="colgrps" src="https://user-images.githubusercontent.com/2300532/148139418-04e13b46-f577-47e0-8e6e-e24f65b8b1bc.png">

because I set 8 row-identification columns, but half of them start out hidden.  If I toggle all the columns to visible, the bold borders are correct.

So I would have to write some javascript to change the span values of those colgroup tags.

I have tried to figure out whether bootstrap-table has a buoltin way to do this, but so far, I have not figured out a simple solution...

**Comment by lparsons** [comment]
Perhaps we should skip the borders for now then. Split that out to another issue and get the updates columns in for PeakData and PeakGroup results.

**Comment by hepcat72** [comment]
Made a [feature request to bootstrap-table](https://github.com/wenzhixin/bootstrap-table/issues/6018).

**Comment by hepcat72** [comment]
Actually, I like this type of coding.  Already implemented it.  Couldn't resist.  Linting and testing... PR impending.
