### ISSUE TITLE
Update/Simplify data submission process

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#318]
### Feature Inspiration

The current process to submit data via a Google form is rather cumbersome.
* Users are not able to submit the Google Spreadsheet directly, but have to download as Excel and upload to the form
* The files end up in different directories for each questions
* Only 10 files can be submitted, more than that have to be zipped, etc.

### Feature Description

Perhaps a checklist of what what file(s) are needed along with a description of how to create a new "study" folder in a specific place on Google drive could work better. We would need to allow each lab member permission to the folder, but there aren't so many that should be a problem. The basic instructions could be in a Google Doc in that folder along with an example (the obob study perhaps) so people could see a completed example.

### Alternatives Considered

None considered, but other ideas welcome.

### Comment

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by hepcat72** [comment]
Maybe a google script can be employed to streamline the process. I've created one before to populate a weather tracking spreadsheet to warn me about the possibility of an ice dam forming on my roof in Buffalo (which was possible if the temperature was below freezing for 4 days in a row... Let me take a quick look at whether a google script could be used to simplify the submission...

**Comment by lparsons** [comment]
I like the idea of a script to customize things. Has the potential to be very powerful. Keep in mind:
1. This process is likely to change, possibly significantly, therefor it should be flexible and easy to change
2. Other developers should all be able to understand and modify things if need be
3. We should have some sort of workaround for edge cases (e.g. put files into a specific Google Drive folder, etc.)

**Comment by hepcat72** [comment]
I was refreshing my memory on google scripts (now called "Apps Scripts" (or "Google Apps Scripts")).  Luckily, I documented it in a [blog post](https://alwayswithyouwhatcannotbedone.wordpress.com/2016/12/).

The way my ice jam script worked was, I attached a script to the spreadsheet that would run whenever a row was added.  Previously, you accessed it from a google spreadsheet via the Tools->Script Editor menu.  Now it's under Extensions -> Apps Script.  And I had an IFTTT applet that added a row each day with tomorrow's high temperature.  The script would check whether the 4 most recent additions were under 33 degrees, and if so, it would email me an "ICE JAM WARNING".

It's pretty nifty, but thinking about this issue, I'm not clear on how a google script might be employed here...  Perhaps if the script could...

1. Prompt to select a number of google spreadsheets and/or excel files (allowing more than 10)
2. Save the submissions in a single directory
3. Maybe even run the validation code???

That's about all we'd need, right?

**Comment by hepcat72** [comment]
This will need some more thought.  I'm going to drop some relevant links and move on while I ruminate on it...

- https://stackoverflow.com/questions/50762183/how-can-i-create-a-google-scripts-prompt-that-accepts-multiple-inputs#_=_
- https://support.google.com/docs/thread/13371261/how-do-i-use-one-google-apps-script-file-to-be-used-for-multiple-different-google-sheets?hl=en

**Comment by lparsons** [comment]
Here is the proposed [TraceBase Study Submission Process](https://docs.google.com/document/d/1sno7-Dm88KSMIlK-hypxUW8nqL3nUzy70gFVemUlcIc/edit?usp=sharing) proposal so far, in Google Docs format to make commenting/editing simpler. Once it's ready, I'll make a PR to update the upload page on TraceBase.
