### ISSUE TITLE
Data Submission Leaderboard

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#319]
### Feature Inspiration

A "leaderboard" style display could help keep track of which lab members are participating in TraceBase and help to encourage people to submit data. 

### Feature Description

On the front page, some tables listing top submitters, organized by
* Number of Studies
* Number of Animals
* Number of PeakGroups

### Alternatives Considered

None

### Comment

Mockup of possible design
![tracebase-leaderboard-mockup](https://docs.google.com/drawings/d/e/2PACX-1vQkCVvCT-Cj0L-BFegHYXlGvGYMXqCSQOaeQ-n-0ZD2x2wCGyKSJg5wzRC0P5js7jQrvGqlTvyHyzZF/pub?w=960&h=720)

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by mneinast** [comment]
Based on conversations with lab members where I hint at this feature, it could be a very popular feature.  I'd say it's worth implementing if easy!
