### ISSUE TITLE
Advanced Search Pagination

### ISSUE THREAD

**Issue by hepcat72** [Princeton-LSI-ResearchComputing/tracebase#336]
### Feature Inspiration

Loading of Advanced search results on the tracebase-dev site is so slow since the data was fully populated, it results in timeout errors.

### Feature Description

As a stop-gap measure (short of fixing the cached property slowness issue), implement pagination in a way that speeds up the loading of the page.

I've been googling and experimenting with bootstrap-table pagination and there may be a way to specify a "[data provider](https://bootstrap-vue.org/docs/components/table#using-items-provider-functions)" method that effectively lazy-loads the data such that all of the bootstrap functionality works in the context of all the results (seen & unseen) - e.g. column sort will execute a new query and page navigation remembers which columns are visible/hidden.  You create a function that retrieves each page worth of data.

I experimented a bit with the possibility that simply setting `data-pagination="true"` may speed up the page, but it did not result in a speed increase.

### Alternatives Considered

Implement django's pagination, decorated by bootstrap.  The problem would be that sorting would only apply to the currently visible data and hiding columns would have to somehow be tracked by django and context variables.

### Comment

Still googling.

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by hepcat72** [comment]
Sheesh, I am realizing that this is a difficult thing to do without sacrificing features & fixes of the current implementation.

Bootstrap table needs to retrieve the data using as data provider function if you want to both get the speed increase of paginated results, hidden columns to be remembered, and sorting to be globally applied(?), but
- You have to format the fields using bootstrap methods/javascript, so all the templates would have to be rewritten and the custom tags would have to be rewritten
- The customizations to refilter duplicate records from many-to-many relationships (and correct the row counts, which might not even be possible) would have to be rewritten
- It doesn't look like the data provider functionality supports column sorting, though I need to look into that more

**Comment by jcmatese** [comment]
I can imagine it will be difficult.  Certainly, HTML tables of sorted strings can be useful (Studies, Animals, Samples, Tissues, etc.) but as soon as you move into the data realm (peak groups, peakdata) it _may_ be best to deprecate web-tables and focus on writing of downloadable/consumable files, instead?  [certainly the "browse all" links _might_ need to go away]

Is it possible to toggle the sorting based on the size of the data (if that is what the possible issue might be)?
   
For the microarray database, we handled data filtering/delivery differently, but if anyone wants a demo just to get ideas flowing, let me know.

**Comment by hepcat72** [comment]
Turns out there may exist an exceedingly [simpler solution](https://stackoverflow.com/questions/70674263/how-to-lazy-paginate-a-bootstrap-table-with-slow-data#comment124941560_70674263) I intend to look into today. I had originally thought of trying to get the cache to live longer (and only be rebuilt when data is added, but initially thought that pagination would be a simpler option... But if all you have to do is add a cache framework and fiddle with its settings, that would be the optimal solution...

**Comment by jcmatese** [comment]
If it is a `cached_property`-caused issue, we could also investigate just storing those in the model (and regenerate on demand), if the simple solution does not work out.

**Comment by hepcat72** [comment]
Looks like it's slightly more involved than my first impression.  I think that each cached_property method would have to roughly do something like this:
```
from django.core.cache import cache

...

output = cache.get(<primary key>)
if not output:
     result = ... do the cached_property code ...
    cache.set(<primary key>, result, ...)
```
Probably I could add something fancy to track whether new data has been added to prompt the cached value to be recomputed.  Could even set a flag to be monitored by a cron job to do it in a way that doesn't cause browser timeouts...

**Comment by hepcat72** [comment]
Then you can configure the way the cache is stored.  You can set up a database table, put it in memory, etc...  Not sure what the default behavior is (if any).

**Comment by hepcat72** [comment]
OK.  Just going to post some notes here.  I got pymemcached/memcached working on a branch.  The results are actually disappointing.  It's actually slower somehow, by 2 or 3 seconds using a 2600 row results table that completes in about 20 seconds from click to fully rendered.  I have a couple insights into the lag.  The cached properties call complete in about 7ish seconds.  I believe the remaining time is divided between transferring the data and rendering.

So there are a few categories where efforts could be applied to tweak the performance:
A. Compiling the data (7s)
B. Transmitting the data (13s - C)
C. Rendering the data (13s - B)

The strategies affect 1 or more of those individual bottlenecks:
1. A better cache implementation (there are a number of strategies)
   - could improve A
   - minimal effort, very simple refactoring and config
   - Can only (potentially) lessen the load time by a max of 1/3 (assuming linear scaling)
2. Limiting the data presented per page (pagination)
   - could improve A, B, & C
   - Major refactor, long development time, possibly dropping some difficult features
   - Could simplify the template and reduce template/tag code complexity
3. Using a data structure instead of an HTML template
   - could improve C
   - Large refactor (less effort than 2, but complex to deal with the refiltering issue) limited mostly to the template.
   - If C is the largest bottleneck, this could be just enough to put the full refactor off
   - Refiltering may need to be done server-side, so the only significant difference with 2 is that there would be no need for column sorting customizations.
   - Would not have to mess with any sort of custom column sorting code

To implement the [caching strategy](https://docs.djangoproject.com/en/dev/topics/cache/#basic-usage) I tried, I had to install a [caching service on the command line, which I did using brew](https://gist.github.com/tomysmile/ba6c0ba4488ea51e6423d492985a7953) and a python interface to it (`pip install pymemcache`, which I added to the requirements).

Strategy 3 *could* improve rendering speed by doing the decorations in javascript lazily (via bootstrap), as you can see in [this demo](https://live.bootstrap-table.com/example/welcome.html), which shows a loading graphic whenever you change pages.

I'm surprised that the memcached strategy was slower.  I may attempt a second strategy for due diligence before giving up on it.  I'm not savvy with how to setup the memcached service as a part of the distro...

**Comment by hepcat72** [comment]
This is weird.  I tried changing the caching strategy to a table in the database, but the same code that worked with memcached (which cached everything), weirdly caches some values but doesn't cache others (most).  I cannot see a pattern to it.  The doc suggested the database option *could* be faster, but with this random failure and only some things cached, it runs about the same as memcached.  Weirdly, if I try to cache values that failed to cache in the shell, they cache just fine...

For example, my debug output shows:
```
Returning cached PeakData.fraction.977?: False Value: <object object at 0x7fce062432d0>
Setting cache PeakData.fraction.977 to 0.0
```
Subsequent `gets` for cache key `PeakData.fraction.977` show the value is not getting cached.  This is a head scratcher.

I even started printing the result of a get immediately after a set.  Then I do it over again and the first get fails...

First page load...
```
Returning cached PeakData.fraction.217?: False Value: <object object at 0x7fb1c292f3f0>
Setting cache PeakData.fraction.217 to 0.0
CACHE SUCCESS FOR KEY/VALUE: PeakData.fraction.217/0.0
```
Second page load...
```
Returning cached PeakData.fraction.217?: False Value: <object object at 0x7fb1c1802f90>
Setting cache PeakData.fraction.217 to 0.0
CACHE SUCCESS FOR KEY/VALUE: PeakData.fraction.217/0.0
```
Other values are cached and received successfully, including `0.0`... So confusing.

**Comment by hepcat72** [comment]
I loaded all of the data that's on the dev site in my dev copy.

I managed to get to the initial load stage of the browse of the peak data view while building its cache (i.e. the unformatted table appears but the page is still loading). It cached 191552 values in just under an hour and a half.

The caching (and gathering) of the data took (very roughly) about 1h 45m.

Gathering the cached data took roughly 17 minutes.  Sending took roughly 4 minutes.  Rendering is 20m in and still going.

But from 1.5h down to just over 0.25m for retrieving cached data is a good improvement.  I can push out what I have, which should improve performance, though I'm not certain by how much in any given case.

I think I may break this effort down into:

1. This caching effort
2. Doing the re-filtering server-side
3. Trying to implement bootstrap-table's server-side pagination/sorting

Some references:
- https://stackoverflow.com/questions/30053645/bootstrap-table-server-side-pagination
- https://examples.bootstrap-table.com/index.html#options/server-side-pagination.html
- https://examples.bootstrap-table.com/index.html#options/server-sort.html

**Comment by hepcat72** [comment]
Wasn't supposed to have been closed... Must have been unintentionally automatic...

**Comment by hepcat72** [comment]
Regarding the breakdown of this effort delineated above as:

1. [x] This caching effort
2. [ ] Doing the re-filtering server-side
3. [ ] Trying to implement bootstrap-table's server-side pagination/sorting

I was thinking about step 2.  In order to be able to do the server-side pagination, we need predictable row numbers.  Currently, since we duplicate records to display linked studies on their own row (requiring re-filtering for them to make sense), I realized that the limit and offset values would be different on the page as they relate to rows than they would in the page numbers, so I think that we will *have* to change the "Study" column to a "Studies" column, and list the studies as either a comma-delimited list or some sort of rows associated with all other associated rows being merged using a rowspan.  Given those two options, I think a delimited list would be preferable, the same way the fcirc format presents them.  This will eliminate a hunk of javascript necessary to recompute the number of results.

**Comment by hepcat72** [comment]
Decided against doing the re-filtering, as it would be slow and complicate limit & offset values.  I removed the refilter code and simply grouped all studies for each root record in a single cell.  Future M:M relationships could reintroduce the complexity if we wanted to again simulate an outer-join, but that code is in the history, so we'll be able to retrieve it if necessary.

**Comment by hepcat72** [comment]
It looks like it's not possible to use a Django template that defines how to render each row.  You need to [define a URL](https://github.com/wenzhixin/bootstrap-table-examples/blob/master/json/data2.json) from which the data is obtained.  I'm going to take this step by step (column by column) and build up one of the templates using this strategy to see how all the renderings are done (e.g. linked values, tooltips, number formatting, horizontal alignment, etc...  It's a pretty drastic rewrite, but the only other option would be to use the onSort and onPageChange events to reload the page every time.  I really doubt it's intended to work that way.  Besides, doing it using the URL will result in a smoother user experience.

**Comment by hepcat72** [comment]
TODO:

- [ ] Turn off BST sorting
- [ ] Better encapsulation
   - [ ] Set BST classes/style for form elems using the paging class
   - [ ] Save class variables inside the paging class
   - [ ] Set separate pagination template
- [ ] Pass switched columns
- [ ] Pass sorting columns
- [ ] Re-enable sorting using the server
- [ ] Fix the rows select list button by creating a custom widget (I saved a link to a SO post about this, but can't find it ATM)
- [ ] Clean up multiforms.py

**Comment by hepcat72** [comment]
- [x] Enable server-side sorting
- [ ] Reorganize javascript to reduce redundancy
- [ ] Make toggle-all be remembered
- [ ] Update sorting controls after column switching
- [ ] Move the paging_form_valid and paging_form_invalid to pager.py
