### ISSUE TITLE
PeakGroup name cannot always be discerned from the PeakGroup detail page

### ISSUE THREAD

**Issue by hepcat72** [Princeton-LSI-ResearchComputing/tracebase#346]
### Problem

The PeakGroup name reported on the PeakGroup detail page is currently showing the Compound.name of the linked compound and PeakGroup.name is nowhere in the record... however the PeakGroup name can apparently differ from the Compound.name value.  This makes it impossible to accurately search for a `PeakGroup` using its name in the advanced search.

### Steps to reproduce

1. In the current tracebase-dev instance, go to http://tracebase-dev.princeton.edu/DataRepo/peakgroups/808/
2. Copy the PeakGroup's name ("3-hydroxybutyrate") and note that the sample is `xz944-t`
3. Got to advanced search and execute a search for `PeakGroup` `is` `3-hydroxybutyrate` user output format `PeakGroups`
4. Search the page for sample `xz944-t`

### Current behavior

Sample `xz944-t` is not among the results.  That's because PeakGroup 808's name is not `3-hydroxybutyrate`.  It's `(R)-3-Hydroxybutanoic acid`, but that name is not in the PeakGroup record on its details page.  This is because what is entered for the PeakGroup name can differ from the name of the linked compound.

### Expected behavior

Either we allow PeakGroup names to differ from the name of the linked compound and add the actual peakgroup name to the details page or we require that PeakGroup names match the compound name of the linked compound.

Personally, I think it should be the latter.  Searching for a peakgroup name seems to intuitively suggest that you would get all peakgroups for that compound, if not only that specific peakgroup.  We have a way to search for a measured compound, but to facilitate searching for a specific peak group, the detail record should show that peak group's name, especially when it differs from the compound name.

### Suggested Change

Add PeakGroup.name to the peakGroup details page.

### Comment

I'm working on how to handle expiry of cached values and I noticed something off WRT PeakGroup Detail records... I randomly selected some records to expire their cached values.  One of them was for PeakGroup 808. I wanted to perform a search for record 808, so I went to: http://127.0.0.1:8000/DataRepo/peakgroups/808/ to see the name of the PeakGroup to search on. I noted that the name listed in the record (3-hydroxybutyrate)  was linked to a compound record, but while I thought that wasn't necessarily the best thing to do, I was like, NBD. But when I did the search in advanced search for PeakGroup is 3-hydroxybutyrate, PeakGroup 808 was not among the cached value debug outputs, so I went to the DB and queried for that record. I discovered that the peak group name was not in fact, "3-hydroxybutyrate", but rather "(R)-3-Hydroxybutanoic acid".
That's a synonym, but I had thought that peakgroup names were supposed to be named using the Compound.name and not a (secondary?) synonym... I'm not sure I have fully characterized what's going on, but this is surely not right somewhere here. I should be able to get the recorded PeakGroup name from the PeakGroup record, but I cannot in this instance.

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will not fix
- E.g. Getting edge case X to work requires too much effort and will not be
  fixed in this effort.

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the fix.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by mneinast** [comment]
Is this issue fixed?  When I search for sample `xz944-t` I see that Peak Group matches Primary Compound name for `3-hydroxybutyrate`

**Comment by hepcat72** [comment]
My thinking on this has somewhat changed given a discussion I had with Lance.  I think there's still an issue, but I think it's related to the template and not the data.  So, the thinking is this (which Lance reminded me of):

- PeakGroup name holds information related to the compound that's not in the Compound record.  That's because the list of synonyms can include (for example) stereoisomers.  Lance pointed out that the researcher could explicitly select one of the stereoisomers when selecting what "compound synonym" to use for the PeakGroup name.
- The compound record makes no distinction about the difference, thus that information (a specific stereoisomer) only resides in `PeakGroup.name`.
- Thus, my suggestion to always use `Compound.name` as the PeakGroup name (for consistent searchability) is (to a degree) wrong.  There *do* exist synonyms that are qualitatively equivalent, and that represents a real searchability issue, but since we don't record these differences, there's no way to handle the searchability issue **and** retain the information that `PeakGroup.name` adds.
  - One possible solution would be to add a field in the CompoundSynonym table that records qualitative differences, but I don't think that's a priority ATM.

But the issue that I think remains might be that either the peakgroup name column doesn't exist or is inappropriately using using Compound.name (I think it's the former, in which case I might have just been misunderstanding the relationship between those 2 name fields, in which case it's potentially a transparency issue).

**Comment by mneinast** [comment]
I see that there are advantages to keeping `PeakGroup.name` specific to the original submission.  Switching to that sounds reasonable to me.

**Comment by hepcat72** [comment]
I cannot reproduce this issue and I cannot find anything wrong with the templates, so I'm going to close this issue. Either I somehow got my wires crossed clicking links or the data changed (probably the former).  So I'm closing this.  If I encounter a problem again, I'll double check and take screenshots.
