### ISSUE TITLE
Support import of Singly Labeled IsoCorr13C15N corrected data

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#349]
### Feature Inspiration

Some lab members use [IsoCorr](https://github.com/xxing9703/isocorr13C15N) to correct data (usually dual-labeled data) instead of [AccuCor](https://github.com/XiaoyangSu/AccuCor). The software is generally used when tracer compounds have both N and C labeled elements, but it does support singly labeled data as well.

### Feature Description

PeakData from IsoCorr13C15N files should be loadable without modification of the data files.

### Alternatives Considered

Loading data with multiple isotopes per tracer (#430) will require some design changes and may be part of this PR or a separate PR, depending on developer preference.

### Comment

Example data will be provided via #431.

-----
### Assumptions

none

### Requirements

- [x] load_accucor_msruns.py should optionally accept an isocor corrected csv file of singly labeled tracer data instead of an accucor xlsx file
- [x] No modifications to the isocor file should be necessary
- [x] Original data should not need to be supplied to perform the load
- [x] Dual isocor labeled data supplied to this singly-labeled accucor load feature should cause an error

### Limitations

- This issue isn't meant to result in the loading of the new infusate/multi-tracer/multi-label database schema.  It is only to be able to parse and handle the isocorr data format, thus this issue only handles parsing and validating files
- This issue does not implement isocorr xlsx pasring - csv only

### Affected/Changed Components

- [`load_accucor_msruns.py`](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/DataRepo/management/commands/load_accucor_msruns.py)
- [`utils.py`](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/DataRepo/utils.py)

#### GUI Change description

Adds an isocor csv file option to the command line interface.

#### Code Change Description *(Pseudocode optional)*

Since IsoCorr13C15N outputs only corrected data in a `.csv` file, loading can be handled much like the case where AccuCor files are `.csv` files without the original data (see #218).

#### Tests

- [x] Add to `DataRepo.tests.test_models.AccuCorDataLoadingTests`: Create a test that loads the isocorr dataset and asserts that the animals, samples, peakgroups, and peakdata records were properly loaded
- [x] Add to `DataRepo.tests.test_models.AccuCorDataLoadingTests`: Create a test to show that multiple labeled elements throws an error
- [x] Fix existing: `DataRepo.tests.test_models.ParseIsotopeLabelTests`
- [x] Fix existing: `DataRepo.tests.test_models.AccuCorDataLoadingTests`
- [x] Fix existing: `DataRepo.tests.test_models.StudyLoadingTests`
- [x] Add to `DataRepo.tests.test_models.StudyLoadingTests`: Load the singly labeled isocorr data as a study

**Comment by hepcat72** [comment]
merged
