### ISSUE TITLE
Change `atom` to `element`

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#35]
Change references in the code from `atom` to the correct term, `element`

**Comment by lparsons** [comment]
OK, I did some more research myself, and it does seem that most cases in this project, `atom` is the correct / appropriate term. An `atom` can be defined as ["An atom is the smallest unit of matter that retains all of the chemical properties of an element."](https://www.khanacademy.org/science/ap-biology/chemistry-of-life/elements-of-life/a/matter-elements-atoms-article). An `element` is ["a substance that is made entirely from one type of atom"](https://education.jlab.org/qa/atom_02.html).

Since we are discussing the labeling of individual atoms, it would make sense to me to use `atom` consistently throughout this project. I think it's appropriate to use the term "carbon atom" when referring to an individual atom of the element carbon.

Thoughts from @hepcat72 or @mneinast ?

**Comment by hepcat72** [comment]
Yeah.  I think atom is fine.  It's funny.  I always thought of "atmoic number" in the periodic table as "number of atoms" (number of protons and of neutrons, I guess).  Proton, neutron, and electron are unambiguous, at least.  And the original notion of "atom" was the smallest piece of matter that could not be divided, but the term has evolved from that original notion when it was discovered you could "split" the "atom".  So I think either term works.  I just think atom is just slightly ambiguous.
