### ISSUE TITLE
Management command to load new tissue records

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#350]
### Feature Inspiration

New studies occasionally will add new tissue types, similar to how new compounds are added. The ability to add these to the study loading process would be helpful.

### Feature Description

* A new management command to load tissue records (analogous to the `load_compounds` command)
* Update tests, etc. to load tissues using this new method

### Alternatives Considered

New tissues records could be added to the current tissues fixture and the fixture reloaded when tissues need to be updated. This may be sufficient, since tissues are likely to be added less often that compounds.

### Comment

If this is implemented, the https://github.com/PrincetonUniversity/tracebase-rabinowitz-data repository should be updated to include this functionality.

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by lparsons** [comment]
@fkang-pu @jcmatese @hepcat72 We have one dataset submitted with two new tissue types that I would like to get loaded.

Are people generally in agreement that tissues should be handled more like compounds (and thus loaded along with other data)? 
  * If yes, then
    * We could implement this before loading that dataset.
    * We could add the tissues to the fixture, load the dataset, and implement this later.
  * If not, I could simply add the tissue types to the fixture, load that on tracebase-dev, and load the new study and we can hold off any decision regarding loading of new tissues.

Thoughts or preferences? I think I'd rather make this change, then load the dataset myself, but any of these options would be OK depending on peoples thoughts.

**Comment by jcmatese** [comment]
@lparsons Might be prompted by my [likely-one-off] issues when running through the contributing steps the other day (#372 ), for the first time after applying the validation migration.  Uncertain if the "fix" is updated docs, coding tweaks, or just let it be (because may not be a _persistent_ issue).  Not stressing about it, but come publication time (e.g."code-in-the wild"), we might want to decide on philosophies on data releases, assumptions that databases generally can/should be blown away and reloaded from scratch, etc.  I think the validation migration was kind of exceptional, though, in that it was an entire new database, intended to mirror a subset of tables of the existing database.

**Comment by lparsons** [comment]
Thank @jcmatese , that makes sense. Perhaps something is still missing from docs. I'm don't have all of the steps to setup caching and validation databases straight in my head yet. I'll be sure to run through everything and update docs as necessary when we push out the updates and data to `tracebase-dev`.

**Comment by hepcat72** [comment]
How did I even come by this issue? Was there a comment added that was deleted or am I going insane?  I only commented on it because I thought it was new.  I'd *thought* this was done, but my default is to assume I'd forgotten something.

**Comment by lparsons** [comment]
Not sure. It was closed 23 days ago, and then commented on by you about an hour ago. Anyway, let me know if something is amiss.

**Comment by hepcat72** [comment]
Yeah, I saw that. That's why I questioned my sanity.

**Comment by lparsons** [comment]
TGIF!
