### ISSUE TITLE
`load_accucor_msruns` command inserts records into the database when `debug` is set

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#357]
Incidentally, WRT the database side-effects, I think that when DEBUG=True, it appears that calls to `Model.objects.get_or_create` and the call to `Protocol.retrieve_or_create_protocol` are retained even when the debug assertion exception happens.

_Originally posted by @hepcat72 in https://github.com/Princeton-LSI-ResearchComputing/tracebase/issues/345#issuecomment-1026232384_

See comment in code here:
https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/356/files#diff-b8fd16e59cc6c39d77ead64f80367681defb6eaffc5e8584a646d17cdde2615fR69

**Comment by hepcat72** [comment]
This issue is outdated.  The `load_accucor_msruns` script was replaced and all calls to `get_or_create` occur inside atomic transaction blocks.  Since `load_accucor_msruns` is deprecated and planned for removal, closing this issue.
