### ISSUE TITLE
Tissues are being loaded unnecessarily for some subset of tests

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#358]
sure, which is why I could see this for any loading tests of animals, samples, studies, data, etc.  But I don't think compound loading requires that.
https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/94069cb5f51e4c11e54025f96c86a7c71b07794c/DataRepo/tests/test_loading.py#L10-L33
I mean, it doesn't hurt, but it _may_ be that tissues are being loaded unnecessarily for some subset of tests.

_Originally posted by @jcmatese in https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/356#discussion_r798913921_

**Comment by jcmatese** [comment]
https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/5168d3ea5ffe09cc2c01b9777c1c28bcedaa7b50/DataRepo/tests/test_models.py#L439-L453

**Comment by jcmatese** [comment]
https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/5168d3ea5ffe09cc2c01b9777c1c28bcedaa7b50/DataRepo/tests/test_models.py#L458-L542

**Comment by lparsons** [comment]
I believe the difference is that `CompoundValidationLoadingTests` sets `validate_only=True` while `CompoundLoadingTests` does not, so they do not seem redundant. However, I don't see a reason that either class should load any Tissue records.

**Comment by jcmatese** [comment]
I was referring to the 2 classes, both named `CompoundLoadingTests` , one in test_loading.py and one in test_models.py .

**Comment by jcmatese** [comment]
I guess they both call `test_compounds_loaded` but one class goes further, with other stuff...

**Comment by lparsons** [comment]
Sorry, didn't see that, I was looking at the code references you posted. I agree that https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/DataRepo/tests/test_loading.py is not needed. I believe I started writing that in a vain attempt to organize the tests and ended up removing just about everything useful. Perhaps this issue should be changed to remove that file entirely.

**Comment by hepcat72** [comment]
Legacy code.
