### ISSUE TITLE
Multiple Tracer Compounds / Single Labeled Element (13C-leucine + 13C-valine)

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#375]
### Feature Inspiration

Support for experiments that involve animals infused with multiple tracer compounds, each which has a single labeled elements. For example, an Animal infused with 13C-leucine and 13C-valine.

### Feature Description

A brief description of *what* the feature should do (not *how* it will be done - for that, jump down to the *Code Change Description* section below to make suggestions).

* [ ] Identify example input data that fits this type of experiment **TBD**
* [ ] Determine the desired output changes for this type of experiment **TBD**

### Alternatives Considered

A brief description of any alternative features that may accomplish the same ultimate goal.

### Comment

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by mneinast** [comment]
Here is my recommendation, described in these [google drive slides](https://docs.google.com/presentation/d/1US08FxF7_hOIkqcKyRkYtLrZs1ZllsJ4MDsfdAd5Zck/edit?usp=sharing)  and summarized below:

- Input data for this case (Maven Output and Accucor files) is not different from our standard case (single tracer compound, single labeled element).  However, the Animals Information Sheet needs to accommodate multiple tracer compounds.
- PeakData output is unchanged.
- PeakGroups: Normalized Labeling is not calculated.
- Fcirc reports values for each tracer compound as additional rows.

As described in the slides, an example dataset is actually already uploaded to TraceBase, but only one Tracer Compound was listed:  [MN_exp027e_KR infusion](http://tracebase-dev.princeton.edu/DataRepo/studies/4/)
 - The original dataset is here: [google drive](https://drive.google.com/drive/folders/1B4F8-kLJ7csmmHi3LM-j2K71zATXHzK4?usp=sharing)
 - A revised dataset is here: [google drive](https://drive.google.com/drive/folders/1SkUCfppwXpH7ouoj-9o8ri0utYBAERLN?usp=sharing)
   - I only revised the Animals Information sheet.  Additional changes are probably necessary.

**Comment by lparsons** [comment]
Merged into #364
