### ISSUE TITLE
MultiLabel and MultiTracer Data Model

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#391]
### Feature Inspiration

Having a proposed data model that incorporates multiple labels per tracer and multiple tracers per animal will allow the team a chance to review and weigh in with any concerns. This is especially helpful since each developer has expertise in different areas of the codebase that might be affected by these changes.

### Feature Description

![QuickDBD-TraceBase Multiple Tracers and Labels (2)](https://user-images.githubusercontent.com/645128/160925685-faeedefe-106a-4bf7-a166-cfaeafb761c5.png)

### Alternatives Considered

Various alternative models were discussed, some are linked in the comments, others can be found on [Google Drive](https://drive.google.com/drive/folders/1NuL5E0KTvicnB9K9LKx-1TENoFpg83W7?usp=sharing)

### Comment

For reference, an old version of the data model is shown in #16.

-----

### Assumptions

- Each animal will have only one infusate (if there does exist a case where the same animal gets more than one infusion, it will have to be modeled as a separate animal)

### Requirements

Support the following relationships
- Animals are infused with Tracer Mixtures at a specific rate
- Tracer Mixtures consist of one or more Tracer Compounds, each of which has a specific concentration
- Tracer Compounds must be linked to a “parent compound” which will in turn, link to PeakGroup (and PeakData) records
- Tracer Compounds have one or more labeled elements (with count and optional position)
- PeakData measure one or more labeled elements with counts (no position)
- A PeakGroup is a collection of measurements for each isotopomer (labeled form) of a (ideally) single “parent compound”

### Limitations

- This design does not cover adding the derived fields at the moment for values like `fraction`, `normalized_enrichment`, etc. Those will be added at a later stage.

### Affected/Changed Components

This is a design issue, not code will be added/changed.

**Comment by fkang-pu** [comment]
I try to list design options with a few examples on paper, so it will be easier for us to have discussions next week. Just uploaded an Excel file named [multiTracers_design_20220304.xlsx](https://docs.google.com/spreadsheets/d/1ZO1pxuzCiJurstU7rQz78pe3SGBO48N_/edit?usp=sharing&ouid=115365092350395816818&rtpof=true&sd=true). The file contains multiple worksheets, but the details and notes are mainly in two worksheets(highlighted in red):

- design-multiple-tracers
- xzl1_brain-13C15N-glutamine

**Comment by hepcat72** [comment]
@fkang-pu @jcmatese @lparsons

I performed a review of Fan's [multiTracers_design_20220304.xlsx](https://docs.google.com/spreadsheets/d/1ZO1pxuzCiJurstU7rQz78pe3SGBO48N_/edit?usp=sharing&ouid=115365092350395816818&rtpof=true&sd=true).  I only added comments, so I didn't copy the file.  (Note sure what happens to comments if the file changes though.)

I am thinking that I will propose a design as well.  I will post it here in the comments of this issue when I'm done.

**Comment by hepcat72** [comment]
OK.  [Here is my idea about the changes to the schema.](https://docs.google.com/drawings/d/1-Je-lMt81qm3V-3M10-yZI_maZHax8ZeL8Ad6y2htGU/edit?usp=sharing).  Please take a look and review by adding comments.  I have commented with my thoughts explaining why I am proposing specific portions of the structure.  Note, some "through" (i.e. "linking") tables are not depicted graphically, but are described in the table itself.

The approach I took was to get close to third normal form.  I fully expect we may condense some things (such as the Atom table) into others, but I felt it was important to at least get a full sense of the relationships in 3NF to help us decide what to condense.

I took the liberty to use this as an opportunity to make some changes unrelated to multiple tracers, such as a researcher table, and removing redundant data (like Compound.name).

@jcmatese @fkang-pu @lparsons @mneinast

Michael - I tagged you to possibly provide insight on whether or not we ever know which tracers have which labeled elements in which positions.  I had initially thought that we didn't necessarily know what position a labeled element is in, but when I see things like "[13C5, 15N2]-glutamine", I realize that's not (always?) the case.  I believe this describes a glutamine with a carbon-13 in position 5 and a nitrogen-15 in position 2.  (I use that example in my comments on my proposed schema change.)

**Comment by hepcat72** [comment]
Oh, also, I started out by creating a [UML diagram of the current database schema](https://docs.google.com/drawings/d/1Vo3bi0EX9VJxFHVHXzoCCb6LlWLWgcW2I8LskQEoHws/edit?usp=sharing), which I provide for reference.

**Comment by mneinast** [comment]
> when I see things like "[13C5, 15N2]-glutamine", I realize that's not (always?) the case. I believe this describes a glutamine with a carbon-13 in position 5 and a nitrogen-15 in position 2.

Actually this indicates the count of labeled atoms, so this indicates there are 5 heavy carbons and 2 heavy nitrogens.

A positional tracer will have additional numbers in front of the element.  For example, `1,2-13C2-glutamine` has two total heavy carbons at positions 1 and 2.  Here is an [example at cambridge isotopes](https://shop.isotope.com/productdetails.aspx?itemno=CLM-2001-PK).

The first example `[13C5, 15N2]-glutamine` could therefore also be written as `[1,2,3,4,5-13C5; 2,5-15N2]-glutamine`.

**Comment by lparsons** [comment]
We have the designs pretty much complete in [TraceBase Tracer Modeling Part I](https://docs.google.com/presentation/d/1CFKJar7QymA1DO9mChEKX68hmIE5-GB9sVhxGolAnXM/edit?usp=sharing) and [TraceBase Tracer Modeling Part II](https://docs.google.com/presentation/d/1Q55Z4qNeWsFXNYNOD5wzE8Hox1oDQ5dfmoGCbSPHaFo/edit?usp=sharing). Closing this.
