### ISSUE TITLE
Update PeakData output format to accommodate data with multiple labels per tracer

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#393]
### Feature Inspiration

Experiments that use tracers with multiple labels require peak data rows for each combination of labels, for example:
* C0, N0 - Unlabeled
* C0, N1 - Nitrogen Labeled only (1)
* C0, N2 - Nitrogen Labeled only (2)
* C1, N0 - Carbon Labeled only (1)
* C2, N0 - Carbon Labeled only (2)
* C1, N1 - Carbon and Nitrogen labeled (1, 1)
* C1, N2 - Carbon and Nitrogen labeled (1, 2)
* C2, N1 - Carbon and Nitrogen labeled (2, 1)
* C2, N2 - Carbon and Nitrogen labeled (2, 2)

### Feature Description

* Additional rows for each combination of labeling.
* PeakData:Fraction is the fraction of 'this' isotope out of all isotopes (including both elements).

Examples
* [google slides describing expected outputs](https://docs.google.com/presentation/d/1LjFfvoWVjKwN434eZFGzi2vHFO1P2VitOE8xNc92Cz4/edit?usp=sharing)
* [google sheet of example calculations](https://docs.google.com/spreadsheets/d/1OfwWCgYlLi3XH9QS62ekn-dlEyldwj7fV260Gp2yFjY/edit?usp=sharing)

### Alternatives Considered

None

### Comment

NOTE: This may be broken into multiple issues to track the changes required to the functions computing the values separately from the changes to the views.

-----

### Assumptions

- A PeakData record links to a combination of PeakDataLabel records that represent a single labeling state (e.g. C2, N0), thus there is no need to "split_rows"

### Requirements

- [ ] Comma-delimit the element:count column

### Limitations

none

### Affected/Changed Components

- `DataRepo/templates/DataRepo/search/results/peakdata.html`
- `DataRepo/formats/peakdata_dataformat.py`

#### GUI Change description

Comma-delimited element:count column and a row for each labeling combination.

#### Code Change Description *(Pseudocode optional)*

- Add `PeakDataLabel` to `peakdata_format.py`
- Set `split_rows` for `PeakDataLabel` to true
- Update PeakData fields

#### Tests

- [ ] Call performQuery to find 1 peakdata record(s) with 2 labeled elements and confirm the number of root table records is 1
- Note there's no way to test that the template renders comma-delimited elements/counts

**Comment by hepcat72** [comment]
Ugh. I started working on this, but realized I can't test out the interface due to extant errors from various recent code changes.

**Comment by hepcat72** [comment]
Merged
