### ISSUE TITLE
Update PeakGroup output format to accommodate data with multiple labels per tracer

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#394]
### Feature Inspiration

Experiments that use tracers with multiple labels will have multiple enrichment fraction and normalized labeling values per PeakGroup. This requires an update to the output table, which right now only displays one enrichment fraction and one normalized labeling per PeakGroup.

### Feature Description

- Add a labeled element column and split each PeakGroup into a different row for each labeled element. The elements included in the split will be the labeled elements of the tracers that the measured compound also has (i.e. exclude rows for tracer labeled elements that are not in the measured compound).
- PeakGroups:'Total Abundance' will be calculated for each peakgroup (i.e. it will be the same for each element-split row), and is the sum of all `PeakData.corrected_abundance`s (for all isotope combinations - including counts of 0 and observations of only 1 of multiple labeled elements because the count of the un-included element's isotope is inferred to be 0).
- PeakGroups:'Enrichment Fraction' will be calculated for each peakgroup/element combo (i.e. split by element into multiple rows per peak group).  `f(element)=SUM_for_every_linked_peakdata_row(peak_data.fraction * peak_data.labels.filter(element=element).first().count) / number_of_atoms_in_the_first_measured_compound`
- PeakGroups:'Normalized Labeling' will be calculated for each peakgroup/element combo (i.e. split by element into multiple rows per peak group)

Examples
* [google slides describing expected outputs](https://docs.google.com/presentation/d/1LjFfvoWVjKwN434eZFGzi2vHFO1P2VitOE8xNc92Cz4/edit?usp=sharing)
* [google sheet of example calculations](https://docs.google.com/spreadsheets/d/1OfwWCgYlLi3XH9QS62ekn-dlEyldwj7fV260Gp2yFjY/edit?usp=sharing)

### Alternatives Considered

This will require changing the return type of multiple methods with `cached_function` decorators.  Not sure if that will cause problems, but one alternative would be to link a new table 1:M, PeakGroup:NewTable.  The purpose of the new table would be to house calculated values of PeakGroup/LabeledElement combinations.  Hopefully, this won't be necessary.

### Comment

NOTE: This may be broken into multiple issues to track the changes required to the functions computing the values separately from the changes to the views.
-----

### Assumptions

- I noted that the  current enrichment_fraction calculation only considers the first of potentially multiple measured compounds for a peak_group when counting atom occurrences of an element. I think it's a fairly safe assumption that the atom count of the labeled element will be the same among the linked compound, so I will perpetuate that assumption.

### Requirements

- [x] Add a labeled element column and split each PeakGroup into a different row for each labeled element. The elements included in the split will be the labeled elements of the tracers that the measured compound also has (i.e. exclude rows for tracer labeled elements that are not in the measured compound).
- [x] PeakGroups:'Total Abundance' will be calculated for each peakgroup (i.e. it will be the same for each element-split row), and is the sum of all `PeakData.corrected_abundance`s (for all isotope combinations - including counts of 0 and observations of only 1 of multiple labeled elements because the count of the un-included element's isotope is inferred to be 0).
- [x] PeakGroups:'Enrichment Fraction' will be calculated for each peakgroup/element combo (i.e. split by element into multiple rows per peak group).  `f(element)=SUM_for_every_linked_peakdata_row(peak_data.fraction * peak_data.labels.filter(element=element).first().count) / number_of_atoms_in_the_first_measured_compound`
- [x] PeakGroups:'Normalized Labeling' will be calculated for each peakgroup/element combo (i.e. split by element into multiple rows per peak group)
- [ ] In order to get the code to work (since I'll be changing the return type), I will have to modify usages of returned values from calls to methods like `enrichment_fraction`, such as is in `enrichment_abundance`.

### Limitations

- This will not modify the database to be able to create a field maintained via a `field_updater_function` tag (will be handled in a later PR)

### Affected/Changed Components

- `DataRepo/models/peak_group.py`
- `DataRepo/formats/peakgroups_dataformat.py`
- `DataRepo/templates/DataRepo/search/downloads/peakgroups_colheads.tsv`
- `DataRepo/templates/DataRepo/search/downloads/peakgroups_row.tsv`
- `DataRepo/templates/DataRepo/search/results/peakgroups.html`

#### GUI Change description

New element column and PeakGroup rows split on labeled element.

#### Code Change Description *(Pseudocode optional)*

In order to keep the `cached_property`/`cached_function` tags, I will make `enrichment_fraction` and `normalized_labeling` return a dict keyed on element.

Other than that, the changes are straightforward data/template changes.

#### Tests

A test for each requirement (above)

**Comment by hepcat72** [comment]
merged
