### ISSUE TITLE
Update FCirc output format to accommodate data with multiple labels per tracer

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#395]
### Feature Inspiration

Experiments that use tracers with multiple labels will have multiple Ra/Rd values per Animal, one for each labeled element. This requires an update to the output table, which right now only displays one set of values per serum sample.

### Feature Description

- Fcirc will need to incorporate labeled element into calculations, and display data from a single sample in a different row for each labeled element.
- Fcirc(intact) is split by element
- Fcirc(average) is split by element

Examples
* [google slides describing expected outputs](https://docs.google.com/presentation/d/1LjFfvoWVjKwN434eZFGzi2vHFO1P2VitOE8xNc92Cz4/edit?usp=sharing)
* [google sheet of example calculations](https://docs.google.com/spreadsheets/d/1OfwWCgYlLi3XH9QS62ekn-dlEyldwj7fV260Gp2yFjY/edit?usp=sharing)

### Comment

NOTE: This may be broken into multiple issues to track the changes required to the functions computing the values separately from the changes to the views.

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by hepcat72** [comment]
ToDo:

- [ ] Change "final" to "last"
- [ ] Remove outdated methods like `last_serum_sample` and `last_serum_sample_id` in deference to the `last_serum_sample_peak_group[_label]` methods
- [ ] Change AnimalLabel.final_serum_sample_tracer_label_peak_groups to use `Animal.last_serum_sample_peak_group_label` because it shouldn't limit itself to the final serum sample.
- [ ] Remove (and re-test with test_views) all the `.using(self._db)` additions to Infusate/Tracer/TracerLabel/InfusateTracer model classes.
- [ ] Revert the various `on_delete=models.CASCADE` instances to on_delete=`models.RESTRICT` and re-test with test_views
  - [ ] Tracer.compound
  - [ ] Animal.infusate
- [ ] Revert the order of Infusate & InfusateTracer in `ALL_MODELS_IN_SAFE_DELETION_ORDER` and it's test

**Comment by hepcat72** [comment]
This comment is a WIP... Working toward organizing/streamlining the "last" methods referring to which peak groups to use for specific tracer calculations...

I need to better organize and consolidate the "last*" methods:
```
$ git grep "def last_"
DataRepo/models/animal.py:    def last_serum_sample(self):
DataRepo/models/animal.py:    def last_serum_sample_id(self):
DataRepo/models/animal.py:    def last_serum_sample_peak_group(self, compound=None, compounds=None):
DataRepo/models/animal.py:    def last_serum_sample_peak_group_label(self, compound, element):
DataRepo/models/animal_label.py:    def last_serum_sample_tracer_label_peak_groups(self):
DataRepo/models/fcirc.py:    def last_peak_group(self):
DataRepo/models/sample.py:    def last_peak_group(self, compound):
$ git grep "def is_last_"
DataRepo/models/peak_group.py:    def is_last_serum_peak_group(self):
```

Perhaps:
- `Animal`
  - [ ] `last_serum_tracer_peak_groups(self)` (returns last serum peak groups for every tracer)
  - [ ] `last_serum_sample(self)` (returns last serum sample)
- `AnimalLabel`
  - [ ] `last_serum_tracer_label_peak_groups(self)` (returns last serum peak groups for every tracer with self.element)
- Sample
  - [ ] `last_tracer_peak_groups(self)` (returns last peak groups for every tracer)
- `FCirc`
  - [ ] `last_peak_group(self)` (returns last peak group for self.tracer with measurements for self.element)
