### ISSUE TITLE
Update PeakData output format to accommodate data with multiple tracer compounds per animal

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#396]
### Feature Inspiration

Experiments that use multiple tracer compounds per animal will require listing multiple tracer compounds for each peak data row.

### Feature Description

The results should be grouped by peak data id and the tracer compound column should be collapse (along with other columns like study which could also contain multiple values).

Recommendation from @mneinast, described in these [google drive slides](https://docs.google.com/presentation/d/1US08FxF7_hOIkqcKyRkYtLrZs1ZllsJ4MDsfdAd5Zck/edit?usp=sharing)

### Alternatives Considered

None

### Comment

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by hepcat72** [comment]
Merged
