### ISSUE TITLE
Update PeakGroup output format to accommodate data with multiple tracer compounds per animal

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#397]
### Feature Inspiration

Researchers sometimes run experiments that use multiple tracer compounds per animal.

### Feature Description

Add support for multiple tracer compounds per animal to the PeakGroup format (since currently the page is broken).  While computing normalized labeling may be done for these cases in the future, since computing these values because the values will have to be done differently, Normalized Labeling will not be calculated for PeakGroups with multiple tracer compounds.

### Alternatives Considered

none

### Comment

Recommendation from @mneinast, described in these [google drive slides](https://docs.google.com/presentation/d/1US08FxF7_hOIkqcKyRkYtLrZs1ZllsJ4MDsfdAd5Zck/edit?usp=sharing)

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by hepcat72** [comment]
Merged
