### ISSUE TITLE
Add the "MN_exp027e_KR infusion" dataset as an example of a dataset using multiple tracers

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#399]
### Feature Inspiration

Having solid, real-life example datasets that contain data with multiple labeled elements per tracer and multiple tracers per animal will make the development of support for this data much simpler. The `MN_exp027e_KR infusion` dataset is a well understood, straightforward example using multiple tracers.

### Feature Description

The `MN_exp027e_KR infusion` dataset is actually already uploaded to TraceBase, but only one Tracer Compound was listed:  [MN_exp027e_KR infusion](http://tracebase-dev.princeton.edu/DataRepo/studies/4/)
 - The original dataset is here: [google drive](https://drive.google.com/drive/folders/1B4F8-kLJ7csmmHi3LM-j2K71zATXHzK4?usp=sharing)
 - A revised dataset is here: [google drive](https://drive.google.com/drive/folders/1SkUCfppwXpH7ouoj-9o8ri0utYBAERLN?usp=sharing)
   - I only revised the Animals Information sheet.  Additional changes are probably necessary.

### Comment

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by hepcat72** [comment]
I just now see that this issue is assigned already, but I was looking at the modified GD data and noted column formats using bars to delimit the multiple tracers. Is that Animals sheet where the encoded infusate name will come in that needs to be parsed?  Have we decided on the column structure (header names, how to incorporate the infusate name with concentration, etc) or is that a separate issue?

**Comment by lparsons** [comment]
I believe the columns were already determined in #400. Also, there are already some datasets with the new format from #389.

**Comment by lparsons** [comment]
Closing this in favor of https://github.com/PrincetonUniversity/tracebase-rabinowitz-data/issues/43
