### ISSUE TITLE
Organize models in a package

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#404]
### Feature Inspiration

A large `models.py` file is hard to look through and update. 

### Feature Description

Break up `models.py` into a `models` package (see https://docs.djangoproject.com/en/4.0/topics/db/models/#organizing-models-in-a-package)

### Comment

Take care to communicate with other developers so they are aware of this incoming PR and can avoid making large changes to the `models.py` file during this refactor.

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by jcmatese** [comment]
@fkang-pu @hepcat72 @lparsons Anyone currently "making large changes to the `models.py` file"?  Should I go ahead and embark on this, and is there a specific version of main I should branch from? (should I wait for any existing PRs or unknown branches to be merged first)?

**Comment by lparsons** [comment]
I say go for it, I don't think any outstanding PRs touch `models.py`.
