### ISSUE TITLE
Tracer related models for multi-tracer and multi-label support

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#406]
### Feature Inspiration

Many datasets generated by the lab utilize some combination of multiple labeled elements per tracer and multiple tracer compounds per animal. TraceBase must be able to store this type of data and perform at least basic computation and export. Currently, each animal has a single tracer with a single element labeled.

![image](https://user-images.githubusercontent.com/645128/160927591-42fd620c-d0e6-467a-a04c-55ce978ff427.png)

### Feature Description

Update Django models to support:
* infusions that include multiple labeled tracer compounds
* tracer compounds that are labeled with multiple elements, with each element having a labeling cardinality and list of positions

### Alternatives Considered

There were various alternative designs proposed, including using JSON fields.

### Comment

-----

### Requirements

- [x] Remove tracer related fields from Animal model
- [x] Infusate in the animal model is optional
- [x] Infusate short_name is optional
- [x] Infusate short_name is unique
- [x] InfusateTracer concentration is required
- [x] TracerLabel will have a composite unique index on `element`, `mass_number`, `count`, and `positions`.
- [x] There will be a way to generate a derived name for the Infusate object a method (e.g. a `Infusate._name()` method that uses `Tracer.name`)
- [x] There will be a way to generate a derived name for the individual Tracer object (e.g. a `Tracer._name()` method)

Rob's edit...
Removed the requirements:

- Infusate name will be derived using the format in #400 (generated on save of the object)
- Tracer name will be derived using the format in #400 (generated on the save of the object)

...as I don't think they affect the model update (unless field characteristics can be inferred from the content of issue #400, though if they can, the requirement would be those characteristics, and a reference to that issue would inform work on that requirement)

### Limitations
- Many parts of the codebase will break after this issue is addressed. **Merge these changes into `multi_tracer_label_aggregate_branch`, then merge that branch to main**
- Loading code updates are not a part of this issue.
- Name parsing and validation is not part of this issue, but will be addresses separately (#407)

### Assumptions
- Each animal will have only one infusate (if there does exist a case where the same animal gets more than one infusion, it will have to be modeled as a separate animal)
- Either label positions will not be searched or that users will know to create an `or`-group where position=x OR count=n, where `n` is the number of the searched element (assumed because positions aren't required when fully labeled)

### Affected/Changed Components
- `models/animal.py`
- `models/infusate.py`
- etc.

#### GUI Change description

No GUI change resulting from this specific issue.  Only models will be touched.  Other issues will touch the GUI WRT this overall effort.

#### Code Change Description *(Pseudocode optional)*

Model changes are captured in [this slide presentation](https://tracebase.slack.com/files/U01LWJVMMJ6/F03FM2522TB/tracebase_tracer_modeling).

#### Tests

- [x] Write/update tests that create an `Animal` infused with a combination of two tracers, with one tracer labeled with carbon
- [x] Test(s) of the `Infusate` method that generates the dervied name string
- [x] Test(s) of the `Tracer` method that generated the dervied name string

Rob's edit...
Removed the tests:

- ~~Test(s) for the `Infusate` class methods `parse_name` and `validate_name`~~
- ~~Test(s) for the `Tracer` class methods `parse_name` and `validate_name`~~

There were no requirements to implement these methods, all of the parsing and validation methods have been in the loading classes (which suggests these tests are just misplaced), and besides I think these belong in the loading implementation issue anyway.

**Comment by lparsons** [comment]
I believe this can be closed now, is there anything else outstanding @hepcat72 ?

**Comment by hepcat72** [comment]
merged
