### ISSUE TITLE
Peak data related models for multi-tracer and multi-label support

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#408]
### Feature Inspiration

Many datasets generated by the lab utilize some combination of multiple labeled elements per tracer and multiple tracer compounds per animal. TraceBase must be able to store this type of data and perform at least basic computation and export. Currently, each animal has a single tracer with a single element labeled.

### Feature Description

Update Django models to support:
* Peak data records that refer to multiple labeled elements

![Pasted image 20220330164537](https://user-images.githubusercontent.com/645128/160929390-8a2f700f-3da0-484f-afe6-ba26c03193bc.png)

### Alternatives Considered

There were various alternative designs proposed, including using JSON fields.

### Comment

-----

### Requirements
- [x] 1. Remove labled element and labeled count fields from PeakData model
- [x] 2. PeakDataLabel will have a composite unique index on `element`, `mass_number`, and `count`.

### Limitations
- Many parts of the codebase will break after this issue is addressed. Loading code can be updated as part of a separate issue.

### Assumptions

none

### Affected/Changed Components
- `models/peak_data.py`
- `models/peak_data_label.py`

#### GUI Change description

No GUI changes as a result of this issue.

#### Code Change Description *(Pseudocode optional)*

Create new peak data label model and remove label fields from peak data.

#### Tests
- [x] Write/update tests that create `PeakData` rows that contain various combinations of labeling

**Comment by hepcat72** [comment]
Merged
