### ISSUE TITLE
Organize utils into a package

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#413]
### Feature Inspiration

A large `utils.py` file is hard to look through and update. 

### Feature Description

Break up `utils.py` into multiple modules (and/or packages) in a `utils` package.

### Comment

Take care to communicate with other developers so they are aware of this incoming PR and can avoid making large changes to the `utils.py` file during this refactor.

-----

### Assumptions

**Existing classes in utils**

- class SampleTableLoader:
- class AccuCorDataLoader:
- class CompoundsLoader:
- class HeaderError(Exception):
- class HeaderConfigError(Exception):
- class RequiredValueError(Exception):
- class ResearcherError(Exception):
- class MissingSamplesError(Exception):
- class AmbiguousCompoundDefinitionError(Exception):
- class ValidationDatabaseSetupError(Exception):
- class QuerysetToPandasDataFrame:
- class DryRun(Exception):
- class LoadingError(Exception):
- class TissuesLoader:

**Seems like you could split this into "loaders" and "exceptions"**

```
SampleTableLoader
AccuCorDataLoader
CompoundsLoader
TissuesLoader
```

```
HeaderError
HeaderConfigError
RequiredValueError
ResearcherError
MissingSamplesError
AmbiguousCompoundDefinitionError
ValidationDatabaseSetupError
DryRun
LoadingError
```

**and then the "odd" one doing its own thing**

`QuerysetToPandasDataFrame`

I would be fine having all the loaders and QuerysetToPandasDataFrame in their own files (5 files), and bundling all the Exception subclasses together in a file?  So 6 files in the utils package, and use the `__init.py__` to map namespace?

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by jcmatese** [comment]
Proposal : I would be fine having all the loaders and QuerysetToPandasDataFrame in their own files (5 files), and bundling all the Exception subclasses together in a file? So 6 files (total) in the utils package directory, and use the __init.py__ to map namespace?

**Comment by jcmatese** [comment]
There is also this stand alone function, that might be homeless, with the above strategy

https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/5daccc83a71481519fa923de2f7d25268389970a/DataRepo/utils.py#L2115-L2142
