### ISSUE TITLE
Organize views into a package

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#414]
### Feature Inspiration

A large `views.py` file is hard to look through and update. 

### Feature Description

Break up `views.py` into multiple modules (and/or packages) in a `views` package.

### Comment

Take care to communicate with other developers so they are aware of this incoming PR and can avoid making large changes to the `views.py` file during this refactor.

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by hepcat72** [comment]
I was pouring through the views and compositeviews files yesterday, trying to think of a packaging scheme.  I'm not entirely sure of how to best organize it, but I had a few insights WRT related components between views and compositeviews.

Basically, the classes in compositeviews...

- BaseSearchView (this is the base class), derived classes:
   - FluxCircSearchView
   - PeakDataSearchView
   - PeakGroupsSearchView
- BaseAdvancedSearchView (this is a class that defined the advanced search as involving the 3 derived classes)

...together, define essentially the combination of models (and how to combine them) to organize the data for the (advanced) search interface.

The "views" that use that intermediate "combined model organization layer" (which I will refer to as the "composite definition") include both classes and methods:

- AdvancedSearchView
- AdvancedSearchTSVView
- search_basic
- test_barebones_advanced_search

Those views have to retrieve data from the models (using):

- getAllBrowseData
- performQuery
- getQueryStats
- constructAdvancedQuery (and constructAdvancedQueryHelper)

They pass that data to the web page, they instruct the web page (we'll ignore templates for now) how to create requests for data, and they process those requests.  They use the *composite definition* to know how to construct the model queries.

There are 3 primary forms in which data is passed around:

- querysets
- "qry" objects (python dict or json object)
- form data

The `qry` objects are sent to the webpage to tell the web page how to create the search query interface (which is done via the template and javascript), and individual queries come back as "form data".  When the view receives the form data, it has to convert the form data into a `qry` object.  And that qry object is used to construct the database query (mentioned above).

The `qry` object has a number of methods for creation, validation, and and reporting:

- creation
   - createNewBasicQuery
   - getFirstEmptyQuery
   - getDownloadQryList
   - Building
      - createFilterGroup
      - createFilterCondition
      - appendFilterToGroup
      - searchFieldToDisplayField (for populating a form from a linked ID search)
         - which uses getJoinedRecFieldValue
   - Conversion (form data to qry)
      - formsetsToDic (and formsetToDict), which uses:
         - pathStepToPosGroupType
         - rootToFormatInfo
- validation
   - isQryObjValid
   - isValidQryObjPopulated (and isValidQryObjPopulatedHelper)
- Interrogation (getters)
   - extractFldPaths (and extractFldPathsHelper)
   - splitCommon
   - splitPathName

We could probably lump the model queries into the `qry` object as well, as those methods take a qry object as input.

I've tried to come up with a way to organize the files, but I'm not sure how best to do it, though O do think that these would make good files, however they are organized:

From compositeviews.py:
- BaseSearchView.py (probably rename as `BaseFormat.py`)
- FluxCircSearchView.py (probably rename as `FluxCircFormat.py`)
- PeakDataSearchView.py (probably rename as `PeakDataFormat.py`)
- PeakGroupsSearchView.py (probably rename as `PeakGroupsFormat.py`)
- BaseAdvancedSearchView.py (probably rename as `FormatGroup.py`)

From views.py:
- AdvancedSearchView
- AdvancedSearchTSVView

And I think a number of "utility" methods from both files should be combined into a class:
- qry.py (probably rename as `FormatQuery.py` or something)
