### ISSUE TITLE
Organize compositeviews into a package

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#415]
### Feature Inspiration

A large `compositeviews.py` file is hard to look through and update. 

### Feature Description

Break up `compositeviews.py` into multiple modules (and/or packages) in a `compositeviews` package. This should likely be a package inside the views package from #414.

### Comment

Take care to communicate with other developers so they are aware of this incoming PR and can avoid making large changes to the `compositeviews.py` file during this refactor.

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by hepcat72** [comment]
I'm going to work on this and pull out some of the `qry`-related methods from `views.py`, as `compositeviews.py` and `views.py` each contain methods that are specifically for the `qry` objects which link views to the web pages and to the models, both via the format definitions in compositeviews.py.
