### ISSUE TITLE
Should we introduce sub-directories when reorganizing packages?

### ISSUE THREAD

**Issue by jcmatese** [Princeton-LSI-ResearchComputing/tracebase#423]
```
DataRepo:
- management
  - loaders
      __init__.py
      compound_loader.py
      accucor_data_loader.py
      ...		
  - exceptions
      __init__.py
      DryRun.py
      LoadingError.py
      ...	
  - commands
      __init__.py
      load_study.py
      ...

- utils
 - dataframes
     __init__.py
     queryset_to_pandas_dataframe.py
 - leaderboards
     __init__.py
     leaderboard_data.py
 - exceptions
      __init__.py
     ...
```

_Originally posted by @fkang-pu in https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/419#pullrequestreview-958122070_

**Comment by jcmatese** [comment]
Also see #422 organization for similar example

**Comment by lparsons** [comment]
Is everyone ok closing this?

**Comment by jcmatese** [comment]
I think it was just an idea for re-organization of everything.    The `utils` have not really been moved around, nor the `loaders` , but we can close it if you want to. (it was just a preliminary proposal from Fan)
