### ISSUE TITLE
getDistinctFields does not fully account for non-field related model reference conversion

### ISSUE THREAD

**Issue by hepcat72** [Princeton-LSI-ResearchComputing/tracebase#424]
### Problem

A recent PR uncovered a problem when a related model reference is included among other distinct fields returned by `getDistinctFields` for the Format class in dataformst.py.  While that problem currently has a work-around, the problem is now more correctly understood and needs to be fixed to avoid future issues.  The initial hunch was that this was a bug in Django's SQL generation, but upon reporting the alleged django bug, the code intended to account for an order-by "gotcha" was revealed to contain a deficiency (based on an incomplete understanding of the gotcha).  The first fields in the distinct call must match the fields in the order_by (which our code does) and must account for the fields defined in `meta.ordering` (which our code does), and must do this for all related tables (which our code does) **BUT** they must also be sensitive to ordering "fields" that are not actual *fields* in the database (which our code does not do, or rather, does incorrectly). Thus, if a related model *reference* is included among the distinct fields of the meta.ordering fields, as in the case of `CompoundSynonym`'s meta.ordering fields (including `compound` - which isn't a field), it can trigger a `ProgrammingError` exception that cryptically claims that the distinct field list must match the `order by` field list (even if the exact same list is supplied to both `order_by()` and `distinct()`).  The problem is that `compounds__synonyms__compound` is automagically changed to `compounds__synonyms__compound__name` in the `order_by` clause and changed into `compounds__synonyms__compound__id` in the `distinct` clause (or vice-versa - I didn't confirm, but I did confirm they were different) when it is written as SQL.

### Steps to reproduce

1. open the django shell and enter:
   ```
   from DataRepo.models.peak_group import PeakGroup
   qs = PeakGroup.objects.filter(msrun__sample__tissue__name__iexact="brain")
   flds=pg.getDistinctFields(assume_distinct=False, included_paths=["msrun__sample__animal","peak_data","compounds","msrun__sample","msrun__sample__tissue","msrun__sample__animal__tracer_compound","msrun__sample__animal__studies","compounds__synonyms"])
   qs.order_by(*flds).distinct(*flds).values_list(*flds)
   ```

### Current behavior

`flds =`
```
['name',
 'pk',
 'compounds__synonyms__compound',
 'compounds__synonyms__name',
 'compounds__synonyms__pk',
 'compounds__name',
 'compounds__pk',
 'msrun__sample__animal__studies__name',
 'msrun__sample__animal__studies__pk']
```

When the query is executed, you get an exception:
```
ProgrammingError: SELECT DISTINCT ON expressions must match initial ORDER BY expressions
LINE 1: ...nd_id", "DataRepo_compoundsynonym"."compound_id", "DataRepo_...
```

### Expected behavior

No exception

### Suggested Change

Note that if you change CompoundSynonym's met ordering from:

```
        ordering = ["compound", "name"]
```

to:

```
        ordering = ["compound__name", "name"]
```

There is no exception.

Having `compound` in the Synonym ordering is not the problem.  It's that including it when you want to do a distinct causes the mismatch because in 1 clause it's changed to Compound's `id` and in the other, it's changed to `name`.

The `getDistinctFields` method needs to catch these non-field references and make sure the fields returned are real fields.  There might be a supported way of doing this.  Changes may need to be made to either or both of these methods:

```
dataformat.getDistinctFields
dataformat.getOrderByFields
```

### Comment

Once this update is made, the `included_paths` argument to `getDistinctFields` can be reverted to a boolean named `split_all`, defaulting to `False`.

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will not fix
- E.g. Getting edge case X to work requires too much effort and will not be
  fixed in this effort.

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the fix.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by jcmatese** [comment]
In hindsight, we _might_ want to drop the `compound_synonym` model and change the concept to an ArrayField within `compound` (if there are not too many advantages to keeping it, and it avoids this issue, or does not make it worse)

**Comment by hepcat72** [comment]
That may be something we will do, but it's still a work-around to an existing issue. And I intend to fix it either way.
