### ISSUE TITLE
Load Animal sheets with multiple labeled elements and multiple tracers

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#427]
### Feature Inspiration

Many experiments are being performed using multiple tracer compounds per animal and multiple isotopes per tracer compound. These type of experiments must be able to be stored in TraceBase.

### Feature Description

Implement loading of Animal sheets with multiple labeled elements and multiple tracers. Using the parser implemented in #407, update the loading scripts to be able to load the sample data from #390 and #399 into the updated models (#406 and #408).

### Alternatives Considered

We discussed providing for the ability to load by old format tracer data and newly formatted tracer data.

### Comment

Note that loading of the AccuCor/IsoCorr mass spec data is handled in a separate issue.

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by hepcat72** [comment]
I inadvertently did this in #467
