### ISSUE TITLE
Add Fcirc computed values

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#43]
### Feature Inspiration

There are a number of Fcirc related values that are commonly used by researchers and are computed based off of the raw, stored data. The specific object(s) where these methods belong needs to be determined.

### Feature Description

* `tracer_Fcirc_intact` - turnover of the tracer compound for this animal, as rate of appearance of any modified form of the tracer compound (nmol/min/gram body weight) = calculated using the infusion rate of tracer in this animal and the labeling in the tracer compound from the final serum timepoint = (Animal:tracer_infusion_rate * Animal:tracer_infusion_concentration) / (Measurement:fraction) - (Animal:tracer_infusion_rate * Animal:tracer_infusion_concentration)
* `tracer_Fcirc_avg` - turnover of the tracer compound for this animal, as the rate of appearance of unlabeled atoms in the tracer compound = calculated using the infusion rate of tracer in this animal and the labeling in the tracer compound from the final serum timepoint. = (Animal:tracer_infusion_rate * Animal:tracer_infusion_concentration) / (PeakGroup:enrichment_fraction) - (Animal:infusion_rate * Animal:infusion_concentration)
* `tracer_Fcirc_intact_perMouse` - tracer_Fcirc_intact * Animal:body_weight = nmol/min/mouse
* `tracer_Fcirc_avg_perMouse` - tracer_Fcirc_avg * Animal:body_weight = nmol/min/mouse
* `tracer_Fcirc_avg_atom` - tracer_Fcirc_avg * PeakGroup:label = nmol atom / min / gram = turnover of atoms in this compound = "nmol carbon / min / g"

### Examples

[Example Fcirc Calculation](https://docs.google.com/spreadsheets/d/1b4H5rZDfzGHzvVZsmgHHUWG_u3esAhxSYF2PVgi9_zk/edit?usp=sharing)

[Bartman et al. - 2021 - Quantitative flux analysis in mammals.pdf ](https://drive.google.com/file/d/1Ts2uAQtB-eDXEkRICXzMM1mvOjTsczWd/view?usp=sharing)

#### John's 2¢
for each animal(s , in study)
get (or pay attention to)
- body_weight
- tracer_compound
- tracer_labeled_atom
- tracer_labeled_count
- tracer_infusion_rate
- tracer_infusion_concentration
retrieve all samples where  sample.tissue.name == Tissue.SERUM_TISSUE_NAME
retrieve all peak data for each sample.msruns where peak_group.compounds contain animal.tracer_compound

perhaps an animal method `serum_tracer_data` that returns a data structure containing the above?

#### Rob's 2¢
We discussed this in the developer meeting on 9/7/2021 and I thought I would jot down the thoughts we had and I'll add some things to flesh it out more...

I'll leave the selection of the columns we display in the Fcirc output format to issue #130.  WRT the collection of values we will compute, I think that if we assume one tracer compound per animal, we could have a row per animal can calculate the following values:

- `tracer_Fcirc_intact` - turnover of the tracer compound for this animal, as rate of appearance of any modified form of the tracer compound (nmol/min/gram body weight) = calculated using the infusion rate of tracer in this animal and the labeling in the tracer compound from the final serum timepoint = (Animal:tracer_infusion_rate \* Animal:tracer_infusion_concentration) / (Measurement:fraction) - (Animal:tracer_infusion_rate \* Animal:tracer_infusion_concentration)
- `Ra_intact_g`
- `Rd_intact_g`
- `Ra_intact`
- `Rd_intact`

- `tracer_Fcirc_avg` - turnover of the tracer compound for this animal, as the rate of appearance of unlabeled atoms in the tracer compound = calculated using the infusion rate of tracer in this animal and the labeling in the tracer compound from the final serum timepoint. = (Animal:tracer_infusion_rate \* Animal:tracer_infusion_concentration) / (PeakGroup:enrichment_fraction) - (Animal:infusion_rate \* Animal:infusion_concentration)
- `Ra_avg_g`
- `Rd_avg_g`
- `Ra_avg`
- `Rd_avg`

All, as calculated in the [example Michael provided](https://docs.google.com/spreadsheets/d/1b4H5rZDfzGHzvVZsmgHHUWG_u3esAhxSYF2PVgi9_zk/edit#gid=2095042101).

I think we should initially only do this for the last serum sample where steady state is assumed.  We can add additional timepoints in another issue.

### Comment

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by jcmatese** [comment]
@lparsons In the original issue description there is a `tracer_Fcirc_avg_atom` that references a `PeakGroup:label` in its formula, but I don't think that attribute exists in our model.  Do you know the original of that method, or if that component should be something else?  Thanks for the clarification.

**Comment by lparsons** [comment]
> @lparsons In the original issue description there is a `tracer_Fcirc_avg_atom` that references a `PeakGroup:label` in its formula, but I don't think that attribute exists in our model. Do you know the original of that method, or if that component should be something else? Thanks for the clarification.

@jcmatese I didn't dig too far, but I would guess that this should be `PeakData:labeled_count`.

**Comment by jcmatese** [comment]
@lparsons OK, so I suppose that would be equivalent of `animal.tracer_labeled_count` == `peakdata.labeled_count` if the `peakdata` instance was the intact version?

**Comment by lparsons** [comment]
> @lparsons OK, so I suppose that would be equivalent of `animal.tracer_labeled_count` == `peakdata.labeled_count` if the `peakdata` instance was the intact version?

Yes, those two are equal for the "intact" version of the `PeakData` instance.
