### ISSUE TITLE
Add Logging Module

### ISSUE THREAD

**Issue by hepcat72** [Princeton-LSI-ResearchComputing/tracebase#445]
NB: Would be nice to use the [logging module](https://docs.djangoproject.com/en/4.0/topics/logging/) here for some additional flexibility in output format, location, and configuration.

_Originally posted by @lparsons in https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/442#discussion_r890496237_

**Comment by hepcat72** [comment]
Dupe of #384

**Comment by lparsons** [comment]
Duplicate of #384, closing.
