### ISSUE TITLE
Core Search Functionality Requirements

### ISSUE THREAD

**Issue by hepcat72** [Princeton-LSI-ResearchComputing/tracebase#47]
### Feature Inspiration

1. Project goal from the [overview doc](https://docs.google.com/document/d/1E6-r6rbDN3mehIxCZ4zXEknY3simOVx-0Vn7orqa8aY/edit): "Researchers will be able to search, retrieve, interpret, and combine previous datasets"
2. The Search and Filter description in the customer [mockup description](https://docs.google.com/document/d/1Q7XWsMVVKHMDecXOXQUFs9bxQJcUNK4LrxHDLZT9xPg/edit): "How biological samples are selected for further analysis.  Important that the user can see the number and/or range of variables selected.  For example, I need to know if the current selection includes multiple genotypes."
  - The [search/filter customer mockup](https://drive.google.com/drive/u/1/folders/1r8T4fWQUrkbyRYOES8_2x3y73GQvza0_).
3. The Serum analysis [mockup description](https://docs.google.com/document/d/1Q7XWsMVVKHMDecXOXQUFs9bxQJcUNK4LrxHDLZT9xPg/edit): (Here, there is still flexibility for the user to group biological samples differently “Group by”: 1. I could plot data for individual mice using “group by” -> “animal ID” 2. I could plot data averaged for multiple mice using “group by -> “genotype, state” 3. Maybe this has to be implemented in the “search and filter” page?)
  - The [Serum Analysis mockup](https://drive.google.com/drive/u/1/folders/1r8T4fWQUrkbyRYOES8_2x3y73GQvza0_)
4. [Slide 7: Search & Download use-case in General Workflow Examples ppt file](https://docs.google.com/presentation/d/1ScFYGnaOsTtV8eOepXbgMuX63QLt0uHU/edit#slide=id.p7): 1. I search for all instances where 13C-glucose was infused in wildtype mice with brain samples. 2. TraceBase finds 30 experiments including 50 conditions and 200 mice 3. I filter out unwanted conditions (ie drug treatments). 4. I download processed data from 24 experiments and 130 mice

### Feature Description

Tracebase should supply functionality to collect and manipulate data for analyses.  This should include ways to:

1. Search for data using multiple keyword terms or mathematical values/ranges (e.g. greater/less than)
2. Search terms will be "and"-ed together
3. Each search will return a pre-selected (/configured) set of tables/fields in a single joined table to standardize the data columns and support repeatable R analyses via downloads
4. Sort data(/search results)
5. Export search results in a way that can be imported into R
6. Exported files will contain the search terms in the header of the file

The final search results could then be used for visualizations/plots or custom analyses via R.

### Alternatives Considered

Alt 1: The above general feature requirements were presented in the 4/27/2021 developer meeting for discussion to consider to be supported or not support in Tracebase and be thus be listed as features or limitations.  We discussed these items and decided to alter these previous items (which were changed in the list above in the *Feature Description*):

- These items were supplanted by the ability to export search results, which satisfies these desired features
  - Group subsets of data from item 1 based on common field values, and compute representational values given data in other fields (e.g. average bodyweight when grouped by age).
  - Save searches / search results
  - Share searches / search results
  - Manually filter data(/search results) (e.g. for outliers)

Alt 2: Also, a valid alternative to a robust search interface, as described in the feature description, or in the rejected feature set above, would be a simple keyword search interface.  Any desired functionality beyond that for accomplishing search, analysis, or visualization tasks would be included as hardcoded & standardized workflows.

### Comment

I'm fine with `Alt 2` above.  I have an interest in creating a robust search interface to extend work I did on similar functionality at Los Alamos.  And I just wanted to nail down what we want to do in terms of search, since it seems to be a critical feature based on what I have been hearing from the lab members in our meetings.  In particular, their mockups and docs (especially item 4 under the inspirations heading above, but items 2-4) explicitly show that they want multiple (and interactive) search terms & results, group-by functionality, and the ability to perform calculations on those groups of values.  Sort seems implicit since they want to plot.  Save and share are features that were discussed in person.

I'll also record a portion of a slack exchange discussing this search functionality (since it's ephemeral there):

> So I had attempted to explain my notion of how I think we should develop search and input of data to visualizations and analyses together, but I'm not sure I clearly conveyed the intent, so I'll make another attempt.
> Put another way, I'm motivated by code re-use and robust flexibility. I was inspired by the word "combine" (and envisioned alongside the notion of "filtering") in one of the project docs, it occurred to me that inputs into visualizations and/or analyses are just columns of data (particularly, specific database fields/columns) and that users may wish to "combine" or "filter" specific rows going into those mechanisms based on values in other fields/columns, or even combinations of field values.
> So instead of hard-coding specific sets of data going into each specific visualization and/or analysis, I propose that the collation of that data be compatible with the data produced by a search, and that that data, as mentioned in the meeting, could be manually selected or deselected on the search results page.
> I also think that those searches and/or result sets should be able to be saved and shared.  Then anytime we want to automatically generate a plot or analysis, it can be created as a shortcut through the search functionality that skips the results page and goes directly into the visualization/analysis.
> Does that clear up my previous attempt at conveying this idea?

And Michael's response:

> > Yes this is really well put!  I like the idea of highly flexible grouping.  In our normal analysis, we often cycle through multiple modes of grouping (ie check data for individual mice before looking at group averages).
> > 
> > I like the idea of basically using search / filter to build an “set” or “collection” of samples for analysis, and critically the ability to save that set for future use / sharing.  It will be important to retain the original experiment study grouping for each animal (as metadata), and it would be nice to optionally keep that original study grouping or break it during analysis.

-----

### Assumptions

- none

### Requirements

The following are my proposed search functionalities broken up into the definition of the query capabilities and the manipulation/refinement of the results.  The intention is for them to be implemented one at a time via issue creation in a similar way that the "Core Database Model" issue was used as a roadmap for individual efforts.

#### System level search requirements

- Searches can be programmatically initiated from any page/script with a simple call to a search method and directed into visualizations or analyses (i.e. workflows/pipelines), hence skipping the search results page
- search queries and the associated (possibly manually filtered) results can be saved and shared
- A search method sould be implemented independent of the search GUI that takes search queries in json format, adds search results to it, and returns the json containing the results

#### The search query interface should include the ability to:

- Include/exclude terms/values of multiple selected database fields
- Specify the means by which to match search terms/values based on field type (e.g. keyword, select list/enum, greater than, less than, etc.)
- Add search terms/values via "and" and "or"
- Preview/limit searched field values based on search values entered thus far (see the first item of the search results features for an alternative)
  - This requirement is based on [Michael's mockup description](https://docs.google.com/document/d/1Q7XWsMVVKHMDecXOXQUFs9bxQJcUNK4LrxHDLZT9xPg/edit) of the search/filter interface:
    > It is important that as the user adds search terms/selections the user be able to see the number and/or range of variables selected.  For example, I need to know if the current selection includes multiple genotypes.
    > It seems like this could be similar to adding a search field and limiting the selections to only those that exist given the other terms.
- Select fields to include in the output data table (via table join, given existing table links)

#### The search results interface should include the ability to:

- Show the search parameters at the top of the results page so they can be tweaked while viewing the results
- Paginate
- Manually Filter selected rows of results
- Sort rows based on the values in any column (ascending or descending))
- Group rows by the values in 1 or more columns (either by discrete values or bin sizes)
  - This would also include ways to represent grouped values in any column in the search results (e.g. mean, mode, median, min, max, count, etc)
- Select columns to generate plots/visualizations or on which to perform analyses
- Copy column values

##### Bonus search result features:

- Manually reorder columns
- Arbitrarily shorten or wrap column values (truncate (but provide tooltip), significant digits, etc.)
- Save search query & results manipulations (e.g. in json) so if a column sort is clicked on page 10 of the results and they are brought to page 1 of the new sorted results, they can get back to page 10

### Limitations

- none

### Affected/Changed Components

- An advanced search query page
- A search results page
- The model class (for the search method that sends/receives JSON)

#### GUI Change description

None.  This is a requirements document.  Changes with GUI results will be in separate issues that use these requirements in guiding the implementation.

#### Code Change Description *(Pseudocode optional)*

The listed requirements will be re-organized into requirements and limitations as a result of reviewing and approving this change request.

#### Tests

n/a

**Comment by hepcat72** [comment]
@lparsons @jcmatese @fkang-pu - Please have a look at the `FEATURE DESCRIPTION` half of this issue.  If a robust search interface is the direction we would like to go in Tracebase, I would like to present the `Requirements` under the issue owner section in the next meeting for hashing out the basic interface for the advanced search functionality.

**Comment by hepcat72** [comment]
@mneinast - as I mentioned in our meeting earlier this week, I am following up to have you take a look at the list of supported search features, as described in the short **Feature Description** section at the top of this page.  Feel free to check out the details on the entire page, but all I'm looking for is your approval and/or feedback on the 4 listed items in that subsection (and the 4 rejected items of `Alt 1` in the **Alternatives Considered** section) to make sure we're all on the same page.

Note however that the **ISSUE OWNER** section is stale and does not reflect the decisions made in the 4/27 developer meeting.  I will update that section once we're all settled on the feature set related to search.

If you have any concerns, we can discuss them in the next tracebase meeting.

**Comment by hepcat72** [comment]
Based on the brief discussion in the meeting today, I will go ahead and create component issues for the search features described in this issue.

**Comment by mneinast** [comment]
Some thoughts as a lab user after today's discussion:

I think the format / organization of tables generated for output should be limited.    A common set of tables that is always produced no matter what samples were selected from TraceBase will make analysis outside of TraceBase easier.  The ability to customize the data included in output (ie for download) is low priority.

In lieu of saving searches within TraceBase, could an output file be generated/downloaded that lists the search parameters used?  I fear that reproducing previous searches / datasets could be difficult without some kind of tracking.

Alt 2 (simple keyword search interface) might be less efficient compared to a partially segmented search interface (where each field can be filtered/searched).  I worry that it could also create confusion between similarly named features (ie Tracer vs Compound).

**Comment by hepcat72** [comment]
> I think the format / organization of tables generated for output should be limited. A common set of tables that is always produced no matter what samples were selected from TraceBase will make analysis outside of TraceBase easier. The ability to customize the data included in output (ie for download) is low priority.

That's a great point.  Here's a followup question.  Given a search could be done using 1 field of 1 table (e.g. animal), would you want to get back:

  1. A table of matching animal records where the Animal table dictates all the columns in the output
  2. A composite table of a standard selection of tables(/fields) that are always returned regardless of which table/field the search was on
  3. All tables/fields

Some notes:

If 1 is preferable, any search that included terms searching values in more than one table/field, e.g. tissue and compound, a result would be a joining of those 2 tables.

If 2 is preferable, what should be done if the field searched isn't in the standard composite set of tables/fields?

> In lieu of saving searches within TraceBase, could an output file be generated/downloaded that lists the search parameters used? I fear that reproducing previous searches / datasets could be difficult without some kind of tracking.

We could add that.  Wouldn't be hard.

> Alt 2 (simple keyword search interface) might be less efficient compared to a partially segmented search interface (where each field can be filtered/searched). I worry that it could also create confusion between similarly named features (ie Tracer vs Compound).

Another good insight.  This would be akin to a "simple search" or "quick search" that searches multiple fields of multiple tables.  We weren't planning on doing that proposal anyway, however, let me point out the following (which wasn't explicit in the requirements above WRT the planned search in this issue), because it's loosely related:

- Multiple search terms will be "and-ed" together

Unless you know of a specific need for joining any search terms with "or", we weren't planning on implementing that as a feature.

**Comment by hepcat72** [comment]
Regarding the first point above, I think I will move forward under the assumption that we will go with option 2 (and default to "all tables/rows").  I was initially leaning toward option 1 as a middle-of-the-road option, where entire tables to include in the results are selected.  We will have an opportunity to change that (anytime, but) in today's 3:30 developer meeting.

So to summarize the alternations to the supported search features (changed above):

1. Search for data using multiple keyword terms or mathematical values/ranges (e.g. greater/less than)
2. **Search terms will be "and"-ed together**
3. **Each search will return a pre-selected (/configured) set of tables/fields in a single joined table to standardize the data columns and support repeatable R analyses via downloads**
4. Sort data(/search results)
5. Export search results in a way that can be imported into R
6. **Exported files will contain the search terms in the header of the file**

Let me know if this adequately addresses all of the issues you brought up @mneinast.

**Comment by hepcat72** [comment]
In our meeting today, we discussed feature 3.  I think that there may be some `cons` WRT  the pre-selected set of tables/fields that span the entire database.  The main one being:

- If you are actually searching for 1 or a handful of records (or the value of 1 field in those records) from a specific "table", joining those records with other data could cause many duplicated rows across multiple pages of results, which could prove frustrating/cumbersome to navigate.

One idea to possibly mitigate this issue could be to defined some preset result "formats".  So instead of selecting each individual field you want to see, you would select a "format" that defines the fields that will be in the output.

**Comment by hepcat72** [comment]
Supplanted by #116
