### ISSUE TITLE
Update `load_study` to work with isocorr files

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#478]
### Inspiration

Studies that use isocorr data files cannot be properly loaded using the `load_study` command.

### Description

* Update the `loading.yaml` specification to include the flags/options needed to load isocorr data.
* Update the `load_study` command to parse the isocorr options.

### Comment

-----

### Assumptions

none

### Requirements

- [x] 1. The `python manage.py load_study` command on the command line should work for all accucor/isocorr files in the example_data directory

### Limitations

- This effort does not modify/update the studies' `loading.yaml` files in the data repo

### Affected Components

- `DataRepo/management/commands/load_study.py`
- `DataRepo/tests/test_models.py`

#### Interface Change description

none

#### Code Change Description

Should be straightforward.  Looks like already passes `isocorr_format`, but it was never tested. Probably only need to add to the yaml.

#### Tests

- [x] Make sure existing tests that call load_study work

**Comment by hepcat72** [comment]
Merged
