### ISSUE TITLE
Compound example data normalization [case, leading and trailing spaces]

### ISSUE THREAD

**Issue by jcmatese** [Princeton-LSI-ResearchComputing/tracebase#48]
### Problem

Manually entered data can contain errant leading/trailing spaces or mixed case that is not to spec.

Example data files are actually prime examples of variable user input, that code may need to clean/normalize.  Either that,  or the example file updated itself.  Perhaps both.

### Steps to reproduce

1. `python manage.py load_compounds "DataRepo/example_data/obob_compounds.tsv"`
2. Use `python manage.py shell` to look for compound records whose name contains `cit`

### Current behavior

Spaces (see space in "citrate ") in [compound file](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/DataRepo/example_data/obob_compounds.tsv) 
![Screen Shot 2021-04-26 at 3 31 52 PM](https://user-images.githubusercontent.com/6091114/116140043-bcf5ba00-a6a4-11eb-8efd-42717c8343b8.png) result in spaces in the database compound names:
```
>>> q = Compound.objects.filter(name__contains="cit")
>>> for o in q:
...     print(f"|{o.name}|")
... 
|citrate |
|isocitrate|
```

Mixed cases, like "glucose" [here](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/DataRepo/example_data/obob_compounds.tsv) , but "Glucose" [there](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/DataRepo/example_data/obob_maven_6eaas_inf_original.tsv) result in mixed cases in the database.

### Expected behavior

Spaces and mixed cases in the load file don't get into the database.

### Suggested Change

Detect these issues and either automatically fix or throw an error when encountered - without entering into the database.

### Comment

I am a little torn, because without these example "bad" data issues being raised, `strip()` probably would not have been first on my mind in my current coding task.  That being said, it does suggest that perhaps we might need to clean/normalize those example data files, and perhaps strip leading and trailing spaces within loading code like [load_compounds.py](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/DataRepo/management/commands/load_compounds.py). It is not clear to me that Django's [full_clean()](https://docs.djangoproject.com/en/3.2/ref/models/instances/#validating-objects) strips and leading or trailing spaces, prior to insertion/saving.

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will not fix
- E.g. Getting edge case X to work requires too much effort and will not be
  fixed in this effort.

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the fix.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by lparsons** [comment]
I strongly suggest that the example files be cleaned up before loading. All compound names should match the compound names in [`obob_compounds.tsv`](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/DataRepo/example_data/obob_compounds.tsv) exactly. Going forward that will be a requirement.

Similarly, all sample names should match the sample names in [`obob_sample_table.tsv`](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/DataRepo/example_data/obob_sample_table.tsv) exactly. For that case, it might be better to update the `obob_sample_table.tsv` file.

**Comment by hepcat72** [comment]
I think Lance's solution is efficient/sufficient, but I *always* strip off leading/trailing spaces from files that users manually touch.  Users in my experience, always do that somewhere.  I had a user send me a manually created "GTF" file the other week.  Had no tabs in it at all.  They were all spaces.

**Comment by lparsons** [comment]
> I think Lance's solution is efficient/sufficient, but I _always_ strip off leading/trailing spaces from files that users manually touch. Users in my experience, always do that somewhere. I had a user send me a manually created "GTF" file the other week. Had no tabs in it at all. They were all spaces.

Good point Rob, I don't think it would be a problem to strip leading/trailing whitespace on import, but I'd be cautious about other manipulation (_e.g._ changing case).

**Comment by jcmatese** [comment]
@lparson Only because you mentioned "I'd be cautious about ... changing case" , I did want to call attention to PR #55 , where I did employ `lower()` to map the database Compound 'glucose' from the example file's PeakGroup 'Glucose', but the PeakGroup.name itself is left/inserted as-is, I think (although I should go verify).
https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/a85766a84e8dd7fc9bceaefdfc44a16e84df03b4/DataRepo/utils.py#L344-L346

I did try to `strip()` from some text columns in that PR (those I thought were relevant).
https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/a85766a84e8dd7fc9bceaefdfc44a16e84df03b4/DataRepo/utils.py#L248-L256

**Comment by lparsons** [comment]
I feel like it would be cleaner if we "fix" the input data files to continue to enforce the rule that the compound names must match between compounds.tsv and AccuCor files. Same for sample names. If we "fix data" on the fly, it could lead to unintentional  collisions. Granted, changing case is a pretty lightweight and safe fix, but it was the choice I made in the sample loading table with compound names.

**Comment by jcmatese** [comment]
mapping from the Maven peak group names/definitions to the database is always going to be an potential issue, unless we implement a synonyms table or some other mapping layer.  Related, code that "citrate/isocitrate" entry requires
https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/a85766a84e8dd7fc9bceaefdfc44a16e84df03b4/DataRepo/utils.py#L328-L332

**Comment by lparsons** [comment]
This was discussed at our meetings multiple times. It's reasonable to ask the researchers to ensure that the names used in El-Maven `compounds.txt` file are consistent and match the names we've loaded previously. Burying code that parses names in the middle of a loading script seems like something that will be very hard to track going forward. For now, I'd rather keep it out entirely. In the future, we could a method (maybe in Compound) that parses/matches names.

**Comment by hepcat72** [comment]
Sorry.  I had to rearrange the issue description section content.  I think it's important that the form fields are entered accurately and concisely.
