### ISSUE TITLE
Re-evaluate enrichment fraction calculation

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#503]
Now that we have partially labeled tracers, we should re-evaluate the how we calculate enrichment fraction.

We defined enrichment fraction as "a weighted average of the fraction of labeled atoms for this PeakGroup in this Sample (i.e. the fraction of carbons are labeled in this PeakGroup compound)".

The formula is currently:
`Sum of all (PeakData.fraction * PeakData.labeled_count) / PeakGroup.Compound.num_atoms(PeakData.labeled_element)`

Now that we are allowing partially labeled tracers, we should consider the possibility of using the number of labeled atoms in the denominator instead of the total number of atoms.

**Comment by lparsons** [comment]
@mneinast Do you have any insight on this?

**Comment by mneinast** [comment]
I think this should be calculated for each labeled element.  So calculating 13C enrichment fraction from a multi tracer experiment would look like:

(13C + 13C15N) / (12C + 13C + 15N + 13C15N)

Does this make sense?

**Comment by hepcat72** [comment]
I'm not sure I follow. The concern is... Lets just stick to a single labeled element for now. And let's say that a compound has 6 Carbons, but the tracer has only 2 of those carbons that are labeled. The way it's calculated currently, the denominator is 6. Should it actually be 2 instead?

**Comment by mneinast** [comment]
Ah sorry!  yes the enrichment fraction should always be weighted by the total number of carbons (or other element), even if the tracer compound is not fully labeled.

**Comment by lparsons** [comment]
> Ah sorry! yes the enrichment fraction should always be weighted by the total number of carbons (or other element), even if the tracer compound is not fully labeled.

Excellent, then I think we can close this issue.
