### ISSUE TITLE
sorting on Time collected in Fcirc view

### ISSUE THREAD

**Issue by jcmatese** [Princeton-LSI-ResearchComputing/tracebase#522]
### Problem

A bird's-eye summation of what the problem is.

### Steps to reproduce

1. [Advanced Search](https://tracebase-dev.princeton.edu/DataRepo/search_advanced/)
2. Select Fcirc output
3. for Study is "exp024_michael lactate timecourse".
4. Click on `Time Collected` header 
5. 
<img width="124" alt="Screen Shot 2022-09-23 at 2 28 07 PM" src="https://user-images.githubusercontent.com/6091114/192033412-1e428c0a-788c-4bfe-becd-6cdb46b03455.png">

### Current behavior

Does not appear to sort on the column (either ASC or DESC)?
)
### Expected behavior

Sorting correctly

### Suggested Change

A guess at what might fix the issue.  *Pseudocode encouraged.*

### Comment

Any other relevant context or links to what you were working on when you
discovered the problem.

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected Components

A list of repository items, dependencies, etc, labeled with add, delete, or
change.  One item per line.  (Mostly, this will be a list of files.)

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

#### GUI Change description

Describe changes the user will see.

#### Code Change Description

Describe code changes planned for the feature. *(Pseudocode encouraged)*

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by hepcat72** [comment]
This was fixed by #521
