### ISSUE TITLE
Allow treatment descriptions to be specified when loading study data

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#523]
### Inspiration

Many studies do not have specific treatments, and thus have an entry `no treatment`. There was a request to use the description `no manipulation besides what is already described in other fields` for the `no treatment` option (https://github.com/PrincetonUniversity/tracebase-rabinowitz-data/issues/23).

### Description

Allow for treatment descriptions to be specified when loading data. After some discussion on Oct 5, we decided it would simplest to handle treatments with a separate loading command, much like we do with tissues and compounds. We would then maintain a consolidated list of treatments.

### Alternatives

The source of the descriptions could come from various places:
* command line parameters (and corresponding yaml fields)
* values in the Excel sheet
* "pre-loaded" in a similar way to compounds and tissues

### Comment

-----

### Assumptions

- Treatments will be fixed manually to ensure they match with existing entries and we aren't using the same name for two different things.

### Requirements

- [ ] 1. `load_treatments` management command that accepts a tsv file with treatment name and treatment description (as an option, specifying an excel file and worksheet name would make loading directly from the animals/sample sheet possible, nice but not required).
- [ ] 2. If a row contains a treatment name that doesn't already exist in the database, create a new treatment record 
- [ ] 3. If a row contains a treatment name that does exist in the database, check if the descriptions match. If they match, this is an exact duplicate, skip and move on. If the descriptions do not match, raise an exception.
- [ ] 4. When loading animal/sample records, check to ensure that the treatment name on the row already exists in the database. If it does, use it, otherwise, raise an exception (just like missing tissue or compound records).
- [ ] Update the load_study command to be able to run this command, and accept this as part of the YAML study definition

### Limitations

- Loading of animals and samples does not need to check the names and descriptions in the worksheet, it can simply look for the treatment names on the animals sheet in the database.

### Affected Components

- add: `load_treatments` command
- change: `load_animals_and_samples` command
- change: `load_study`
- change: `load_study` YAML schema

#### Interface Change description

Describe changes to usage. *E.g. GUI/command-line changes*

#### Code Change Description

Describe code changes planned for the feature. *(Pseudocode encouraged)*

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by jcmatese** [comment]
@lparsons Regarding a specific definition/description for `no treatment` I see that small_obob_animal_and_sample_table.xlsx has a description "No treatment was applied to the animal.  Animal was maintained on normal diet (LabDiet #5053 "Maintenance"), housed at room temperature with a normal light cycle.
" which is different than the "inpiration", "no manipulation besides what is already described in other fields".  I assume this issue is really "create a command to load treatments based on the Treatments sheet of the Animals and samples template".  I can create a command to create treatments, or perhaps re-use existing names (or perhaps definition, preferably) or augment name with a date, if definition differs.  But I have no faith of actually getting everyone using the same protocol strings (given existing  different definitions of `no treatement` and similar "equivalent names like `control` );  we will need to enable protocol (attribute) editing on the web UI, long-term.

**Comment by lparsons** [comment]
@jcmatese Right now, there is simply no loading code that will load a description for treatment, afaik. Getting the lab members to use a consistent set of terms is certainly an issue, but one that is separate from this. To start with, we need a way to create a treatment with a specific description.

In our meeting last week you, I, and @hepcat72 discussed how to do this. There were a two options discussed:
1. A separate command used to create treatments. This would work similarly to compounds and treatments. As new studies are added, we would load new treatments as required and add them to a growing list of treatments. The code loading the animals and samples would then require that a treatment record be found that matches what was given in the spreadsheet.
2. Load the treatments as part of the animals and samples spreadsheet. This is how things work now, except that we would add some code to look for the treatment description in a separate worksheet.

I can see benefits to either method, but during the meeting there was a preference for option 2 presented since it seemed simpler (fewer commands, etc.). If, after further thought, you would prefer to implement the first option, I think that would be fine.

Regardless of the approach taken, we can and should address the use of consistent naming and protocols by the lab.

**Comment by jcmatese** [comment]
@lparsons How would you wish the following "error" to be handled?

```
raise LoadingError(f"Errors during protocol loading :\n {message}")
DataRepo.utils.exceptions.LoadingError: Errors during protocol loading :
 Error in row 1: ['Protocol with name = \'no treatment\' but a different description already exists: Existing description = \'For protocol\'s full text, please consult Xianfeng Zeng.\' New description = \'No treatment was applied to the animal.  Animal was maintained on normal diet (LabDiet #5053 "Maintenance"), housed at room temperature with a normal light cycle.\'']
```

Munge the new name by appending a timestamp (filename origin?) or other semi-unique postfix? [note: this pops up when executing `python manage.py load_study_set tracebase-rabinowitz-data/study_set_list.txt` ]  I guess with a timestamp, the protocol would never get re-used, which is probably _not_ what we want.  Could pass a filename postfix (straightforward) or _possibly_ a researcher (`load_samples_and_animals` does not have that as an argument, but presumably you could dig around in the file for it?)

**Comment by jcmatese** [comment]
As per discussion in the meeting, we will just raise that error, and **_not_** automatically modify the name.

**Comment by jcmatese** [comment]
Discussion directives:
- Remove auto-insertion code from animal sample loader (historical)
- No updates on the fly
- No insertions as a part of animal sample loading command (PR)
- Curators will copy paste protocols from the treatment sheet into a master list (and/or a study-specific list), and load, prior to loading animals/samples
