### ISSUE TITLE
Update display of Infusates

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#541]
### Inspiration

When displaying Infusates, there is a lot of information to convey, but we also want to make it as accesible as possible for researchers.

### Description

Include the following columns when displaying Infusates. Put the columns next to each to guide the reader.
* Infusate - Use the Infsuate group name if defined, otherwise, the long infusate name
* Tracer(s) - A list of the tracers in the infusate
* Tracer Concentration(s) - A list of the tracer concentrations in the infusate

### Comment

-----

### Assumptions

- List of assumptions that the code will not explicitly address/check
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected Components

A tentative list of anticipated repository items that will be changed, labeled
with "add", "delete", or "change".  One item per line.  (Mostly, this will be a
list of files.)

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

#### Interface Change description

Describe changes to usage. *E.g. GUI/command-line changes*

#### Code Change Description

Describe code changes planned for the feature. *(Pseudocode encouraged)*

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by hepcat72** [comment]
I was implementing this for the advanced search formats and I'm unsure about a few things:

> Include the following columns when displaying Infusates. Put the columns next to each to guide the reader.

I presume this means I should add columns to the download formats as well?

> - Infusate - Use the Infsuate group name if defined, otherwise, the long infusate name

- By `long name`, do you mean the name that includes everything (tracers, labels, and concentrations)
- Should the download formats always use the long/full name?
- Should the long/full name always be used for sorting even if we're only displaying the tracer group name, so that the first tracer sorts with other tracers without tracer group names?

> - Tracer(s) - A list of the tracers in the infusate

- So in most cases of single tracer infusates, the tracer and infusate columns will appear identical, or am I missing something?

> - Tracer Concentration(s) - A list of the tracer concentrations in the infusate

- If there's no tracer_group name, the concentration will appear in 3 columns.  Do I have that right?

- Lastly, just to confirm: no TracerLabel column.

**Comment by fkang-pu** [comment]
The questions @hepcat72 asked make me think if I got it right for sample_list page. @lparsons, could you take a look at [sample list page (](https://tracebase.princeton.edu/DataRepo/samples/)e.g. search 6EAAs for infusate) to see if the layout is what you expect. If ok, I will use same format and order for infusate/tracer related columns.

**Comment by lparsons** [comment]
> I presume this means I should add columns to the download formats as well?

Yes, add the columns to both the display and download formats.

> * By `long name`, do you mean the name that includes everything (tracers, labels, and concentrations)

The infusate long name is the complete (unique) name. If there was a short, though less unique, name, that might be preferable, but for now, this is what we decided in our discussion.

> * Should the download formats always use the long/full name?

When downloading, I would not want to omit the infusate group name, I would keep it the same as the display. The long infusate name is simply a concatenation of other columns and thus, if we replace it with the group name, nothing is really lost.

> * Should the long/full name always be used for sorting even if we're only displaying the tracer group name, so that the first tracer sorts with other tracers without tracer group names?

I would think that sorting based on something that isn't displayed (the long name) would be confusing. Sort based on the displayed name.

> * So in most cases of single tracer infusates, the tracer and infusate columns will appear identical, or am I missing something?

The tracer column would not have the concentration appended.

> * If there's no tracer_group name, the concentration will appear in 3 columns.  Do I have that right?

No, the concentration is appended to the infustate string, but is not part of the tracer column.
 
> _EDIT: Actually, I think that Tracer.name doesn't include concentrations, so it will appear in 2 columns._

Correct.

> * Lastly, just to confirm: no TracerLabel column.

I don't think there is a need to remove columns that are already there, but I suppose if it's not being shown now, then we don't have to add it.

**Comment by lparsons** [comment]
> The questions @hepcat72 asked make me think if I got it right for sample_list page. @lparsons, could you take a look at [sample list page (](https://tracebase.princeton.edu/DataRepo/samples/)e.g. search 6EAAs for infusate) to see if the layout is what you expect. If ok, I will use same format and order for infusate/tracer related columns.

It looks good to me, at least this is what I recall from our discussion and my notes.

**Comment by hepcat72** [comment]
OK.  I do recall these discussions BTW, but getting into the depth of it made me question whether I understood things right.  Oh, and I was thinking I would include a tooltip with the full name.
