### ISSUE TITLE
Link to updated upload template

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#544]
### Problem

The link to the Google Sheets template on the upload page is old and does not use the new column headers

### Steps to reproduce

1. Upload menu
2. Create a Sample Sheet
3. [Copy](https://docs.google.com/spreadsheets/d/1To3495KxJkAtnAD9KVdzc162zKbNiYuPEVyPseQPjMQ/copy?copyComments=true) the TraceBase Animal and Sample Table Template.

### Current behavior

The link makes a copy of the old template.

### Expected behavior

Use the updated template: https://docs.google.com/spreadsheets/d/1ywj9BvwX76ygRc5iXHwmzBcg1CWc5eFjLGOC6NtSHo8/copy?copyComments=true

### Comment

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected Components

A list of repository items, dependencies, etc, labeled with add, delete, or
change.  One item per line.  (Mostly, this will be a list of files.)

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

#### GUI Change description

Describe changes the user will see.

#### Code Change Description

Describe code changes planned for the feature. *(Pseudocode encouraged)*

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by lparsons** [comment]
@fkang-pu I'll go ahead and take this, should be a simple URL swap...

**Comment by fkang-pu** [comment]
Nice. Thanks.
