### ISSUE TITLE
Run all tests

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#549]
### Inspiration

Multi-label and mulit-tracer work is complete, all tests should be run.

### Description

Update GitHub action to run all tests. Remove unused tags from testing code (optional)

### Alternatives

none

### Dependencies

- #513

### Comment

none

-----

### Assumptions

- List of assumptions that the code will not explicitly address/check
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected Components

A tentative list of anticipated repository items that will be changed, labeled
with "add", "delete", or "change".  One item per line.  (Mostly, this will be a
list of files.)

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

#### Interface Change description

Describe changes to usage. *E.g. GUI/command-line changes*

#### Code Change Description

Describe code changes planned for the feature. *(Pseudocode encouraged)*

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by hepcat72** [comment]
I haven't yet looked at Fan's latest updates.  Did she fix the remaining broken tests?

**Comment by lparsons** [comment]
> I haven't yet looked at Fan's latest updates. Did she fix the remaining broken tests?

I'm not sure, but this can certainly wait until after the soft launch for the lab members.

**Comment by lparsons** [comment]
Yes, this is a required priority for the Production Release, which is scheduled for early Nov.

**Comment by hepcat72** [comment]
Oh OK.  I could have sworn it was in the soft-launch milestone. Sorry about that.
