### ISSUE TITLE
Add a `--defer-rollback` option to the protocols, tissues, and compounds load scripts for use by `load_study` to prevent errors about missing records

### ISSUE THREAD

**Issue by hepcat72** [Princeton-LSI-ResearchComputing/tracebase#577]
## FEATURE REQUEST

Updated this issue to better reflect the current state of the codebase. See the `PREVIOUS FEATURE REQUEST` section below for the original details.

### Inspiration

Similar to the way the loading of the accucor data needs the sample sheet data to be loaded/present for the load to succeed, the loading of the sample sheet data needs the tissues, compounds, and protocols to be present, in order for the load to succeed.

The protocols loader is run inside an atomic transaction, and when in validate mode - you don't want to change the database, so its changes are not retained.  When the sample sheet is attempted to be loaded, the novel tissues, protocols, and compounds are absent, thus you get an error.

There is now a separate protocols load command that loads both animal treatments and MSRun protocols.  The loads run in the validation view will raise an error about missing or inconsistent protocols when **adding** new animal treatments in the animal/sample xlsx sheet.

### Description

This has already been solved in the instance of sample data being retained in order for the accucor data to not raise any errors about missing samples, and that is the same (and simple) solution that should be employed here.  All of the scripts already have a `--validate` flag, and in the context of each individual script, it needs to roll back the changes from the load.  What we need to also do, is, from the `load_study` script, we must tell the child script (`load_protocols`) that we will handle the rollback for it, so that it *should* leave the data changed upon exit, because `load_study` also runs everything within its own atomic transaction context.  We just need to add the same options to `load_protocols`, `tissues`, etc.: `--defer-rollback`.

### Dependencies

None

### Comment

None

## PREVIOUS FEATURE REQUEST

> ### Title
> 
> Include checks on protocols (and tissues?) in the validation view
> 
> ### Description
> 
> Modify the code in such a way that valid novel protocols do not raise an error but when a protocol is inconsistent (e.g. name matches but descriptions mismatch), the load scripts raise a useful error/exception.  This must be done in a sustainable way too, so that the validation database is left in the same state it was in before the validation.
> 
> ### Alternatives
> 
> There are a few alternative that have been discussed:
> 
> 1. Run the protocols load on the validation database (using the animal/sample spreadsheet as input) as a part of the validation (being careful to not leave the validation database modified at the end)
> 2. Change the paradigm to always populate tissues, compounds, and protocols for a validation run and run the protocols load on the validation database (using the animal/sample spreadsheet as input) (clearing the entire validation database each time)
> 3. Treat the protocol loads like tissues and compounds so that when we as curators run it, it keeps the protocols synched in the validation database.  Then modify the sample table loader to not stop when it encounters a missing protocol, but report the errors to be presented to the user (i.e. buffer the errors and issue them at the end).  This is the easiest fix, but it means that users would see protocol errors on all novel protocols.
> 
> There may be other options...
> 
> John and I discussed it in the comments below and are favoring option 2.  One question that remains is: do we copy data from the default database each time or just run the consolidated protocol loads from files (and the protocol load script on all projects).  If the copy from the default database is straightforward, I'd opt for that.
> 
> ### Dependencies
> 
> - #581
> 
> ### Comment
> 
> The comment from the PR that triggered the creation of this issue:
> 
> I agree.  And we could create an issue that handles it in 1 or 2 ways.  Either [the sample table loader could make a treatments-tab-aware check](https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/538#discussion_r1005885013) so that no change to the validation code is necessary, or the the validation view can run the protocol loader on the submitted sample excel file before running the sample loader code, using the same design pattern of running the sample table loader before the accucor loader.  I'll reference this in a new issue.
> 
> _Originally posted by @hepcat72 in https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/538#discussion_r1005935218_
> 

-----

### Assumptions

- List of assumptions that the code will not explicitly address/check
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected Components

A tentative list of anticipated repository items that will be changed, labeled
with "add", "delete", or "change".  One item per line.  (Mostly, this will be a
list of files.)

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

#### Interface Change description

Describe changes to usage. *E.g. GUI/command-line changes*

#### Code Change Description

Describe code changes planned for the feature. *(Pseudocode encouraged)*

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by jcmatese** [comment]
as "features I think would be nice", is if the validator finds any new compounds, tissues, or protocols that it might list them out or reformat them for potential insertion, later (like a "make a standard study directory with loading files + standardized yaml")

**Comment by hepcat72** [comment]
That would be a feature of the loading code.  All the validation code does is it runs the loading scripts and reports its errors.  Though it does go to some effort to pretty-up the output.  And I think it should remain that simple.

**Comment by hepcat72** [comment]
Note that if a treatment doesn't exist in the database, the validation will include an error like the following:

<img width="1275" alt="without_loaded_treatments" src="https://user-images.githubusercontent.com/2300532/199107874-ea447d88-ecb6-42b6-adf0-67e2d0fe1616.png">

If the protocol is a standard one that has been loaded, e.g.:

```
python manage.py load_protocols --protocols DataRepo/example_data/small_dataset/small_obob_protocols.tsv
```

it will pass:

<img width="619" alt="quick_fix_passes" src="https://user-images.githubusercontent.com/2300532/199108151-64d8f6b0-2aed-4c57-9efa-b9aaa5f20302.png">

**Comment by hepcat72** [comment]
I believe that we will also at least have an inconsistency/issue WRT default protocols whose description mentions the researcher.

**Comment by jcmatese** [comment]
One thing that the validator _might_ try is a call_command to `load_protocols --protocols <submitted_animal_and_sample_table.xlsx> --database=validation` prior to the sample animal loading attempt into validation.  If the protocol is encoded in the xlsx, and successfully loads into validation database, then the treated animals might be able to load, too.

**Comment by hepcat72** [comment]
That's exactly what I was thinking John, so I wonder about the consolidated load factor. Any new entries have to be consistent with previous loads, so I think we need to both load what's in the file and pre-load the consolidated protocols.

**Comment by jcmatese** [comment]
I think where I would (potentially) like to be is that the validation database is empty all the time (no script loads both databases, by default) , but _**when you want to validate**_, you :

1. sync the current list of selected models (compounds, tissues, protocols) from production to validation, [so some novel method that replicates a table/models from one database to the other, one-way, to validation]
2. select the (putative/future?) validator router, 
3. try loading all to validation (capturing feedback), 
4. then init that validation database clean again. 
5. select the (putative/future?) production router (unless there is no cause to worry about database routing changes between processes; I don't know how it works)

Haven't given it much thought, though...

**Comment by hepcat72** [comment]
I think that's a good plan. I have had similar thoughts. Because the problem with loading the protocols in the submitted file and having the consolidated protocols pre-loaded, is that the clean up cannot just empty the protocols table. But I think if, like you suggest, we load compounds, tissues, and protocols with each validation, it makes the load scripts simpler and it solves the problem of cleaning out the table after a validation is performed. So I think you're right, that is the way to go.

**Comment by hepcat72** [comment]
I'm looking through this issue.  It is at least partially outdated, perhaps even fully implemented? It references the validation database, which is gone.  And the validation view now uses `load_study`, which loads both tissues and protocols. My only question I want to answer before closing is if the spirit of this is implemented: checks and handling of errors related to those data...
