### ISSUE TITLE
User Data Validation Improvement

### ISSUE THREAD

**Issue by hepcat72** [Princeton-LSI-ResearchComputing/tracebase#580]
### Inspiration

From learning about cross-database relation exceptions and the difficulty surrounding using multiple databases (i.e. the validation database) to handle load scripts with side-effects, we discover we have a choice to make on how to handle the validation of data without committing that data to the database.

Manually including `.using(db)` clauses introduces undesirable overhead, and turns out to have challenges relating to instance methods that make new queries (e.g. any method that makes a call like `Model.objects...`).    Those fresh database queries will get the default database even though the object containing the method was created using a query to the validation database.

In learning about how to handle this, it was discovered that you can override Django's default "database router" by creating your own derived class that overrides its 4 methods.  This would make all the usages of `.using(db)` clauses unnecessary.  All you would have to do is tell the router to direct queries to the validation database.

However, the only reason we're using a second database in the first place is 2-fold:

- The load scripts have side-effects (i.e. the dry-run/debug mode makes changes to the database).
- Subsequent load script runs depend on the previous runs having committed their data to the database.

There's also the issue of the load scripts stopping mid-load, causing the user to have to run the validation iteratively to learn of each issue 1 by 1, so either way, the load scripts need to be refactored.

### Description

The choices for implementation are:

1. Implement a database router (and remove all the .using(db) clauses and any customized code to work around other issues, like calls to the method in MultiDBMixin [in a coming quick-fix PR])
2. Refactor the load scripts to not have database side-effects, then refactor the validation view to wrap all the load scripts in an atomic transaction

### Alternatives

See the description.  A choice needs to be made before this issue can proceed.

### Dependencies

none

### Comment

A PR with a quick fix is coming.  There is a [stack post](https://stackoverflow.com/questions/74241257/how-to-override-model-init-and-respect-usingdb-in-django) that goes into more detail about the cross-db relations and possible solutions.

The database router solution *should* make it unnecessary to put calls to full_clean behind a conditional so that it only runs when the database is the default database.

-----

### Assumptions

none

### Requirements

This will be broken down into phases per load script to produce PRs that are more readily consumable.  Each phase should be accompanied by new and all-working tests.

- Phase 1
  - [x] 1. Load scripts generate as many actionable errors as possible in 1 run
  - [x] 2. If a load action in the script requires input involved in a previous error, skip that load action
  - [x] 3. Make it possible to control the verbosity of the loads
  - [x] 4. Raise error on unknown headers
- Phase 2
  - [x] 5. Make it possible to defer mass auto-updates outside of the load scripts (so it can be run by either load_study or load_study_set)
- Phase 3
  - [x] 6. Dry-run mode has no database side-effects when there's an exception or when run in dry run mode (and specifically when not run in `--validate` mode)
    - [x] 6.1. Wrap loading code in an atomic transaction
- Phase 4
  - [x] 7. Validation page works by running in dry-run mode on the main database
- Phase 5
  - [x] 8. Remove the validation database
    - [x] 8.1. Remove `.using(db)`, `.save(using=db)`, and `if self.db == settings.TRACEBASE_DB: rec.full_clean()`
    - [x] 8.2. Revert database settings
    - [x] 8.3. Update docs
- Phase 6 **OPTIONAL**
  - [x] 9. Add the ability to run load_study inside the validation interface instead of just individual loaders

### Limitations

none

### Affected Components

- change: `DataRepo/management/commands/load*`
- change: `DataRepo/utils/*load*`
- change: `Tracebase/settings.py`

#### Interface Change description

No changes in user experience other than receiving more errors in 1 run on the validation page.  The --database and --validate options will go away on the command line.  --debug will change to --dryrun.  An option to disable auto-update will be added.

#### Code Change Description

The load scripts will be changed to buffer all errors in a self.errors array attribute.  Different model loads will be encapsulated in methods, with required inputs (some of which may require successful prior model loads).  If a required input is from a previous failed model load, the model load is skipped so as to not output useless errors.  There will be a new requirement to report unrecognized (optional) headers as an error.

#### Tests

- [x] `1.` Load scripts generate as many actionable errors as possible in 1 run - test that self.errors can contain multiple errors
- [x] `2.` If a load action in the script requires input involved in a previous error, skip that load action - test that (e.g.) a tissue error will not be followed by a sample error in the same run
- [x] `3.` Make it possible to control the verbosity of the loads - unnecessary test
- [x] `4.` Raise error on unknown headers - input a bad header for an optional column and check that an error about it is raised
- [x] `5.` Make it possible to defer mass auto-updates outside of the load scripts (so it can be run by either load_study or load_study_set) - Try deferring auto-updates using the new option and check that the buffer is populated after the run
- [x] `6.` Dry-run mode has no database side-effects (when not run in `--validate` mode) - test unnecessary (see 6.1)
  - [x] `6.1.` Wrap loading code in an atomic transaction - Run a successful load and check that nothing in the DB has changed
- [x] `7.` Validation page works on the main database - existing tests should suffice
- [x] `8.` Remove the validation database - tests unnecessary
  - [x] `8.1.` Remove `.using(db)`, `.save(using=db)`, and `if self.db == settings.TRACEBASE_DB: rec.full_clean()` - tests unnecessary
  - [x] `8.2.` Revert database settings - tests unnecessary
  - [x] `8.3.` Update docs - tests unnecessary
- [x] `9.` Add the ability to run load_study inside the validation interface instead of just individual loaders

**Comment by hepcat72** [comment]
I've been reading about Django's database routers this morning on stack and in the django docs:

- [Multiple Databases in Django 3.2](https://docs.djangoproject.com/en/3.2/topics/db/multi-db/)

It looks like the database router class may not be well suited for having a **process** temporarily use a different database.  It looks like it's for having different models use different databases.  I wondered about possibly creating either a class variable or an instance variable to use to switch databases, but I don't think a class variable would be restricted to just the validation view load script runs, and an instance variable would have to be set for every model object involved (which is back to the same annoying need for having `.using(db)` everywhere...

So I'm leaning toward a refactor to accomplish a few things:

- Gather as many errors as possible to spit back in 1 run, to cut down on the need for successive runs
- Make dry-runs not have any side-effects
- Adjust methods to allow things to run inside an atomic transaction block (so that there aren't exceptions about queries being performed)
- Turn off auto-updates during a dry run of multiple scripts and perform buffered autoupdates once they leave the atomic transaction block

I have a post in the Django forum asking about routers and if they can handle our use-case, because this refactor would be a much larger undertaking in comparison.  If the database router could fix the issues with multiple databases, I think it would be a relatively small effort.  And someone replied while I was composing this comment.  He said you **can** accomplish the goal of a separate database, but by launching a separate task (e.g. using celery) that is configured to use a different database.  He confirmed my doubts that a database router could do this.  And knowing how much overhead there is associated with tasks/celery, I think that we should go the refactor/atomic-transaction route.

**Comment by hepcat72** [comment]
The separate database strategy could still work, but it would require that the load scripts don't call model methods that make fresh queries...  And I also don't know how to deal with full_clean.  Either way, a refactor would be necessary to at least better consolidate errors for users.

**Comment by jcmatese** [comment]
Definitely leaning towards a refactor that removes the extra validation database, if the router is not process specific.  Fills me with unease that I don't know what database I might be addressing (or that it could switch, depending on the context).

**Comment by hepcat72** [comment]
Yeah, I have similar concerns.  That's why I edited my latest PR to comment out the link to the validation page.  Though the guy on the Django forum did say that you can make it process-specific by launching a new process with a separate settings file.  That would certainly be quicker than a refactor, but I feel like there are other advantages to a refactor as well, so I started trying out a small refactor to at least buffer "some" errors in the sample loader.

**Comment by hepcat72** [comment]
- ToDo, phase 4
  - [ ] Add test for when accucor cannot run (maybe if there's is at least 1 exception from sample table loader and an exception for every row/sample in the accucor file, clear out the errors and set state to UNCHECKED)
  - [ ] Catch the ValidationError exceptions that happen where there are duplicate compound/label count issues and ignore them, so processing may proceed
  - [ ] Add test to ensure user can proceed to submit when there are only warnings
  - [ ] Add test to ensure submission link is not presented when there are errors in the sample sheet
  - [ ] Add test to ensure submission link is not presented when there are errors in any accucor file
  - [ ] Add tests to ensure the database doesn't change
  - [ ] See if I can include proper tracebacks in the aggregated exceptions (current work-around is saving it as a string in `exception.tb_str`).  Might need to always do a raise/except everywhere.
  - [ ] **OPTIONAL**: Move the cull_warnings and buffer_exception methods to a `TraceBaseLoader` superclass

**Comment by hepcat72** [comment]
Incidentally, regarding the "proper tracebacks" item in the TODO list above, I gained insight into tracebacks this morning that I didn't understand before.  A traceback isn't created at the creation of the exception object. It's not created at the moment it's raised.  And it's not created when it's caught.  It's built from the bottom up, as the exception travels up the stack, thus it stops being built when it's caught.

I guess I never really thought about it before. To me, it was a black box.  I think I implicitly assumed that when the exception object was constructed, it constructed the whole traceback, and that when you caught an exception, it sliced the difference between the exception point and the catch.  And I never scrutinized my assumption.  I don't think I ever even knew I was assuming it.  And I think I was applying my knowledge of the `caller()` function in perl, which I understood(/assumed?) to keep a constant record of the call stack.

I gained this insight thanks to the person who [answered](https://stackoverflow.com/a/75291685/2057516) my stack question about why I wasn't getting the full traceback when I buffered an exception.  He was spot on in understanding the (implicit) assumption I was making.

**Comment by hepcat72** [comment]
After running the new cold exposure data through the dev validate interface in my sandbox, I have a few things I want to address.  Perhaps I'll do this in phase 4.5...

- [ ] Figure out the reason behind an empty sample name in DuplicateValues errors and create a specific error
- [ ] Study names in the DuplicateValues error are broken - fix
- [ ] Simplify sample name report - Including study name this way is confusing
- [ ] Filter units from infusion_rate values and issue a warning when they're included
- [ ] Create a separate file input for isocorr files
- [ ] Line break missing samples and duplicate Isotopes
- [ ] Label the atom counts in the dupe isotopes error for clarification
- [ ] Make more informative Dupe MSRun errors
- [ ] Report MissingSamplesError in the context of the sample file instead of database
- [ ] Create MissingCompounds error that lists the compounds

**Comment by hepcat72** [comment]
So it turns out that the MAX_LABELED_ATOMS has to be the max number of atoms in the compound with the most atoms that have a label applied.  In the cold exposure data, that was `fatty acid C34:1`, which has a formula of `C34H66O2`. So I should:

- [ ] Create a specific exception that reports the issue described above and it should include the formula, and why it's creating a record with a label count higher than `MAX_LABELED_ATOMS`.  It should catch this case:
> ValidationError: {'count': ['Ensure this value is less than or equal to 30.']}

**Comment by hepcat72** [comment]
All of the todo items in the comment above are now complete.  There remain a couple of housekeeping items I want to keep in mind as I move on to phase 5:

- [ ] Run the original Cold Exposure data through to make sure everything is handled correctly
- [ ] Wrap ValidationsErrors, IntegrityErrors, and all unanticipated exceptions in a generic exception that indicates the row of the input file where the exception was encountered and the data on that row.  It should also suggest creating a custom exception.
- [ ] Make a final pass on the code changes to remove debug prints, commented code, and fill in any docstrings where methods are not entirely clear

**Comment by hepcat72** [comment]
- [ ] Improve `ExistingMSRun` to not list samples if all samples in common with another accucor/isocorr file account for all samples in the current accucor/isocorr file

**Comment by hepcat72** [comment]
New changes in #678 were previously overlooked.  Re-opening.
