### ISSUE TITLE
Fix code for data frame to handle null values for infusate and tracer names

### ISSUE THREAD

**Issue by fkang-pu** [Princeton-LSI-ResearchComputing/tracebase#585]
## BUG DESCRIPTION

Based on current database specifications, infusate.name and tracer.name allow null values. The dataframe code used for study list and animal list would  have errors if some values are null.

### Problem

The root problem is due to group by "name" field. Pandas would return an empty dataframe if the field contained null values.  [PR576](https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/576) modified some data frame code but didn't address root cause. 

### Steps to reproduce

Will link to a test case later

### Expected behavior

Although infusate.name and tracer.name should be not null with normal data loading, but the code should handle null values based on current spec. and allow tests with different settings (e.g. enable_buffering or disable_buffering). 

### Suggested Change

The code for infusate related data frames need to join id and name fields first and then run "groupby".

### Comment

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected Components

A list of repository items, dependencies, etc, labeled with add, delete, or
change.  One item per line.  (Mostly, this will be a list of files.)

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

#### GUI Change description

Describe changes the user will see.

#### Code Change Description

Describe code changes planned for the feature. *(Pseudocode encouraged)*

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by hepcat72** [comment]
👍
