### ISSUE TITLE
PeakGroup name parsing and compound validation

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#61]
### Feature Inspiration

`PeakGroup` names are generally the name of the associated compound, but sometimes are actually the names of multiple compounds.

### Feature Description

A method for parsing these "combined names" should be part of the PeakGroup class to keep that logic together and allow reuse. Compounds that associated with the PeakGroup should have names that match those parsed from the "combined name" and be checked by validation. 

Both `Compound` and `PeakGroup` have a `formula` attribute, which in principle should match. There should be some validation to ensure that the `PeakGroup.formula` matches each of the `Compound.formula` values for associated `Compound`s.

#### Design suggestion

* A `PeakGroup` class method that returns a iterable of individual compound names based on the provided string.
* Validation that names and formulas between `PeakGroup`  and associated `Compound` records match.

### Alternatives Considered

none

### Comment

Some overlap with #68 

-----

### Assumptions

none

### Requirements

- User provided data files will be required to follow the format used by this parsing function for `PeakGroup` names.
- Edit the following comment once we've settled on the error behavior for non-mathcing / empty PeakGroup formulas:

https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/68469624485631fe8624d83a7090c2cccfe7b2c7/DataRepo/utils.py#L485-L488

- There should be some validation to ensure that the PeakGroup.formula matches each of the Compound.formula values for associated Compounds.

### Limitations

none

### Affected/Changed Components

- `PeakGroup` class

#### Tests

- Test that an empty formula in an insert into the PeakGroup table fails
- Test that a matching formula succeeds

**Comment by jcmatese** [comment]
Just adding a note here which came out of data loading testing of PR #55 , in case it affects validation decisions/strategies in this issue

PeakGroup formulas might get set as `nan`
https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/55#discussion_r627518449

**Comment by hepcat72** [comment]
This is essentially done.
