### ISSUE TITLE
Move PeakGroupSet (i.e. the filename) into MSRun and include it in the UniqueConstraint

### ISSUE THREAD

**Issue by hepcat72** [Princeton-LSI-ResearchComputing/tracebase#636]
### Inspiration

I was working on the accucor loader refactor and creating an exception class to explain the existing MSRun record `ValidationError`.  Doing so involved explaining why the error occurred (which is because the combo of `date`, `researcher`, `protocol`, and `sample` must be unique).  I recalled comments by John lamenting the fact that the date is usually tweaked to accommodate runs that happen on the same day with the same sample (by the same researcher and same protocol).  It also involved identifying the accucor/isocorr files that were the source of the conflict (whose dates must be edited), and I realized that the `PeakGroupSet.filename` is always associated with all the PeakGroups loaded from 1 file, even if it's the same PeakGroup loaded from another file.

Currently, PeakGroup links to both MSRun and PeakGroupSet in a M:1 fashion, and the relation from other contents in MSRun (Researcher, date, protocol) to PeakGroupSet.filename is always the same.  During the run of any instance of the accucor loader, there's only 1 researcher, 1 date, 1 protocol, and 1 filename.

### Description

If we move the filename from PeakGroupSet to MSRun (and delete PeakGroupSet), we could include it in the UniqueConstraint and not have to fudge dates to allow data to load.  This would of course duplicate the `filename`, but we already duplicate the date, researcher, and protocol, so what's 1 more CharField?

### Alternatives

1. MSRun could probably sit happily between Animal and Sample *OR*...
2. Sample could probably link to MSRun [in a M:M relation] instead of the other way around *OR*...
3. We could have a Sample-PeakGroup linking table (e.g. MSRun would only contain Sample and PeakGroup IDs) that also contains a link to an MSRunInfo record - so that `date`, `researcher`, `protocol`, and `filename` aren't duplicated for every sample.  After all, an MSRun (i.e. the running of the machine) defines a collection of samples.  The parameters like, researcher, date, protocol, and filename applies to every sample in the collection.

The latter 2 options (the third one being particularly appealing to me) would eliminate the need to using a sample name prefix.  The Sample table could have a single record for every sample that exists in reality and that Sample could be included in multiple MSRuns.

...but I'm not prepared to take it this far.  Putting filename in MSRun will just make things easier without need for fudging dates.

### Dependencies

none

### Comment

none

-----

### Assumptions

- List of assumptions that the code will not explicitly address/check
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected Components

A tentative list of anticipated repository items that will be changed, labeled
with "add", "delete", or "change".  One item per line.  (Mostly, this will be a
list of files.)

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

#### Interface Change description

Describe changes to usage. *E.g. GUI/command-line changes*

#### Code Change Description

Describe code changes planned for the feature. *(Pseudocode encouraged)*

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by jcmatese** [comment]
Unless we shuffle concepts and models relationships around, I think the file name you would _probably_ want in MSRUN would be the filename of the mzxml/raw file, not the accucorr/isocorr filename [unless you want to specify a filename plus column index(es) where the sample maps to].

**Comment by hepcat72** [comment]
> Unless we shuffle concepts and models relationships around, I think the file name you would _probably_ want in MSRUN would be the filename of the mzxml/raw file, not the accucorr/isocorr filename [unless you want to specify a filename plus column index(es) where the sample maps to].

That's a useful insight.  Though, would the inclusion of protocol possibly already account for that? TBH, I need a refresher on the relationships of the different files.  I think it's captured in that diagram I created early on in this project.

**Comment by hepcat72** [comment]
It also just occurred to me that if we make the relationship between MSRun:Sample a M:M relationship, we won't need to duplicate sample names using the prefix strategy.
