### ISSUE TITLE
Data Loader Tests

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#64]
### Problem

According to the contributing doc:

> All pull requests must implement tests of the changes implemented prior to being merged.

Tests were not implemented for PR #55.

There was also some discussion of our documented processes not allowing for alternate paths to implementing tests.

### Steps to reproduce

1. Run the tests associated with the changes in PR #55

### Current behavior

The following tests were implemented:

- Successful load of `DataRepo/example_data/obob_maven_6eaas_inf.xlsx`
- Successful load of `DataRepo/example_data/obob_maven_c160_inf.xlsx`

### Expected behavior

There should be a test for each requirement listed in issue #45.

### Suggested Change

Write tests for each of the requirements in the issue:

1. [ ] xlsx file (accucor format, required) `test that supplying the wrong file type or no file fails`
2. [ ] date required `test that fails when no date supplied`
3. test that protocol can be either an integer (protocol.id) or name, and is required
  - [ ] `test supplying protocol name succeeds`
  - [ ] `test that supplying protocol ID succeeds`
  - [ ] `test that not supplying a protocol fails`
4. [ ] researcher name `test for failure when no name supplied` (#67)
5. [ ] sample names are unique with the file `supply a file with a duplicate sample name & test for failure` (#66)
6. [ ] sample names must already be in the database `test for failure with a sample name not in the DB`
7. [ ] compound labels must already be in the database `test for failure with a compound not in the DB`

### Comment

There is no accommodation in the contrib doc for implementing tests *after* a PR is merged.  I feel that this is intentional because otherwise, testing often falls by the wayside.  No one likes to write tests, so no one is going to opt to take those issues.  There are always more important/interesting tasks to be done, however, not implementing tests can quickly lead to an endless and rigorous maintenance cycle.  Personally, I don't think that we should build in a mechanism for putting test creation off.  Even if we "know" right now that the code "works" - we don't know if it will work in the future if something changes.

I have changed this issue to a bug because skipping test implementation is a bug as it relates to the process we decided to adhere to, and *will* lead to problems down the road.  In my experience with software engineering, we were taught that bugs can be introduced in every phase of a project: planning, requirements gathering, design, implementation, and testing.  This issue spans planning, design, implementation, and testing.

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will not fix
- E.g. Getting edge case X to work requires too much effort and will not be
  fixed in this effort.

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the fix.

#### Tests

A test should be planned for each requirement (above), where possible.

### Feature Description

A brief description of *what* the feature should do (not *how* it will be done -
for that, jump down to the *Code Change Description* section below to make
suggestions).

### Alternatives Considered

A brief description of any alternative features that may accomplish the same
ultimate goal.

### Comment

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by hepcat72** [comment]
This issue is redundant to existing loader test issues for the loader refactor.
