### ISSUE TITLE
Remove `concentration` from the `InfusateTracer._meta.UniqueConstraint`

### ISSUE THREAD

**Issue by hepcat72** [Princeton-LSI-ResearchComputing/tracebase#652]
### Problem

The same `Tracer` could be added to an `Infusate` multiple times with different concentrations, but there should only exist 1 such link.

### Steps to reproduce

1. Observe that `InfusateTracer._meta.UniqueConstraint` has infusate, tracer, and concentration

### Current behavior

Code keeps multiple concentrations between Infusate:Tracer from being added currently, but future code or manual database commands could add them and not complain.

### Expected behavior

There should be a unique constraint IntegrityError if you try to add the same infusate & tracer with different concentrations.

### Suggested Change

Remove `concentration` from the `InfusateTracer._meta.UniqueConstraint`.

### Comment

Change the InfusateTracer `UniqueConstraint` to exclude concentrations.

See the PR thread for possible other related changes.

> Actually, I don't think we even need concentration in the uniqueconstraint...
>
> ```
>         constraints = [
>             models.UniqueConstraint(
>                 fields=["infusate", "tracer"],
>                 name="unique_infusate_tracer",
>             )
>         ]
> ```

_Originally posted by @hepcat72 in https://github.com/Princeton-LSI-ResearchComputing/tracebase/issues/650#issuecomment-1444285490_

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected Components

A list of repository items, dependencies, etc, labeled with add, delete, or
change.  One item per line.  (Mostly, this will be a list of files.)

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

#### GUI Change description

Describe changes the user will see.

#### Code Change Description

Describe code changes planned for the feature. *(Pseudocode encouraged)*

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by lparsons** [comment]
Resolved in #650, closing.
