### ISSUE TITLE
Ra table headings display the incorrect normalization method when Animal weight is missing

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#683]
### Problem

In the FCirc results for mice for which we have no weight, the "Mouse Normalized" column is `None` while the "Weight Normalized" column has a value. If a weight it missing, the weight normalized value should be missing, but the mouse normalized value should be able to be calculated. _Note:_ This only seems to happen when the animal weight is missing.

### Steps to reproduce

1. View FCirc table for `fluxomics 2020` study
2. See Ra values for a mouse with missing weight (e.g. [Animal Record - SH.fasted.[U-13C]sodium oleate.M2](https://tracebase.princeton.edu/DataRepo/animals/112/)

### Current behavior

The "Mouse Normalized" column is `None` while the "Weight Normalized" column has a value. 
![image](https://github.com/Princeton-LSI-ResearchComputing/tracebase/assets/645128/bd1ef978-0d84-4604-af91-2d2f6b92b907)

### Expected behavior

The weight normalized value should be missing, but the mouse normalized value should be able to be calculated.

### Suggested Change

Hopefully the problem is simply a mixed up header, but the values should be checked (weight normalized = mouse normalized / mouse weight)

### Comment

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected Components

A list of repository items, dependencies, etc, labeled with add, delete, or
change.  One item per line.  (Mostly, this will be a list of files.)

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

#### GUI Change description

Describe changes the user will see.

#### Code Change Description

Describe code changes planned for the feature. *(Pseudocode encouraged)*

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by hepcat72** [comment]
The calculation is based on infusion rate, not mouse weight?
```
Ra_avg_g = Rd_avg_g - [Infusate] * 'Infusion Rate' in nmol/min/g
```
That's where the `/g` comes from?

> Also referred to as Ra_avg_g, and sometimes referred to as Fcirc_avg.
> Equivalent to Rd_avg_g - [Infusate] * 'Infusion Rate' in nmol/min/g
> Calculated for the last serum sample collected, for the last tracer
> peakgroup analyzed.

What's the initial thing that prompted the correspondence from the user?

**Comment by hepcat72** [comment]
And the per animal calculation multiplies the per gram value by the animal weight to remove the grams:

```
self.rate_appearance_intact_per_gram * self.animal.body_weight
```

So the `None` values make sense.

**Comment by hepcat72** [comment]
So my question is... Is it just the `None` values that are prompting concern? If that's what it is, then there is no problem that I can tell.  If there is another reason to be concerned, I would need to know more to debug what the issue is.

Perhaps... is there a reciprocal way to calculate the per_animal value that doesn't require knowing the animal weight?

**Comment by lparsons** [comment]
Ugh. Sorry about the confusion, but you're totally right Rob. I'll close this this issue, but feel free to reopen if needed.
