### ISSUE TITLE
Study creation by existing commands

### ISSUE THREAD

**Issue by jcmatese** [Princeton-LSI-ResearchComputing/tracebase#69]
## FEATURE DESCRIPTION

Make (one or both) existing commands enter studies, on demand.

### Feature Inspiration

**Existing scripts**

[load_samples](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/DataRepo/management/commands/load_samples.py)
[load_accucor_msruns](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/DataRepo/management/commands/load_accucor_msruns.py)

Neither of these scripts have columns in their input files that define a study.  _However_, both of them could potentially make a study, associating the samples/animals they handle/process with a newly created study, with name, description either auto-generated based on file name or defined by optional arguments.

### Feature Inspiration

Tracebase is progressing to a point where having defined studies would be beneficial. Search (#22 , #47) and view (#49 ) interfaces will want to take that model/data into account.  To the best of my knowledge, we have not curated any provisional study records in the database.  Should we augment existing commands with an option to create a collective study, to facilitate the development of the other issues?

### Feature Description

Compile a list of animals for each sample handled by script and make a study from it, given a name/description.

### Alternatives Considered

You could wait for web search interface to provide an alternate input to a study creation action.

### Comment

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by lparsons** [comment]
I'm a bit confused, while I don't disagree that we could collect more detail, the sample loading also creates studies: https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/004468feba3ec253c5f5ff15869c3363beae0590/DataRepo/utils.py#L101-L114

**Comment by jcmatese** [comment]
Sorry, I was unaware this already existed.
