### ISSUE TITLE
Migration to link `MSRun` records to `LCMethod` records based on `Protocol` record links

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#703]
### Inspiration

~Copying `Protocol` records in the `msrun_protocol` category to the new `LCMethod` model class.~

We have `LCMethod` records that should correspond to existing `Protocol` `msrun_protocol` records.

### Description

~Create a [data migration](https://docs.djangoproject.com/en/4.2/topics/migrations/#data-migrations) that copies the records from `Protocol` to `LCMethod`. Since these will be previously loaded records, the Protocol name will need to be parsed to determine appropriate values. Use a `unknown` value for missing information (e.g. instrument).~

1. Add a foreign key in `MSRun` to `LCMethod` with `null=True` and automatically create a migration
2. Create a [data migration](https://docs.djangoproject.com/en/4.2/topics/migrations/#data-migrations) that sets the `LCMethod` foreign key in `MSRun` based on its existing link to `Protocol`. If the link cannot be determined, use use the `unknown` `LCMethod` record.

### Alternatives

Allow `NULL` for missing information.

### Dependencies

This issue cannot be started until the completion of the following issue(s):

- #702

### Comment

-----

### Assumptions

- List of assumptions that the code will not explicitly address/check
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected Components

A tentative list of anticipated repository items that will be changed, labeled
with "add", "delete", or "change".  One item per line.  (Mostly, this will be a
list of files.)

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

#### Interface Change description

Describe changes to usage. *E.g. GUI/command-line changes*

#### Code Change Description

Describe code changes planned for the feature. *(Pseudocode encouraged)*

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by jcmatese** [comment]
@mneinast for your study [MN_exp027e_acute KR infusion](https://tracebase.princeton.edu/DataRepo/studies/4/) which was loaded using "LC-MS, high-mz mode" and "LC-MS, low-mz mode" , would these both be migrated to some form of [polar-HILIC-25-min](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/c4b70402ce4df0bf1109006f80a3690dcdac0023/DataRepo/fixtures/lc_methods.yaml#L7-L15)?

I was just looking at the list of [production protocols](https://tracebase.princeton.edu/DataRepo/protocols/msrun_protocols/) , and was wondering if they should all be mapped to a single protocol , or whether some subset (like "[Default](https://tracebase.princeton.edu/DataRepo/protocols/14/)", three studies) needs to me mapped to "[unknown](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/c4b70402ce4df0bf1109006f80a3690dcdac0023/DataRepo/fixtures/lc_methods.yaml#L2-L6)"

**Comment by jcmatese** [comment]
[fluxomics 2020](https://tracebase.princeton.edu/DataRepo/studies/5/) with "Default" protocol [looks like it should map to HILIC](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7544659/#:~:text=Metabolite%20Measurement%20by,13C%20abundance.)

**Comment by jcmatese** [comment]
[ob/ob Fasted](https://tracebase.princeton.edu/DataRepo/studies/1/) which contains a "Default" protocol (somewhere), has 1091 msrun, with at least some being HILIC.  Could they all be HILIC (just loading differences)?  I was not able to easily query this in the web interface (I don't think `msrun.protocol.name` is queryable).

**Comment by hepcat72** [comment]
Invalid issue.  There is nothing to do to the database in a migration for this issue. The records are already created. Issue #704 modifies the MSRun model to create a foreign key into LCMethod.  Until that's done, there's nothing in the database to "migrate".

I think that this issue should be after #704.  #704 should ADD a foreign key to `LCMethod` and this issue should create a migration that sets links to `LCMethod` records based on existing links to `msrun_protocol`s.  **That's** when the migration can happen.  I can set my branch aside until #704 is done.
