### ISSUE TITLE
Update submission templates to ask for LCMethod information

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#705]
### Inspiration

Researchers should specify LC method information when submitting data. 

### Description

For each peak annotation file, researchers should specify:
* chromatographic technique (enum values defined by `LCMethod` class)
* run length (in minutes)
* description (optional)

### Comment

-----

### Assumptions

- Every peak annotation file is associated with a single Liquid Chromatography Protocol

### Requirements

- [ ] 1. Liquid Chromatography Method is required
- [ ] 2. Run Length is required
- [ ] 3. Description is optional

### Limitations

- This effort will not attempt to associate multiple different protocols per peak annotation file

### Affected Components

- [x] change: [Submission form](https://docs.google.com/forms/d/1Y2SEQgLTd8QUjbXGCuo3989WQxMfsfh4AbJyeL3f6c8/edit)
- [x] change:`TraceBaseDocs/TraceBaseDocs/Upload/How to Upload.md` _(which links to [LC Method instructions](https://docs.google.com/document/d/1Lm4br-jCB2QwbgPyzJvvgLgaO-t7Cwcq1xHyBIOlTog/edit/))_

#### Interface Change description

The nomenclature established in the design section of issue #704 will be used.

#### Code Change Description

Describe code changes planned for the feature. *(Pseudocode encouraged)*

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by hepcat72** [comment]
Incidentall, I edited a link in the submission form that was going to tracebase-dev instead of tracebase...
