### ISSUE TITLE
Create `MSRunSequence` model class

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#707]
### Inspiration

Part of the [TraceBase MS Data Storage Model](https://docs.google.com/document/d/1CUg1fChG3ZEHgMcLZnzq5eRDxiixhhH5quELHXjLIRc/edit?usp=sharing)

### Description

Create a model class `MSRunSequence` with the following fields:
* `id` PK int
* `researcher` string
* `date` date
* `instrument` enum (HILIC, QE, QE2, QTOF)
* `lc_method_id` int FK >- `LCMethod.id`
* `notes` string NULL

![image](https://github.com/Princeton-LSI-ResearchComputing/tracebase/assets/645128/57bd3031-1a56-4686-8344-fe383427d297)

### Alternatives

Use a separate model class to store instruments. This would make it simpler to change the list of instruments using the admin interface which would be especially useful for other labs.

Use a config file to determine instrument choices. Possibly simpler and lighter weight that using a model class.

### Dependencies

This issue cannot be started until the completion of the following issue(s):

- #700 

### Comment

-----

### Assumptions

- List of assumptions that the code will not explicitly address/check
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected Components

A tentative list of anticipated repository items that will be changed, labeled
with "add", "delete", or "change".  One item per line.  (Mostly, this will be a
list of files.)

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

#### Interface Change description

Describe changes to usage. *E.g. GUI/command-line changes*

#### Code Change Description

Describe code changes planned for the feature. *(Pseudocode encouraged)*

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by hepcat72** [comment]
I think that all this needs is for #702 to have been implemented, so I should be able to knock this out.

**Comment by mneinast** [comment]
@lparsons and @hepcat72 These are the valid instrument names for the Rabinowitz lab:

QE, QEplus, QE2, Exploris240, Exploris480, ExplorisMX
