### ISSUE TITLE
Update initial LCMethod records

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#728]
### Inspiration

The initial LCMethod records are placeholders. They should be updated to ones vetted by the lab.

### Description

Initial LCMethod records:

| Name | Type | Run Length | Description |
| --- | --- | --- | --- |
| polar-HILIC-25-min | polar-HILIC | 00:25:00 | “Polar-HILIC-HRMS”: this method involves the analysis of polar metabolites using HILIC on Waters Amide columns with basic buffer, coupled with high resolution mass spectrometry. |
| polar-reversed-phase-ion-pairing-25-min | polar-reversed-phase-ion-pairing | 00:25:00 | “Polar-Reversed-phase-ion-pairing-HRMS”: this method involves the analysis of polar metabolites using reversed-phase ion pairing chromatography on C18 columns, coupled with high resolution mass spectrometry. It provides good separation and detection for polar metabolites in negative ion mode, in particular phosphate metabolites. |
| polar-reversed-phase-25-min | polar-reversed-phase | 00:25:00 | “Polar-Reversed-phase-HRMS”: this method involves the analysis of polar metabolites using C18 columns with acidic buffer, coupled with high resolution mass spectrometry. It is mainly used for the analysis of amino acids and derivatives. |
| lipid-reversed-phase-25-min | lipid-reversed-phase | 00:25:00 | “Lipid-Reversed-phase-HRMS”: this method involves the analysis of lipids using reversed-phase chromatography on C18 columns, coupled with high resolution mass spectrometry. It is mainly used for the analysis of lipids. |

These methods and descriptions were are the procduct of @mneinast and Wenyun Lu <wlu@princeton.edu>
from the Rabinowitz Lab.

### Comment

-----

### Assumptions

- List of assumptions that the code will not explicitly address/check
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected Components

A tentative list of anticipated repository items that will be changed, labeled
with "add", "delete", or "change".  One item per line.  (Mostly, this will be a
list of files.)

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

#### Interface Change description

Describe changes to usage. *E.g. GUI/command-line changes*

#### Code Change Description

Describe code changes planned for the feature. *(Pseudocode encouraged)*

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by jcmatese** [comment]
I can start this, and perhaps add in the model export tweaks suggested during the model review (pk exports, and whatnot)...
