### ISSUE TITLE
Update postgres

### ISSUE THREAD

**Issue by hepcat72** [Princeton-LSI-ResearchComputing/tracebase#729]
### Inspiration

Django 4.2 requires at least postgres 12 and we currently are using 10.8.

### Description

Update postgres on the production and development servers to at least 12, possibly up to the latest stable release.

### Alternatives

None

### Dependencies

None

### Comment

I'm (Rob) running 13.4 on my machine, so I know there are no issues there.  My "check for updates" says I can upgrade to 13.11, but we should probably check that the version we use is compatible on developer workstations.

-----

### Assumptions

- List of assumptions that the code will not explicitly address/check
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected Components

A tentative list of anticipated repository items that will be changed, labeled
with "add", "delete", or "change".  One item per line.  (Mostly, this will be a
list of files.)

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

#### Interface Change description

Describe changes to usage. *E.g. GUI/command-line changes*

#### Code Change Description

Describe code changes planned for the feature. *(Pseudocode encouraged)*

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by lparsons** [comment]
I believe that TraceBase works fine with an newer PostgreSQL versions, though updating the GitHub actions to test with it would be good. We could perhaps update the CONTRIBUTING.md and certain the GitHub tests. That could be done as part of #721.

Our current instance of TraceBase however, is running with an older OS which needs some updating to accomodate recent PostgreSQL versions. That effort is being tracked in a ticket: `[gen-help.princeton.edu #57516] Update Postgres on tracebase-dev and tracebase`.

**Comment by lparsons** [comment]
Tracebase-Dev at https://tracebase-dev.princeton.edu is now running CentOS9, updated Postgres, and Python 3.9.

**Comment by lparsons** [comment]
Resolved in #724 and [RT #57516](https://gen-help.princeton.edu/Ticket/Display.html?id=57516).
