### ISSUE TITLE
Task: Develop plan to serve static files in production

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#732]
We can use Django to serve ArchiveFiles in development, but a different strategy should be employed in production. Work with the sys admins to determine the appropriate strategy for tracebase and get it setup and tested in dev prior to implemeting it in production.

* [Serving files uploaded by a user during development](https://docs.djangoproject.com/en/4.2/howto/static-files/#serving-uploaded-files-in-development)
* [How to deploy static files](https://docs.djangoproject.com/en/4.2/howto/static-files/deployment/)

Outline of tasks
* [x] Configure development server to store and serve files from `tracebase-archive` directory.
* [x] Test development - turn off `DEBUG` and configure apache to serve files from the `STATIC_ROOT` and `MEDIA_ROOT`
    * Note: This may involve some extra deployment steps for static files (`collectstaticfiles`), but I'm not certain it's necessary in our case. 
* [x] Configure production server to store and serve files form `tracebase-archive` directory - `.env` updated, but permissions must be set by sys admins ([RT #101680](https://nplc-helpdesk.princeton.edu/Ticket/Display.html?id=101680))
* [x] Configure production apache to serve files from the `STATIC_ROOT` and `MEDIA_ROOT` - must be configured by sys admins ([RT #101680](https://nplc-helpdesk.princeton.edu/Ticket/Display.html?id=101680))

**Comment by hepcat72** [comment]
Sven started up the vm.  It didn't seem to be running this morning.

**Comment by lparsons** [comment]
Looks like everything is ready to go to me, closing this issue.
