### ISSUE TITLE
Add various helper methods to Model Classes

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#74]
### Feature Inspiration

When creating table list and detail views, there are some model methods that are very helpful.

### Feature Description

Add the following methods:
* [x] [`__str__`](https://docs.djangoproject.com/en/3.2/ref/models/instances/#str) 

Add the following meta options:
* [x] [`verbose_name`](https://docs.djangoproject.com/en/3.2/ref/models/options/#verbose-name)
* [x] [`verbose_name_plural`](https://docs.djangoproject.com/en/3.2/ref/models/options/#verbose-name-plural)

to each model class: 
* [x] Compound
* [x] Sample
* [x] Tissue
* [x] Animal
* [x] Study
* [x] MSRun
* [x] Protocol
* [x] PeakGroup
* [x] PeakGroupSet
* [x] PeakData

### Comment

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by hepcat72** [comment]
I'm not sure `get_absolute_url` is necessary.  The purpose is for linking between apps, as I understand it. We currently only have 1 app (`DataRepo`).  All I think we need is `{% url "view_name" rec.id %}`.  I haven't messed with `M:1` links yet, but conceptually, it doesn't seem like we need `get_absolute_url`.  When I ran into errors that suggested `get_absolute_url` as a solution, I debug-printed the values, and the access to the id value was incorrect.  I fixed that and then there was no more error.

**Comment by hepcat72** [comment]
I also have `verbose_name` and `verbose_name_plural` and `__str__` in places where they were needed in my branch.

**Comment by fkang-pu** [comment]
I will upload my branch "fkt2" this afternoon.  Right now, I haven't found better solution to get name and hyperlink for foreign key than `get_absolute_url`. This is the area I need suggestions and help.  example : https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/fkt1/DataRepo/templates/DataRepo/animal_list.html  e.g. The line: **`<td><a href="{{ animal.tracer_compound.get_absolute_url }}">{{ animal.tracer_compound.name }}</a></td>`**

**Comment by hepcat72** [comment]
OK.  Fan, I just demonstrated how you don't need `get_absolute_url`.  Here's an example.  I branched off your branch, swapped out your use of `get_absolute_url` with a `{% url %}` tag, and tested it.  It works.  This is the supported way of creating links within an app.  Check out PR #79, which merges a branch I made off your branch.

**Comment by fkang-pu** [comment]
@hepcat72 Thanks for the code in PR#79. I will change some of my code and test it.

**Comment by hepcat72** [comment]
No problem @fkang-pu. I'm looking into the subtable inclusions now.  It would be great if I could get a look at fkt2 to see how you did it.

**Comment by hepcat72** [comment]
> @lparsons @fkang-pu @hepcat72 I am working on this. Question: in [examples I have seen online](https://learndjango.com/tutorials/django-best-practices-models), `verbose_name` and `verbose_name_plural` value were lowercase, but crosschecking [Rob's branch](https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/87), they were uppercase-first. Is there a consensus on this?

I was using it to create "pretty names" to be used in (my generic) templates.  IMO, it should be presentable for users, so it should have capitalization - but we could use custom template tags to get the case we want (though personally, I think that's a bit heavy handed).  *However*, the way I was using the template tags was, I was only applying that custom capitalization if the verbose name wasn't set (I think - either that or that's how I later decided we *should* do it).

> Also, Rob, did you want me to add anything else while I am editing `Meta` , like `ordering`, based on that branch?

I added a couple orderings in my branch so that list views had a reasonable default ordering, so I say go ahead and add orderings to the models.

**Comment by hepcat72** [comment]
And I was only really using `verbose_name_plural`.

**Comment by hepcat72** [comment]
Examples from my branch:

https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/f7a545ee20677b23dcd1a60d24e2a9a9a2da59e9/DataRepo/models.py#L237-L238

https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/f7a545ee20677b23dcd1a60d24e2a9a9a2da59e9/DataRepo/models.py#L105-L108

And this is what I used for default representations.  It splits both on camelcase and underscores and applies capitalization only if everything is all lowercase.

https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/f7a545ee20677b23dcd1a60d24e2a9a9a2da59e9/DataRepo/views.py#L162-L198

**Comment by jcmatese** [comment]
Now I am curious if `verbose_name` is [always capitalized, anyway](https://code.djangoproject.com/ticket/18129)?

**Comment by jcmatese** [comment]
OK, I will push something, and we can decide then.  I definitely don't care, and would do the ucfirst on reviewers' request, if it means less formatting down the road... (i.e. I don't know the usage and web display workings)

**Comment by hepcat72** [comment]
I didn't read far on that page, but it seems to me like there was a discussion and they decided that capitalization should be how you want it to look, i.e. acronyms are capitalized (e.g. MSRun) and words are otherwise title-ized (ucfirst on each word).
