### ISSUE TITLE
incorrect sample information in PeakData from AdvancedSearch

### ISSUE THREAD

**Issue by mneinast** [Princeton-LSI-ResearchComputing/tracebase#746]
### Problem
Sample information in PeakData page on the Advanced Search is different than in PeakGroups.

Specific example found in the `cold exposure` study:  sample `col005g_02_L` is labeled with treatment `cold_4C_acute` in the PeakGroups table, but its treatment is `none` in the PeakData table.  It seems like this is true for all samples that should be `cold_4C_acute`.

Note that PeakData is selecting the correct samples based on the selected filter (treatment contains cold), just displaying the incorrect treatment value in the table.

### Steps to reproduce

See the following Advanced Search settings for PeakGroups, which has the correct sample information (correct treatment):

- Output Format:  PeakGroups
- Match: all
- Study contains cold
- Infusate contains hydroxybutyrate
- Treatment contains cold
- Tissue contains liver

In contrast, the same Advanced Search settings used for PeakData pulls the same samples, but they have the wrong Treatment value:

### Current behavior

PeakGroups using the AdvancedSearch filters above:

![image](https://github.com/Princeton-LSI-ResearchComputing/tracebase/assets/34348153/94119190-8526-4644-b304-4c8958546f10)

PeakData using the AdvancedSearch filters above:

![image](https://github.com/Princeton-LSI-ResearchComputing/tracebase/assets/34348153/25252bf0-53fa-4448-9ed4-a1b7750d10cd)

### Expected behavior
correct sample information should be displayed in PeakData table.

### Suggested Change

None provided

### Comment
perhaps this is related to the treatment value displayed as a link in the table?  The PeakGroups table shows a link but hte PeakData table displays plain text.

-----

### Assumptions

1. List of assumptions made WRT the code
2. E.g. We will assume input is correct (explaining why there is no validation)

### Limitations

1. A list of things this work will specifically not do
2. E.g. This feature will only handle the most frequent use case X

### Affected Components

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

#### GUI Change description

None provided

#### Code Change Description

None provided

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by hepcat72** [comment]
So it appears that this was "fixed", although I noticed that while to correct treatment is shown on both production and dev, that treatment is not linked in the `PeakData` results view, while it is linked in the `PeakGroups` results view.

I'm going to quickly fix that so we can close this.

**Comment by hepcat72** [comment]
#913
