### ISSUE TITLE
Update loader to handle new Iso-Autocorr format

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#751]
### Inspiration

There is now a new correction softwware in use: Iso-Autocorr (https://github.com/xxing9703/Iso-Autocorr ). The output format is similar to AccuCor, but is not yet supported by TraceBase.

### Description

Update the loading code so that we can import the new Iso-Autocorr formatted files.

### Alternatives

None

### Comment

None

-----

### Assumptions

1. List of assumptions that the code will not explicitly address/check
2. E.g. We will assume input is correct (explaining why there is no validation)

### Limitations

1. A list of things this work will specifically not do
2. E.g. This feature will only handle the most frequent use case X

### Affected Components

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

#### Interface Change description

None provided

#### Code Change Description

None provided

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by mneinast** [comment]
Examples of this format can be found in \msdata\tracebase-submissions\mneinast\col013a_perturbative infusions\
