### ISSUE TITLE
Convert google docs links in TraceBaseDocs to Markdown

### ISSUE THREAD

**Issue by hepcat72** [Princeton-LSI-ResearchComputing/tracebase#757]
### Inspiration

I was working on issue #705 and noted that I needed to change information in a google doc that I didn't have permission to edit.  However, it seems that this and other google docs linked inside the markdown were not intentionally created.  They were assumed to have all been converted to markdown.

### Description

Convert all google docs linked in the documentation to markdown saved in the repo (except for links that are to templates and forms that are intended to be used from the tracebase interface.

### Alternatives

None

### Dependencies

None

### Comment

[slack](https://tracebase.slack.com/archives/C01LFSYQHN3/p1695762293438809?thread_ts=1695752672.787459&cid=C01LFSYQHN3)

> > > I'm not sure what the document is, but I don't own it. Most of the docs for TraceBase are now at https://princeton-lsi-researchcomputing.github.io/tracebase/ and are generated from the source code
> >
> > Yes, and this document is linked from that code in step 9 under the Step-by-step instructions (see attached screenshot). Looks like @mneinast is the owner.
> >
> > ![how_to_upload_-_tracebase_documentation_720](https://github.com/Princeton-LSI-ResearchComputing/tracebase/assets/2300532/8f21370f-b471-4771-9ba2-da60f99ca546)
> > Should we remove that from the docs?
>
> Looks like something Michael missed when he converted to markdown. I say we just put the contents into the markdown docs.

-----

### Assumptions

1. List of assumptions that the code will not explicitly address/check
2. E.g. We will assume input is correct (explaining why there is no validation)

### Limitations

1. A list of things this work will specifically not do
2. E.g. This feature will only handle the most frequent use case X

### Affected Components

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

#### Interface Change description

None provided

#### Code Change Description

None provided

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by mneinast** [comment]
ah good catch - i've given you permission to edit that google doc.

I agree that all of these pages should be markdown docs so that any of us can edit them.

**Comment by hepcat72** [comment]
I also just noticed that the website is rendering these steps as 2 numbered lists (1-4 and 1-9), whereas it should contain a single 3-member numbed list with nested numbered lists:

> 1. Create a Sample Sheet (see also [How to label sample
>    information](https://docs.google.com/document/d/15C1Qp_l-QQ7eCK8Iu2wWFS8f2eUb7I11DQKz-R3mHus/edit?usp=sharing))
> [Copy](https://docs.google.com/spreadsheets/d/1To3495KxJkAtnAD9KVdzc162zKbNiYuPEVyPseQPjMQ/copy?copyComments=true)
> the TraceBase Animal and Sample Table Template.
>    1. Fill in the `Animals` sheet. Give each mouse in your study a unique ID.
>    2. Fill in the `Samples` sheet. Ensure that each `Sample Name` matches the
>       sample names in your AccuCor/Isocorr files. If you have a Tissue that is
>       not included in the existing list, please label it as you would like to
>       in the `Tissues` sheet and tell the developer you have a new Tissue.
>    3. Fill in Treatments sheet (optional) with any treatments not captured by
>       other columns (ie `Diet`).  Use `no treatment` if applicable. Provide a
>       list of treatments used in the study, along with a description of each.
> 
>       Note: In general, you should NOT edit your AccuCor files. It's simplest
>       and often best to resolve issues by editing your animal and sample table
>       file.
> 
> 2. Upload your data on Google Drive
>    1. Create a folder for your study in the [TraceBase Study Submission
>       folder](https://drive.google.com/drive/folders/1cBy3eezfr_0vmaz8RGodga6A8n3hkm1m?usp=sharing)
>       on Google Drive
>    2. Create a folder with your name (if it doesn't already exist).
>    3. Create a new folder for this study.
>    4. Copy the Animal and Sample spread sheet and any AccuCor files that should
>       be included in the study
> 
> 3. Submit the [TraceBase Study Submission
>    form](https://forms.gle/vEfJEfhPbCbkybpE7).  Complete the following:
>    1. Study Name
>    2. Link to Google Drive folder with study submission.
>    3. Mass Spectrometry Details (see [How to label Mass Spec Run
>       Information](https://docs.google.com/document/d/1Lm4br-jCB2QwbgPyzJvvgLgaO-t7Cwcq1xHyBIOlTog/edit?usp=sharing))
>

**Comment by hepcat72** [comment]
This was fixed by #797, however, the markdown needs to be re-rendered as HTML.  I.e. The markdown was updated to remove the google doc links, but the navigable docs need to be re-generated on https://princeton-lsi-researchcomputing.github.io/

**Comment by hepcat72** [comment]
I looked through these files.  This issue appears to be outdated.  The only google docs links that are not the feedback form or a powerpoint overview (which are valid google docs links to have) are ones associated with the upload/submission procedure, which will be rewritten as a part of issue #939 anyway, so there's no need to convert the existing upload pages to markdown.
