### ISSUE TITLE
Method to list PeakGroups for a Study

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#77]
### Feature Inspiration

Getting a list of PeakGroups for a given Study will provide the researchers with a sensible way to start previewing the data and will let us explore methods of generating queries across multiple tables.

### Feature Description

A method of the Study class that provides a list of PeakGroups suitable for consumption by a template.

### Alternatives Considered

It would be useful to have reusable methods to generate querysets like this that relate things across multiple tables. Hopefully, in the process of developing this feature we'll discover methods of providing search results that we can use for later, more sophisticated search implementations.

### Comment

This should perhaps be combined with #22 

-----

### Assumptions

- The search results template will be able to be combined later with a search query template as sub-templates using a master search template (see design & limitations below for context)

### Requirements

- Search results page with data mimicking the [sample spreadsheet](https://docs.google.com/spreadsheets/d/1waEyLnC3VcNz43VVT1t7Sp0td8XcVf8rrzDdCuDUVcA/edit?usp=sharing)
- Link from study detail page that shows the results relevant to the study displayed in the study detail page

### Limitations

- Only the fields currently existing in the database will be in the results (and not the collection of columns currently represented in the [sample spreadsheet](https://docs.google.com/spreadsheets/d/1waEyLnC3VcNz43VVT1t7Sp0td8XcVf8rrzDdCuDUVcA/edit?usp=sharing).
- No pagination will be implemented at this time.  Currently, only a function to retrieve the query sets and a template to only show the consolidated results.
- Field values and overall page appearance will not be customized to look pretty.  That can be done in a separate issue.
- The format of the search criteria definition that is passed to the search function may change with advanced search to support more complexity (or's, and's, parentheticals, etc)

### Affected/Changed Components

- DataRepo/views.py
- DataRepo/urls.py
- templates/search_results.html
- templates/study_detail.html

#### GUI Change description

There will be a button or link on the study detail page to view all related tissue data.  The resulting page will dsiplay a table that mimics the table in the sample provided by Caroline.

#### Code Change Description *(Pseudocode optional)*

- Create a search function in views.py
  - inputs
    - list of search criteria (where each item indicates table, field, type of comparison (e.g. greater than), and value/term
    - A format parameter (that indicates the allotment of columns to display in the results)
  - outputs
    - `render(request, "search_results.html", {"results": search_results, "columns": column_info})`
- The search results template will loop through the study table records and contain nested loops for any related table records
- Since the study detail view is not yet merged from Fan's branch, I will create a very simple placeholder version
- A search results view will be referenced in DataRepo/urls.py, similar to other urls defined there

#### Tests

- Test a search results object is the same given a study ID exact search term

**Comment by hepcat72** [comment]
@lparsons @jcmatese @fkang-pu I just filled out the issue owner section.  Essentially it's the same as what we discussed in this morning's meeting, but if you would like to review the details, let me know if you have any issues before I get too deep into it.

**Comment by lparsons** [comment]
This looks good to me. As I'm working on the computed values, I'm realizing that it might work if the results are, at their heart, a list of PeakGroups, perhaps with some prefetch relations. That way we could retrieve the computed values for each PeakGroup and the related fields in the template.

**Comment by hepcat72** [comment]
Are you saying that all the columns in the sample tissue file are from the PeakGroup table?

**Comment by lparsons** [comment]
> Are you saying that all the columns in the sample tissue file are from the PeakGroup table?

For sure not. There are a lot of related fields, thus the need to prefetch some of the related things. I guess I'm just saying that it would be very handy if in the template has an instance of the PeakGroup handy.

**Comment by hepcat72** [comment]
It there are PeakGroup fields in the sample sheet, those objects will be there.  If there aren't, it would be easy to add when the computed values are ready.

**Comment by lparsons** [comment]
I believe the spreadsheet has one row per PeakGroup.

**Comment by hepcat72** [comment]
Well either way, the strategy should easily support adding data via objects if they aren't there on my first pass.  Sounds like they will be, but obviously I'm focussing on function the function as opposed to the particular data. And it sounds like, if I understand you correctly, adding the computed values will be very easy.

**Comment by fkang-pu** [comment]
@hepcat72 Looks good to me, except I have a couple of comments:

1. in my "fkt2" branch, I have home.html, base*.html in templates/, but created templates for each model in /templates/DataRepo/ based on Django's default location and name convention for [CBV](https://docs.djangoproject.com/en/3.2/topics/class-based-views/generic-display/). 
  example: templates/DataRepo/compound_list.html
2. for search_results.html, I would prefer a more specific name, just in case we need to add other templates for database search later on (e.g. search_peakdata_per_study.html or search_peakdata.html)

**Comment by hepcat72** [comment]
> @hepcat72 Looks good to me, except I have a couple of comments:
> 
> 1. in my "fkt2" branch, I have home.html, base*.html in templates/, but created templates for each model in /templates/DataRepo/ based on Django's default location and name convention for [CBV](https://docs.djangoproject.com/en/3.2/topics/class-based-views/generic-display/).
>    example: templates/DataRepo/compound_list.html

Yes.  I wasn't planning on establishing locations for templates.  In fact, I'm pretty much copying the study template from your branch just to have something to navigate, although, I wasn't going to fully integrate it.  It will just be a placeholder.

Although, I did wonder about where to put the search results template.  That too can be easily changed though.  I just need something to look at.  We can move it to wherever.  My focus is only on the functionality.  I expect that how it looks and where the files go will definitely change.

> 2. for search_results.html, I would prefer a more specific name, just in case we need to add other templates for database search later on (e.g. search_peakdata_per_study.html or search_peakdata.html)

I did think about a different name, perhaps based on the format, although I might craft the search results template to be reusable for multiple search types.  So the name could be based on the structure of the resulting table, but in keeping with the core search functionality issue, it could handle multiple formats - and I just didn't decide which way to go yet.  For now, I'm going to keep it simple, but overall, I'm planning to apply what I learned in the generic template work.

**Comment by hepcat72** [comment]
After just performing some basic setup, I think I'll establish a different search results template for each results format.  I think that makes editing easier.  Personally, I prefer the generic/dynamic path, but  the specific/static one might develop faster.  I'll keep the interfaces the same though so that it would be easier to transition to a generic/dynamic strategy as things get bigger.

**Comment by hepcat72** [comment]
I went through the columns in Caroline's file and traced the way I'll need to access all the data, given a study record.  At the bottom, I worked out the `select_related()` arguments I would need to get all the nested objects.  I'm not sure how to obtain `seruminfusate`.  I'm skeptical it can be done in 1 query, so I'm going to focus on everything else first and tackle it after I get everything else worked out.

Here are my notes, with the queryset call at the bottom.  I'll then access the data for each column in a series of nested loops in the template to render the table (note, the access in the PRM doesn't use the id fields and I may need to add some related_names to the model relation definitions):

```
## Fields from Caroline's spreadsheet:

### Compound
	PeakGroup.name
	Study:Animal:Sample:MSRun:PeakGroup
	Study.id -> Animal.{study_id -> id} -> Sample.{animal_id -> id} -> MSRun.{sample_id -> id} -> PeakGroup.{ms_run_id -> PeakGroup.name}
### C_Label
	Animal.tracer_labeled_atom + Animal.tracer_labeled_count
	Study:Animal
	Study.animals -> Animal.{tracer_labeled_atom + tracer_labeled_count}
### Sample
	Sample.name
	Study:Animal:Sample
	Study.id -> Animal.{study_id -> sample_id} -> Sample.{id -> name}
### fraction #"normalized"
	PeakData.fraction() #cached_property
		self.corrected_abundance / self.peak_group.total_abundance
	Study:Animal:Sample:MSRun:PeakGroup:PeakData
	Study.id -> Animal.{study_id -> id} -> Sample.{animal_id -> id} -> MSRun.{sample_id -> id} -> PeakGroup.{ms_run_id -> PeakGroup.id} -> PeakData.{peak_group_id -> PeakData.fraction}
### tissue
	Tissue.name
	Study:Animal:Sample:Tissue
	Study.id -> Animal.{study_id -> id} -> Sample.{animal_id -> tissue_id} -> Tissue.{id -> name}
### mouse
	Animal.name #They included ID in the example table, but Lance said it should be name
	Study:Animal
	Study.id -> Animal.{study_id -> name}
### tic #"corrected"
	PeakGroup.total_abundance() #cached_property
	Study:Animal:Sample:MSRun:PeakGroup
	Study.id -> Animal.{study_id -> id} -> Sample.{animal_id -> id} -> MSRun.{sample_id -> id} -> PeakGroup.{ms_run_id -> total_abundance}
### seruminfusate
	PeakGroup.enrichment_fraction() #DOES NOT EXIST AS A CACHED PROPERTY.  IT WOULD HAVE TO BE CALCULATED ON THE FLY.  IT IS CALCULATED ON A SELECTION OF RECORDS ASSOCIATED WITH SERUM SAMPLES
		PeakGroup.objects.filter(ms_run__sample_id=final_serum_sample.id)
		    .filter(compounds__id=self.ms_run.sample.animal.tracer_compound.id)
		    .get().enrichment_fraction
	Study:Animal:Sample:MSRun:PeakGroup
	Study.id -> Animal.{study_id -> id} -> Sample.{animal_id -> id} -> MSRun.{sample_id -> id} -> PeakGroup.{ms_run_id -> enrichment_fraction()}
		Cannot use this straight.  Need to filter PeakGroups on Study, grab all the unique compounds, 
### normfraction
	PeakGroup.normalized_labeling() #cached_property
	Study:Animal:Sample:MSRun:PeakGroup
	Study.id -> Animal.{study_id -> id} -> Sample.{animal_id -> id} -> MSRun.{sample_id -> id} -> PeakGroup.{ms_run_id -> normalized_labeling()}
### infusate
	Compound.name (via Animal.tracer_compound_id)
	Study:Animal:Compound
	Study.id -> Animal.{study_id -> tracer_compound_id} -> Compound.{id -> name}
### experiment
	Study.name
	Study
	Study.{id -> name}
### state
	Animal.feeding_status
	Study:Animal
	Study.id -> Animal.{study_id -> feeding_status}
### infusionrate
	Animal.tracer_infusion_rate
	Study:Animal
	Study.id -> Animal.{study_id -> tracer_infusion_rate}
### infusateconc
	Animal.tracer_infuser_concentration
	Study:Animal
	Study.id -> Animal.{study_id -> tracer_infuser_concentration}


So the select_related things I need are:

	Study
		Animal:Compound
		Animal:Sample:Tissue
		Animal:Sample:MSRun:PeakGroup:PeakData

	This should be able to be accomplished with:

		study_obj.objects.select_related('animal__compound','animal__sample__tissue','animal__sample__msrun__peakgroup__peakdata')
```

**Comment by hepcat72** [comment]
Dupe of #22
