### ISSUE TITLE
Update validation interface for the new input files

### ISSUE THREAD

**Issue by hepcat72** [Princeton-LSI-ResearchComputing/tracebase#814]
### Inspiration

Issue #712 added new input files that are a part of validating data submissions.  Those files are not a part of the validation form currently.

### Description

Add input form elements for the new mzXML files.

### Alternatives

None

### Dependencies

This issue cannot be started until the completion of the following issue(s)/pull request(s):

- #712

### Comment

This will probably also require adding the `loading.yaml` file, since providing default values will likely be necessary.  The interface should probably create one that can be downloaded and is as fleshed out as possible.

-----

### Assumptions

1. List of assumptions that the code will not explicitly address/check
2. E.g. We will assume input is correct (explaining why there is no validation)

### Limitations

1. A list of things this work will specifically not do
2. E.g. This feature will only handle the most frequent use case X

### Affected Components

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

#### Interface Change description

None provided

#### Code Change Description

None provided

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by lparsons** [comment]
I suspect this is out of date and should be closed.
