### ISSUE TITLE
Links to data on Archive Files list page are broken

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#843]
### Problem

The links to Peak Group Data and Peak Data on the Archive Files list page are broken.

### Steps to reproduce

1. Click on "Archive Files" in the left nav bar
2. Click on "Peak Group Data" or "Peak Data" in one of the rows

### Current behavior

```
Page not found (404)
'Ambiguous model instance [ArchiveFile].  Must specify one of [PeakAnnotationFile,MZFile,RAWFile].'
Request Method:	GET
Request URL:	http://127.0.0.1:8000/DataRepo/search_basic/ArchiveFile/id/iexact/1/peakgroups/
Raised by:	DataRepo.views.search.basic.search_basic
Using the URLconf defined in TraceBase.urls, Django tried these URL patterns, in this order:

admin/
[name='home']
DataRepo/ [name='home']
DataRepo/ upload [name='upload']
DataRepo/ validate [name='validate']
DataRepo/ validatedown [name='validatedown']
DataRepo/ search_basic/<str:mdl>/<str:fld>/<str:cmp>/<str:val>/<str:fmt>/ [name='search_basic']
The current path, DataRepo/search_basic/ArchiveFile/id/iexact/1/peakgroups/, matched the last one.
```

### Expected behavior

A list of data associated with the peak annotation file

### Suggested Change

Might be useful to create a separate list view for archive files of `data_type` `ms_peak_annotation` and `ms_data`.

### Comment

None

-----

### Assumptions

1. List of assumptions made WRT the code
2. E.g. We will assume input is correct (explaining why there is no validation)

### Limitations

1. A list of things this work will specifically not do
2. E.g. This feature will only handle the most frequent use case X

### Affected Components

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

#### GUI Change description

None provided

#### Code Change Description

None provided

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by hepcat72** [comment]
I have a fix for this on tracebase-dev. @lparsons, could you go there are poke around to see if there are any issues.  I only did the list view. Going to glance at the details view momentarily.

**Comment by hepcat72** [comment]
OK.  The details page is fixed now too.  I'll submit a PR after linting.
