### ISSUE TITLE
Double check compound naming and HMDB for Sedoheptulose 7-phosphate

### ISSUE THREAD

**Issue by hepcat72** [Princeton-LSI-ResearchComputing/tracebase#848]
### Inspiration

The compounds in the example data appear to not be consistent with the Rabinowitz repo.

### Description

Issue relocated from https://github.com/Princeton-LSI-ResearchComputing/tracebase/issues/847

> Because name and HMDB ID differs between consolidated list
> https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/4bb4583c9898868cdb5800b9d0a2dd6bf3228339/DataRepo/data/examples/compounds/consolidated_tracebase_compound_list.tsv#L51
> 
> and the Rabinowitz data repo
> 
> https://github.com/PrincetonUniversity/tracebase-rabinowitz-data/blob/9d44914f73de1491f2cd44dcf75f115f3ce45762/compounds/compounds.tsv#L164
> 
> 
> Also, regarding differences, there are 52 lines in the former and 184 lines in the latter, so I think the former ("consolidated") _might_ just be for example/test data, and is not comprehensive (consolidated, but perhaps in a different context?).

### Alternatives

None

### Dependencies

None

### Comment

None

-----

### Assumptions

1. List of assumptions that the code will not explicitly address/check
2. E.g. We will assume input is correct (explaining why there is no validation)

### Limitations

1. A list of things this work will specifically not do
2. E.g. This feature will only handle the most frequent use case X

### Affected Components

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

#### Interface Change description

None provided

#### Code Change Description

None provided

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by lparsons** [comment]
Duplicate of #847?

**Comment by hepcat72** [comment]
Yeah, for some inane reason, I'd thought #847 was in the rabinowitz repo.
