### ISSUE TITLE
When no results are found, Peak Group and Peak Data links from Animal detail page return a 404 error

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#854]
### Problem

Clicking on the Peak Group or Peak Data links from the Animal detail page results in a 404 error when no records are found.

### Steps to reproduce

1. Navigate to the Animal detail page: https://tracebase.princeton.edu/DataRepo/animals/143/
2. Click on "Peak Data"

### Current behavior

```
Page not found (404)
No records found matching [Animal.id=143].
Request Method:	GET
Request URL:	https://tracebase-dev.princeton.edu/DataRepo/search_basic/Animal/id/iexact/143/peakdata/
Raised by:	DataRepo.views.search.basic.search_basic
Using the URLconf defined in TraceBase.urls, Django tried these URL patterns, in this order:

admin/
[name='home']
DataRepo/ [name='home']
DataRepo/ upload [name='upload']
DataRepo/ validate [name='validate']
DataRepo/ validatedown [name='validatedown']
DataRepo/ search_basic/<str:mdl>/<str:fld>/<str:cmp>/<str:val>/<str:fmt>/ [name='search_basic']
The current path, DataRepo/search_basic/Animal/id/iexact/143/peakdata/, matched the last one.
```

### Expected behavior

An empty list of peak data records or a message explaining that no records are found.

### Suggested Change

None provided

### Comment

None

-----

### Assumptions

1. List of assumptions made WRT the code
2. E.g. We will assume input is correct (explaining why there is no validation)

### Limitations

1. A list of things this work will specifically not do
2. E.g. This feature will only handle the most frequent use case X

### Affected Components

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

#### GUI Change description

None provided

#### Code Change Description

None provided

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by hepcat72** [comment]
This has apparently already been fixed.  See the corresponding records on the dev site:

https://tracebase-dev.princeton.edu/DataRepo/animals/143/
https://tracebase-dev.princeton.edu/DataRepo/search_basic/Animal/id/iexact/143/peakgroups/
https://tracebase-dev.princeton.edu/DataRepo/search_basic/Animal/id/iexact/143/peakdata/
