### ISSUE TITLE
Add an mzXML directory option

### ISSUE THREAD

**Issue by hepcat72** [Princeton-LSI-ResearchComputing/tracebase#893]
### Inspiration

It is laborious to account for all subdirectories where mzXML files live, even if supplying a glob.

### Description

It would be nice to be able to supply an mzXML root directory, and walk the directory to find all the mzXML files.  Add an mzXML directory argument/option to:
- `StudyLoader`
- `load_study`
- `MSRunsLoader`
- `load_msruns`

### Alternatives

Provide a glob utilizing curly braces.

### Dependencies

None

### Comment

None

-----

### Assumptions

1. List of assumptions that the code will not explicitly address/check
2. E.g. We will assume input is correct (explaining why there is no validation)

### Limitations

1. A list of things this work will specifically not do
2. E.g. This feature will only handle the most frequent use case X

### Affected Components

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

#### Interface Change description

None provided

#### Code Change Description

None provided

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by lparsons** [comment]
Adding an alternative option:
* Provide a directory and search it for mzXML files. This could also extend to the CLI parameter.

**Comment by hepcat72** [comment]
Huh. I'd forgotten I'd created this issue.

**Comment by hepcat72** [comment]
The yaml file is deprecated.  Going to edit this issue to apply to the refactored load scripts.

**Comment by hepcat72** [comment]
Done/merged.
