### ISSUE TITLE
Multiple labeled elements malformed in `Labeled Element(s)` column in included template on Animal Details page

### ISSUE THREAD

**Issue by hepcat72** [Princeton-LSI-ResearchComputing/tracebase#894]
### Problem

It appears that when there are multiple labeled elements (possibly also requiring multiple tracers with multiple labeled elements), the Labeled Element(s) column is incorrectly populated (contains a repeated element, once with a space and once without).

### Steps to reproduce

1. Observed an animal that has a `Lysine-[13C6,15N2]` tracer, e.g.: https://tracebase.princeton.edu/DataRepo/compounds/446/

### Current behavior

The labeled elements column displays as `C,N, C`.

![lysinemallabel](https://github.com/user-attachments/assets/552b9abb-31db-4dfd-acb1-9b8f5e9c35e0)

### Expected behavior

Should be either `C, N` or `C,N`.  Probably with a space is better.

### Suggested Change

I tried following the code, but had difficulty tracking down the source of the problem, though I don't think it's a data problem because elements associated with that tracer/animal display correctly in the advanced search.

### Comment

None

-----

### Assumptions

1. List of assumptions made WRT the code
2. E.g. We will assume input is correct (explaining why there is no validation)

### Limitations

1. A list of things this work will specifically not do
2. E.g. This feature will only handle the most frequent use case X

### Affected Components

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

#### GUI Change description

None provided

#### Code Change Description

None provided

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by mneinast** [comment]
I suspect this occurs when multiple tracers are included in a single infusate, and one tracer is dual labeled (ie. 13C, 15N) and a second tracer is single labeled (ie 13C).  This then appears in the table as `C,N, C`.

I'm imagining that if we had an infusate like:
 - [13C-15N]-lysine
 - [13C]-valine
 - [2H-13C]-glucose
the table would display `C,N, C, H,C`

The purpose of this labeled element(s) column is to indicate what forms of labeling are possible in the measured compounds.  So, in the original example, it would only show `C, N`.  In the theoretical example, it would show `C, N, H`.

**Comment by hepcat72** [comment]
> I suspect this occurs when multiple tracers are included in a single infusate, and one tracer is dual labeled (ie. 13C, 15N) and a second tracer is single labeled (ie 13C). This then appears in the table as `C,N, C`.
> 
> I'm imagining that if we had an infusate like:
> 
> * [13C-15N]-lysine
> * [13C]-valine
> * [2H-13C]-glucose
>   the table would display `C,N, C, H,C`
> 
> The purpose of this labeled element(s) column is to indicate what forms of labeling are possible in the measured compounds. So, in the original example, it would only show `C, N`. In the theoretical example, it would show `C, N, H`.

This issue is documented and I believe it's in the beta 3 release milestone (either it is or we agreed to move it there). I did a little shallow digging into it awhile back. I couldn't pin it down exactly, but I confirmed that the data in the database is correct. I suspect the issue may be located in the dataframes code, but I can't say for sure.

**Comment by hepcat72** [comment]
I figured out what's going on here.  This happens when an infusate has multiple tracers and not all tracers have the same labeled elements.  You end up with a string of elements where the space-separated ones are the unique combination of elements for 1 or more tracers with that complement of elements.  So in the example above:

> [13C-15N]-lysine
> [13C]-valine
> [2H-13C]-glucose

lysine results in `C,N`
valine results in `C`
glucose results in `H,C`

...and they're joined together with a comma-space.

Not sure yet how to fix it.

This is happening because there was an assumption made that all the tracers would have all the same labeled elements (or it was overlooked that it could be different).  The combination of labeled elements in each tracer is made into an ordered comma-delimited string, then `unique` is called on those strings, so if we had:

> [13C-15N]-lysine
> [13C]-valine
> [2H-13C]-glucose
> [13C]-glutamine

we would still end up with `C,N, C, H,C`.

**Comment by hepcat72** [comment]
@mneinast - Just was speaking with Fan about this issue in the meeting this morning and realized I might have misunderstood what the intention was for the `Labeled Elements` column. I had worked on this issue to "fix" it so that something like `C,N, C, H,C` would instead appear as `C, H, N`. But Fan pointed out that the purpose of displaying it as `C,N, C, H,C` was intentional: to represent that combinations of elements that exist among the tracers.

I had learned during my "fix" that that's why it displayed the way it did.  So I guess my question is (and I'll ask you about it when we meeting later): do you want the labeled element combinations that exist among the tracers, or a unique list of labels?  If you want the combinations, I can just close my PR without merging, though we might consider addressing the header name to somehow explain the meaning of the data in that column, because it wasn't clear to me why it seemed to show repeated elements.
