### ISSUE TITLE
Ability to submit files using MSData share

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#904]
### Inspiration

Data submissions require researchers to organize their files in location accessible to the curators. We have used Google Drive in the past, but that can be unwieldy, esp. for larger submission with mzXML files. Researchers are already familiar with the `MSData` shared drive and they would often prefer that to Google Drive. Similarly, getting files off of the MSData share is easier for curators than Google Drive.

### Description

* [x] Work with system admins to create a top-level submission directory with permissions suitable for having lab members organize submissions
* [x] Create an organization underneath the top-level submission directory to help researchers prepare submissions
* [x] Update the submission processing documentation to include details on how to handle submissions from MSData
* [x] Update the submission instructions and form to indicate how/where researchers should place newly submitted files

### Alternatives

None

### Comment

None

-----

### Assumptions

1. List of assumptions that the code will not explicitly address/check
2. E.g. We will assume input is correct (explaining why there is no validation)

### Limitations

1. A list of things this work will specifically not do
2. E.g. This feature will only handle the most frequent use case X

### Affected Components

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

#### Interface Change description

None provided

#### Code Change Description

None provided

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by hepcat72** [comment]
I'm not familiar with an MSData share, but reading between the lines, my guess is that it's more convenient for researchers because the files are coming from a windows system that runs the mass spec? I did a quick google and one of the top results is a bioconductor msdata package. I don't know if that should have any influence on how this or the helper utility issue should be implemented, but it's something to note at least.

As far as organizing files for submission, it would probably help to consult the lab folks before finalizing a directory structure.  We could propose a structure and ask for feedback, perhaps something like this:
```
tracebase_submissions/
    <user>/
        <study>/
            <study>.xlsx
            <peak_analysis>/
                <accucor|isocorr>.xlsx (only 1 accucor/isocorr file in a single <peak_analysis> dir - probably the same name as the accucor file)
                ms_data/  (raw/mzXML files)
                    *.mzXML (used in the <peak_analysis>)
            unanalyzed_ms_data/  (raw/mzXML files)
```

**Comment by lparsons** [comment]
This is ready to go, at least the first implementation of it is ready.
