### ISSUE TITLE
Handle additional non-sample columns from El-Maven

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#91]
### Feature Inspiration

It appears that newer versions of El-Maven output additional non-sample columns (namely `adductName` and `Max Peak`). These columns will appear in the "Original" worksheet of an AccuCor file.

This is currently pending a fix in AccuCor as well: https://github.com/XiaoyangSu/AccuCor/issues/23

### Feature Description

Non-sample columns should be treated as such. Currently, the loading script will see these new columns as samples and thus attempt to find matching samples in the database, which will fail. Instead, they should be ignored along with the other non-sample columns.

Since AccuCor has not been updated to handle these columns properly, they will appear in that output as well. Given that fact, and the fact that some users have asked for AccuCor to output some additional columns in the "Corrected" and "Normalized" sheets, it would be useful to have TraceBase ignore those columns in those other sheets (in addition to the "Original" worksheet). 

### Alternatives Considered

None

### Comment

-----

### Assumptions

- These new columns (`adductName` and `Max Peak`), plus the existing list of "standard" El-Maven columns are the only non-sample columns in the file
- Columns in any sheet of an AccuCor file that are in the list of "standard" should be treated as non-sample columns

### Requirements

- The column names from El-Maven must match the list of "non-sample" columns exactly

### Limitations

- Additional non-sample columns added by El-Maven may not be properly ignored by the loader and thus will cause problems when attempting to load those files

### Affected/Changed Components

- `AccuCorDataLoader` in `utils.py`

#### GUI Change description

None

#### Code Change Description *(Pseudocode optional)*

* Add new columns to list of non-sample columns
* Ensure any of the non-sample columns in the Corrected and Normalized sheets don't cause problems

#### Tests

Test loading a file with the new columns in the Original sheet
Test loading a file with the new columns in the Original, Corrected, and Normalized sheet

**Comment by hepcat72** [comment]
Do those new columns appear before or after the sample columns (I assume before).  If I recall the code loading correctly, I think it computes the "last" non-sample column.  So it might be that the current code could tolerate the new columns unless the new columns are the last non-sample columns.

I had considered including the sample name format as a possible metric in that determination, but opted not to make that as an issue.

**Comment by jcmatese** [comment]
Likely code in question : 
https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/3b63c66499dbb7321821146f8cbc13f53efb842b/DataRepo/utils.py#L341-L382

**Comment by lparsons** [comment]
> Do those new columns appear before or after the sample columns (I assume before). If I recall the code loading correctly, I think it computes the "last" non-sample column. So it might be that the current code could tolerate the new columns unless the new columns are the last non-sample columns.

Good thinking, in fact that is exactly what we discussed in the last developers meeting. Unfortunately, one of the columns, I believe `Max Peak`, appears as the "last" non-sample column. So the current code would likely tolerate the new `adductName` column, but not the `Max Peak` column.

> I had considered including the sample name format as a possible metric in that determination, but opted not to make that as an issue.

I didn't think there was any way to predict the sample name format. If you know of a way to handle this more elegantly or robustly, I'd love to know, since it would be helpful for AccuCor as well.

**Comment by hepcat72** [comment]
> > I had considered including the sample name format as a possible metric in that determination, but opted not to make that as an issue.
> 
> I didn't think there was any way to predict the sample name format. If you know of a way to handle this more elegantly or robustly, I'd love to know, since it would be helpful for AccuCor as well.

I just recalled your comment while looking at Accucor data.  At the time, I was busy, so I came back to respond.  I had been thinking simply of a pattern, like `^[A-Za-z]{1,4}-[a-z]{2}\d+$` - but that's just based on a single file sample.  There must be some definition somwhere.  Currently, none of the other column headers would match that.

**Comment by lparsons** [comment]
It looks like [the only new El-Maven column is actually `adductName`](https://github.com/XiaoyangSu/AccuCor/issues/23#issuecomment-882633228).
